### PR TITLE
[IMP] migration of fiscal year opening journal entries

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Implements the changes to account migration script to fix https://github.com/OCA/OpenUpgrade/issues/622

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As you know, this is not valid for Spain. You can include a condition to move (not delete) all the entries if the company country is Spain.

**Comment by StefanRijnhart** [comment]
Can you rebase instead of merging to prevent these commits from showing up in the main branch history?
How are opening balances used in Spain? Can we detect this method regardless of the installed module?
Would you like to attempt to replace the subqueries by joins? Or I could do it after the optimistic merge.

**Comment by JordiBForgeFlow** [comment]
@StefanRijnhart I need your help to rebase. I'm having trouble understanding how to squash the commits.

As for the opening balances, in spain a journal entry is created at the end of the year to set the P&L accounts to 0, and move the net profit to the balance sheet. There's really no way to detect this method, regardless of the installed module, at least that I know of.

As for replacing the subqueries by joins, please feel free to improve after an optimistic merge.

**Comment by StefanRijnhart** [comment]
We can squash at merge time using the GitHub dropdown button next to 'Merge Pull Request'. You are right, we can optimize the code later. Also, in a further improvement this had better be done by company, as periods are company aware. :+1:

**Comment by StefanRijnhart** [comment]
Merging this after too long of a delay to be optimistic

**Pull request merged**
