### PR TITLE
[10.0][FIX] module coverage list

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This PR fixes two errors I found in the module coverage list.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why is Travis red? Have you rebased on latest branch?

**Comment by MiquelRForgeFlow** [comment]
Yes, it's completely rebased to v10 branch with last commits being from @NL66278 in the account PR. It's very strange. I don't have any idea what is happening.

Edit: Now rebased with the payment added. Let's see.

**Comment by pedrobaeza** [comment]
Now it's OK. Travis X files.

**Comment by MiquelRForgeFlow** [comment]
Hehe. I think what happened is that you merged the payment PR when this PR was still in yellow.

**Comment by pedrobaeza** [comment]
Yeah, it can be, as this uses a dynamic checkout...

**Pull request merged**
