### PR TITLE
[9.0][OCA/sale-workflow] Sale exception module renamed

### PR DESCRIPTION
**Pull request by atchuthan**
Renamed module from sale_exceptions --> sale_exception as per suggestions from pedrobaeza.

cc: @gurneyalex @guewen @pedrobaeza

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
You have forgotten to put commas at the end of the line.

**Comment by atchuthan** [comment]
@pedrobaeza: corrections done

**Comment by pedrobaeza** [comment]
Thanks!

:+1:

**Pull request merged**
