### PR TITLE
[14.0][MIG] event_crm

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Nothing to do.

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Review by RaulOForgeFlow — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
I think these nothing-to-do PRs can be best merged manually without ocabot triggering another run from the github workflows, so I'll do just that, even if it feels a bit dirty.

**Comment by pedrobaeza** [comment]
But the dependency chain has been respected?

**Comment by StefanRijnhart** [comment]
I would think yes, because otherwise, CI would not have been green on the PR.

**Comment by pedrobaeza** [comment]
I see that both `event` and `crm` has been merged, but CI is not necessarily saying the truth, as if there are no migration scripts, but there's nothing that provokes an error, CI will be green.

**Comment by StefanRijnhart** [comment]
OK. I did check for the 'blocked by dependency' label before merging but I'll do an extra check when merging manually next time.

**Comment by pedrobaeza** [comment]
I think @MiquelRForgeFlow is very conscientious with the labels, so it can be OK if it has been removed. Sorry for the noise.

**Comment by StefanRijnhart** [comment]
That's true, @MiquelRForgeFlow is very good with those labels!

**Pull request merged**
