### PR TITLE
[FIX] Some modules are not marked for upgrade with -u all

### PR DESCRIPTION
**Pull request by StefanRijnhart**
In standard Odoo, '--update all' just means: '--update base + upward (installed) dependencies'.
This breaks the chain when only new (glue) modules are encountered. E.g. purchase in 8.0 depends
on stock_account and report, both of which are new. They may be installed, but purchase as an
upward dependency is not selected for upgrade. Therefore, explicitely select all installed
modules for upgrading in OpenUpgrade.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the patch. :+1:

Does it apply to previous versions?

**Comment by StefanRijnhart** [comment]
Thanks for the review, quick as ever ;-) No, I think this is the first time we encountered this, because an existing module only depends on new modules in the new version.

**Comment by pedrobaeza** [comment]
OK, good to know.

Thanks again.

**Comment by guewen** [comment]
:+1:

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
