### PR TITLE
9.0 upstream 2016 07 21

### PR DESCRIPTION
**Pull request by hbrunn**
Sync latest upstream. Conflict resolution:

``` ShellSession
$ git show 9cf6466
commit 9cf6466b7a49e0938cff1197df86d4aa680c095f
Merge: 397eebe f0620a9
Author: Holger Brunn <hbrunn@therp.nl>
Date:   Thu Jul 21 06:59:35 2016 +0200

    Merge remote-tracking branch 'odoo/9.0' into 9.0-upstream-2016-07-21

diff --cc README.md
index f6be628,8a566fb..77afba8
--- a/README.md
+++ b/README.md
@@@ -1,9 -1,39 +1,8 @@@
 -[![Build Status](http://runbot.odoo.com/runbot/badge/flat/1/9.0.svg)](http://runbot.odoo.com/runbot)
 -[![Tech Doc](http://img.shields.io/badge/9.0-docs-8f8f8f.svg?style=flat)](http://www.odoo.com/documentation/9.0)
 -[![Help](http://img.shields.io/badge/9.0-help-8f8f8f.svg?style=flat)](https://www.odoo.com/forum/help-1)
 -[![Nightly Builds](http://img.shields.io/badge/9.0-nightly-8f8f8f.svg?style=flat)](http://nightly.odoo.com/)
 +[![Build Status](https://travis-ci.org/OCA/OpenUpgrade.svg?branch=9.0)](https://travis-ci.org/OCA/OpenUpgrade)

 -Odoo
 -----
 +![OpenUpgrade logo](/openerp/openupgrade/doc/source/images/OpenUpgrade.png?raw=true)

 -Odoo is a suite of web based open source business apps.
 -
 -The main Odoo Apps include an <a href="https://www.odoo.com/page/crm">Open Source CRM</a>, <a href="https://www.odoo.com/page/website-builder">Website Builder</a>, <a href="https://www.odoo.com/page/e-commerce">eCommerce</a>, <a href="https://www.odoo.com/page/project-management">Project Management</a>, <a href="https://www.odoo.com/page/accounting">Billing &amp; Accounting</a>, <a href="https://www.odoo.com/page/point-of-sale">Point of Sale</a>, <a href="https://www.odoo.com/page/employees">Human Resources</a>, Marketing, Manufacturing, Purchase Management, ...  
 -
 -Odoo Apps can be used as stand-alone applications, but they also integrate seamlessly so you get
 -a full-featured <a href="https://www.odoo.com">Open Source ERP</a> when you install several Apps.
 -
 -
 -Getting started with Odoo
 --------------------------
 -For a standard installation please follow the <a href="https://www.odoo.com/documentation/9.0/setup/install.html">Setup instructions</a>
 -from the documentation.
 -
 -If you are a developer you may type the following command at your terminal:
 -
 -    wget -O- https://raw.githubusercontent.com/odoo/odoo/9.0/odoo.py | python
 -
 -Then follow <a href="https://www.odoo.com/documentation/9.0/tutorials.html">the developer tutorials</a>
 -
 -
 -For Odoo employees
 -------------------
 -
 -To add the odoo-dev remote use this command:
 -
 -    $ ./odoo.py setup_git_dev
 -
 -To fetch odoo merge pull requests refs use this command:
 -
 -    $ ./odoo.py setup_git_review
 +OpenUpgrade
 +===========

 +This <a href="https://odoo-community.org">OCA</a> project aims to provide an Open Source upgrade path for <a href="https://github.com/odoo/odoo">Odoo</a>. It is hosted at <a href="https://github.com/oca/openupgrade">GitHub</a>. For documentation, see <a href="https://doc.therp.nl/openupgrade">here</a>.
- 
diff --cc openerp/addons/base/ir/ir_model.py
index ea5fe2b,e462b15..bb33b2c
--- a/openerp/addons/base/ir/ir_model.py
+++ b/openerp/addons/base/ir/ir_model.py
@@@ -1237,11 -1237,7 +1254,11 @@@ class ir_model_data(osv.osv)
                          _logger.info('Deleting orphan external_ids %s', external_ids)
                          self.unlink(cr, uid, external_ids)
                          continue
 +                    # OpenUpgrade specific start
 +                    if not self.pool.get(field.model):
 +                        continue
 +                    # OpenUpgrade specific end
-                     if field.name in openerp.models.LOG_ACCESS_COLUMNS and self.pool[field.model]._log_access:
+                     if field.name in openerp.models.LOG_ACCESS_COLUMNS and field.model in self.pool and self.pool[field.model]._log_access:
                          continue
                      if field.name == 'id':
                          continue
diff --cc openerp/fields.py
index 6907cb8,b7795ec..0607f2e
--- a/openerp/fields.py
+++ b/openerp/fields.py
@@@ -11,8 -11,8 +11,9 @@@ from types import NoneTyp
  import logging
  import pytz
  import xmlrpclib
 +from psycopg2 import OperationalError

+ from openerp.sql_db import LazyCursor
  from openerp.tools import float_round, frozendict, html_sanitize, ustr, OrderedSet
  from openerp.tools import DEFAULT_SERVER_DATE_FORMAT as DATE_FORMAT
  from openerp.tools import DEFAULT_SERVER_DATETIME_FORMAT as DATETIME_FORMAT
@@@ -1072,12 -1100,7 +1101,12 @@@ class Float(Field)
      @property
      def digits(self):
          if callable(self._digits):
 +            # OpenUpgrade: try to reuse the migration cursor, to prevent
 +            # transaction locks
 +            migration_cursor = fields.get_migration_cursor()
 +            if migration_cursor:
 +                return self._digits(migration_cursor)
-             with fields._get_cursor() as cr:
+             with LazyCursor() as cr:
                  return self._digits(cr)
          else:
              return self._digits
diff --cc openerp/modules/loading.py
index 0a2a218,18592b5..59a4dd1
--- a/openerp/modules/loading.py
+++ b/openerp/modules/loading.py
@@@ -336,9 -276,10 +336,10 @@@ def load_modules(db, force_demo=False, 
          # processed_modules: for cleanup step after install
          # loaded_modules: to avoid double loading
          report = registry._assertion_report
 -        loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
 +        loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report, upg_registry=upg_registry)

-         if tools.config['load_language'] or update_module:
+         load_lang = tools.config.pop('load_language')
+         if load_lang or update_module:
              # some base models are used below, so make sure they are set up
              registry.setup_models(cr, partial=True)

diff --cc openerp/osv/fields.py
index b1616c9,db35864..275c3ad
--- a/openerp/osv/fields.py
+++ b/openerp/osv/fields.py
@@@ -24,10 -24,8 +24,9 @@@ import loggin
  import pytz
  import re
  import xmlrpclib
 +import threading
  from operator import itemgetter
- from contextlib import contextmanager
 -from psycopg2 import Binary
 +from psycopg2 import Binary, OperationalError

  import openerp
  import openerp.tools as tools
@@@ -34,38 -33,10 +34,34 @@@ from openerp.sql_db import LazyCurso
  from openerp.tools.translate import _
  from openerp.tools import float_repr, float_round, frozendict, html_sanitize
  import json
- from openerp import SUPERUSER_ID, registry
+ from openerp import SUPERUSER_ID

 +# OpenUpgrade start
 +migration_cursors = {}
 +
 +
 +def set_migration_cursor(cr=None):
 +    """ Store or unset the current migration's cursor per database """
 +    if cr:
 +        migration_cursors[cr.dbname] = cr
 +    else:
 +        migration_cursors[threading.currentThread().dbname] = False
 +
 +
 +def get_migration_cursor():
 +    """ During migration, return a valid cursor for this thread's database,
 +    if any """
 +    cursor = migration_cursors.get(threading.currentThread().dbname)
 +    if cursor:
 +        try:
 +            cursor.execute('SELECT 1')
 +        except OperationalError:
 +            return False
 +    return cursor
 +# OpenUpgrade end
 +
- 
- @contextmanager
- def _get_cursor():
-     # yield a valid cursor from any environment or create a new one if none found
-     with registry().cursor() as cr:
-         yield cr
+ # deprecated; kept for backward compatibility only
+ _get_cursor = LazyCursor

  EMPTY_DICT = frozendict()

@@@ -404,12 -375,7 +400,12 @@@ class float(_column)
      @property
      def digits(self):
          if self._digits_compute:
 +            # OpenUpgrade: try to reuse the migration cursor, to prevent
 +            # transaction locks
 +            migration_cursor = get_migration_cursor()
 +            if migration_cursor:
 +                return self._digits_compute(migration_cursor)
-             with _get_cursor() as cr:
+             with LazyCursor() as cr:
                  return self._digits_compute(cr)
          else:
              return self._digits
@@@ -1377,12 -1352,7 +1382,12 @@@ class function(_column)
      @property
      def digits(self):
          if self._digits_compute:
 +            # OpenUpgrade: try to reuse the migration cursor, to prevent
 +            # transaction locks
 +            migration_cursor = get_migration_cursor()
 +            if migration_cursor:
 +                return self._digits_compute(migration_cursor)
-             with _get_cursor() as cr:
+             with LazyCursor() as cr:
                  return self._digits_compute(cr)
          else:
              return self._digits
```

### CODE REVIEW

**Comment by hbrunn** [comment]
So Microsoft does open source, adult people play with pokemon and Odoo SA releases migration scripts: https://travis-ci.org/OCA/OpenUpgrade/builds/146288174#L261 - seems we're going to suffer some horrible and painful death some time soon.
How are we going to handle this? I'd be inclined to simply fix what flake8 complains about

**Comment by lasley** [comment]
Brave new world! 

Maybe handle like a back port? Only thing on top of the flake fixes would be the note in ReadMe about the code not being covered under CLA.

**Comment by pedrobaeza** [comment]
Maybe we can check only OpenUpgrade files verifying the import of the library or the use of the decorator migrate.

**Comment by hbrunn** [comment]
thanks for the suggestions, just excluding the files is what I like most, then we also don't need to take care of CLA issues as we don't touch the code at all

**Comment by hbrunn** [comment]
finally green. Will one of you do the honors?

**Comment by pedrobaeza** [comment]
Of course!

**Pull request merged**
