### PR TITLE
[ADD] 14.0 - delivery - migration done

### PR DESCRIPTION
**Pull request by legalsylvain**
Quite simple migration script.

- ``length`` has been renamed into ``packaging_length``
- I added comments in the ``noupdate_changes.xml`` to say why I don't load the data.

thanks for your review.

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi. 

i don't understand why CI is failing.

At the end of the migration openupgrade try to make a delete on ``res.partner`` table...
https://github.com/OCA/OpenUpgrade/runs/6943798791?check_suite_focus=true#step:13:5198

```
ERROR: update or delete on table "res_partner" violates foreign key constraint "fleet_vehicle_assignation_log_driver_id_fkey" on table "fleet_vehicle_assignation_log"
DETAIL:  Key (id)=(31) is still referenced from table "fleet_vehicle_assignation_log".
```

In fact, in the last green build the delete are present at the end of the openupgrade log, but no error is raised... 
https://github.com/OCA/OpenUpgrade/runs/6932502486?check_suite_focus=true#step:13:5177

Thanks for your help.

**Comment by legalsylvain** [comment]
Something is wrong in the CI. Don't you think ?
https://github.com/OCA/OpenUpgrade/pull/3300 is red, but I only added a text file...

**Comment by legalsylvain** [comment]
And I rerun the test for https://github.com/OCA/OpenUpgrade/pull/3289 (that was green). And it is now red.

**Comment by pedrobaeza** [comment]
This is because Odoo has added a new restriction that makes this to fail (as Odoo part is always got dynamically, which is good, as it serves to see things that can fail in real scenarios):

https://github.com/odoo/odoo/commit/91ceb950f90d42d07970aa4a43fe9a6f3e6ff629

We have to prevent such deletion searching which data is removing, and preventing it to be removed.

**Comment by MiquelRForgeFlow** [comment]
FYI: https://github.com/OCA/OpenUpgrade/pull/2998

**Comment by pedrobaeza** [comment]
Then we can close this one, but that doesn't prevent to fix current problem in CI, which is independent from the migration of this module, and comes from an update upstream.

Miquel, can you check it?

**Comment by legalsylvain** [comment]
> FYI: https://github.com/OCA/OpenUpgrade/pull/2998

Damn'it, the related main issue was not up to date. (https://github.com/OCA/OpenUpgrade/issues/2190)

**Pull request closed without merging**
