### PR TITLE
[ADD] a bunch of modules with nothing to do

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by JordiBForgeFlow** [comment]
:+1. I updated https://github.com/OCA/OpenUpgrade/issues/400

**Comment by hbrunn** [comment]
@jbeficent thanks for updating, I usually do that when I merge some PR (and hope the others do the same...)

**Comment by JordiBForgeFlow** [comment]
Got it!

**Pull request merged**
