### PR TITLE
[12.0][FIX] mrp: don't set kit products as consumables

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Only version 12.0 forces kits as consumables. In v13, they are not forced, like they were in v11.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Have you reviewed FW-port PRs for that thing? It's probably that the patch is not yet merged, but I think the idea is that they forbid for each supported version this thing.

**Comment by pedrobaeza** [comment]
@chienandalu are you aware of the state of the fw-port?

**Comment by AaronHForgeFlow** [comment]
actually that change was reverted in v12: https://github.com/odoo/odoo/commit/6c4623a46cbe35c18017c59335b3a3c563ae5fbf

Perhaps we should not convert products even if target version is 12.0

**Comment by pedrobaeza** [comment]
Yes, then I think it should be reverted this patch as well. cc @StefanRijnhart

**Comment by MiquelRForgeFlow** [comment]
Revert done.

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by MiquelRForgeFlow** [comment]
Here I did the update upstream to include the odoo revert: https://github.com/OCA/OpenUpgrade/pull/2655

**Comment by chienandalu** [comment]
> actually that change was reverted in v12: [odoo/odoo@6c4623a](https://github.com/odoo/odoo/commit/6c4623a46cbe35c18017c59335b3a3c563ae5fbf)
> 
> Perhaps we should not convert products even if target version is 12.0

The funny thing is that it was a dirty trick to patch another problem that it was fixed in other way in later versions :upside_down_face:

**Pull request merged**
