### PR TITLE
Fix incorrect table reference for account_bank_statement_cashbox

### PR DESCRIPTION
**Pull request by ToBeReplaced**
See #543

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1:

**Comment by hbrunn** [comment]
@ToBeReplaced are you planning to sign the CLA? If not, then I'll duplicate your PR with my credentials because the rule is that all code must be covered by the CLA. Thanks for following up!

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by ToBeReplaced** [comment]
Just a followup; I sent the CLA more-or-less immediately after hbrunn's comment. Maybe check the cla email?

**Comment by pedrobaeza** [comment]
CLA checked, so merging.

**Pull request merged**
