### PR TITLE
[17.0][OU-ADD] resource: migrate to 17.0

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Comment by legalsylvain** [comment]
@duong77476-viindoo : could you rebase this PR ?
Thanks !

**Comment by daiduongnguyen-odoo** [comment]
@legalsylvain Sure, done

**Comment by hbrunn** [comment]
/ocabot merge nobump

thanks!

**Comment by pedrobaeza** [comment]
@hbrunn I have put a fix in #4655

**Pull request merged**
