### PR TITLE
14.0 fix calendar migration

### PR DESCRIPTION
**Pull request by SilvioGregorini**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Could you avoid in your second commit do too much visual diff?

**Comment by SilvioGregorini** [comment]
> Could you avoid in your second commit do too much visual diff?

I made it that way so that it could be easier to recognize the column-value association, but if little diffs are preferred, I will change it as soon as I get back from lunch :smile:

**Comment by SilvioGregorini** [comment]
@MiquelRForgeFlow done!

**Comment by pedrobaeza** [comment]
Definitively something is wrong with the CI for not failing on previous SQLs.

**Comment by MiquelRForgeFlow** [comment]
I see. Because doc file is not filled. Some modules like `calendar` and `product` are not marked in doc.

**Comment by pedrobaeza** [comment]
Ouch!

**Comment by MiquelRForgeFlow** [comment]
Now `calendar` it's being tested.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Thanks for your fixes.

**Pull request merged**
