### PR TITLE
[17.0][OU-ADD] auth_signup: migration to 17.0

### PR DESCRIPTION
**Pull request by flachica**
oauth_signup.reset_password_email is not migrated automatically because odoo detect model change. This external id in 16.0 is marked as noupdate. In 17.0 is detected as view

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration auth_signup

<dependency></dependency>

**Comment by legalsylvain** [comment]
@flachica : could you rebase ?

**Review by hbrunn — CHANGES_REQUESTED** [review]
please copy `upgrade_analysis.txt` to `upgrade_analysis_work.txt` and document what you did here

**Comment by hbrunn** [comment]
> please copy `upgrade_analysis.txt` to `upgrade_analysis_work.txt` and document what you did here

I took the liberty to do this myself so that we can merge this one fast

**Review by hbrunn — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
