### PR TITLE
[IMP] web_diagram removed from Odoo 14.0

### PR DESCRIPTION
**Pull request by etobella**
Web_diagram was removed on https://github.com/odoo/odoo/pull/36638

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It was already handled in #3232

**Comment by etobella** [comment]
Not properly handled IMO... If it was installed but no longer used it will not be merged

**Comment by pedrobaeza** [comment]
It's the contrary...

**Comment by etobella** [comment]
Ouch!! Thanks, I didn't see the not... My fault. Sorry :cry:

**Pull request closed without merging**
