### PR TITLE
[16.0][OU-ADD] sale_stock: migration

### PR DESCRIPTION
**Pull request by hoangtiendung070797**
migration

### CODE REVIEW

**Comment by legalsylvain** [comment]
@hoangtiendung070797 could you take a look at the other PR ?

**Comment by hoangtiendung070797** [comment]
> @hoangtiendung070797 could you take a look at the other PR ?

@legalsylvain Yes, ok

**Comment by hoangtiendung070797** [comment]
Dulicates https://github.com/OCA/OpenUpgrade/pull/4015

**Pull request closed without merging**
