### PR TITLE
[12.0][MIG] Avoid 'account.move.line.reconcile' error

### PR DESCRIPTION
**Pull request by OthmaneGhandi**
Current behavior before PR:
You got an error when trying to open Journal Items, related to "'account.move.line.reconcile'" action view
=> The action view should be deleted et the end of the migration 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedroslopez — COMMENTED** [review]
Could we use openupgradelib's `delete_records_safely_by_xml_id` here?

**Comment by OthmaneGhandi** [comment]
> `delete_records_safely_by_xml_id`

In this case we should include it in pre-imgration file, because after reloading the modules we lose the xml id of the record. I will try it too

**Comment by pedrobaeza** [comment]
Thanks for discovering the problem, but the patch is not correct, as removing once the XML-ID has been changed deletes the incorrect record. I have pushed the proper fixed in 0452773.

**Comment by OthmaneGhandi** [comment]
Thanks @pedrobaeza

**Pull request closed without merging**
