### PR TITLE
8.0 ignore implicit columns

### PR DESCRIPTION
**Pull request by StefanRijnhart**
- Ignore dedicated test addons, as they can rely on demo data
- Ignore implicit columns (create_uid etc.) which are now added automatically as fields
- Manually remove references to implicit columns from analysis files

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by arthru** [comment]
:+1:

**Comment by legalsylvain** [comment]
Hi @StefanRijnhart. Thanks!

Just a little minor question: 
to know if a module is a "test" module you base your analysis on 'category' field of model ir.module.module.
But when I "grep 'category'.*Tests" in Odoo I find 8 modules: 
./openerp/addons/test_converter/
./openerp/addons/test_exceptions/
./openerp/addons/test_impex/
./openerp/addons/test_inherit/
./openerp/addons/test_limits/
./openerp/addons/test_new_api/
./openerp/addons/test_uninstall/
./openerp/addons/test_workflow/

And when I look for module named 'test_xx' I find 10 modules:
**./openerp/addons/test_access_rights**
**./openerp/addons/test_convert**
./openerp/addons/test_converter
./openerp/addons/test_exceptions
./openerp/addons/test_impex
./openerp/addons/test_inherit
./openerp/addons/test_limits
./openerp/addons/test_new_api
./openerp/addons/test_uninstall
./openerp/addons/test_workflow
- Seems that looking by name give a result more complet;
  Do you know if 'category': 'Tests' is a real convention ?

Thanks.

Otherwise :+1:

**Comment by StefanRijnhart** [comment]
@legalsylvain thanks for the review! I think it is a convention, just not applied too rigorously. For our purposes, it does not matter. I just needed to exclude test_new_api as it broke the analysis process, as it depends on demo data that is not installed.

**Pull request merged**
