### PR TITLE
[16.0][OU-ADD] base_iban: Nothing to do

### PR DESCRIPTION
**Pull request by remytms**
There is no analysis file generated and there is no DB changes. So nothing to do.

But it depends on `account` which as no migration script yet.

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration base_iban

<dependency>Depends on : 

- account : #4070</dependency>

**Comment by pedrobaeza** [comment]
Please change tag to  `[OU-ADD]`.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
