### PR TITLE
[13.0][FIX] stock: putaway rules in multi-company

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Oversight.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't this a previous bad information in such rules?

**Comment by MiquelRForgeFlow** [comment]
In previous versions, such rules didn't have a company_id field. Thus, we need to fill it correctly.

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Wait a moment: I'm not finding such model in v12 core.

**Comment by MiquelRForgeFlow** [comment]
Obviously, it's renamed in pre from `stock.fixed.putaway.strat`.

**Review by mariadforgeflow — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]

**Pull request merged**
