### PR TITLE
[FIX] don't write implied groups on all users

### PR DESCRIPTION
**Pull request by hbrunn**
see https://github.com/OCA/OpenUpgrade/pull/1460

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thanks. Travis failed on problems resetting to TRAVIS_COMMIT. Restarting build.

**Comment by pedrobaeza** [comment]
I was waiting to see if Odoo merges this for later updating upstream, but no answer for now.

**Comment by StefanRijnhart** [comment]
Restarting build did not fix anything. Last time I had this problem nothing worked except a recommit with a different hash.

**Comment by pedrobaeza** [comment]
It has been merged on 10.0, and will be forward-ported soon. Should we continue with this PR, or make a merge from upstream?

**Comment by StefanRijnhart** [comment]
Let me try and reproduce my recommit experience here: https://github.com/OCA/OpenUpgrade/pull/1462

**Comment by StefanRijnhart** [comment]
#1462 is green. You can either merge that one or wait for @hbrunn to force a different commit hash (or wait until it is merged into Odoo and then merge that).

**Comment by hbrunn** [comment]
I'm on vacation currently and promised myself to only use my office ssh key when something is burning. So thanks for taking over, I think we can just wait until upstream has this and then refresh the whole branch. Closing this then.

**Pull request closed without merging**
