### PR TITLE
[CI] explicit CI lines

### PR DESCRIPTION
**Pull request by legalsylvain**
Log more info in the CI to understand https://github.com/OCA/OpenUpgrade/pull/3273 problem.

### CODE REVIEW

**Comment by legalsylvain** [comment]
That's seems OK @pedrobaeza. don't you think ?

https://github.com/OCA/OpenUpgrade/runs/7211788568?check_suite_focus=true#step:13:56

**Comment by pedrobaeza** [comment]
Yes, they are. The problem has been in certain CIs, like the `mail` one, but once I restarted the build, it was OK, so it's not clear what has happened.

**Comment by legalsylvain** [comment]
OK. Could we merge this one ?

**Comment by pedrobaeza** [comment]
Yes, it doesn't hurt and clarifies a bit for future issues.

**Comment by legalsylvain** [comment]
Thanks.

**Pull request merged**
