### PR TITLE
[13.0][FIX] utm: pre-migration 

### PR DESCRIPTION
**Pull request by astirpe**
This fixes an error I get when I try to re-run the migration scripts after something has gone wrong.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is not correct. If you are re-running something, it should be rolled-back. If not, then you should start from beginning again.

**Comment by astirpe** [comment]
Ok but it saved a lot of time to me, especially in this early stage. Feel free to close this PR

**Comment by pedrobaeza** [comment]
The only reading here is if the commit after migrating each module is working properly. @StefanRijnhart can it be incorrect, committing changes in migration scripts but not committing module installed version?

**Comment by MiquelRForgeFlow** [comment]
This is wrong. @astirpe the problem you may have is that after a failed migration, the following migration is trying to migrate an already migrated module.

**Comment by astirpe** [comment]
The error I got was because the script failed somewhere and the `rename_models` rolled-back but the `rename_tables` did not. Re-executing the script, the `rename_models` was not executed anymore because not any table with `mail_mass_mailing_stage` name was found: this caused an error.

According to you all, the only way to go on is to restart all over again since the rollback didn't work properly.
For me this PR worked fine and I saved some good time.

I realize you don't see any advantage in this change, so I close the PR and save extra time.

**Comment by pedrobaeza** [comment]
@astirpe that's the weird thing: everything should be rolled-back. The commit level should be per module, and if everything is in the same module, everything should be rolled-back.

**Pull request closed without merging**
