### PR TITLE
[ADD] travis

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Same as 8.0

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi, 
Is there any reason to set a max-length to 120 ? I know that OpenUpgrade is not an official OCA project but OCA rule is Max 80 ?

**Comment by pedrobaeza** [comment]
Yeah, I would prefer 80

**Comment by StefanRijnhart** [comment]
Me too! I'm currently fixing the warnings and I adhere to 80 intuitively.

**Comment by legalsylvain** [comment]
You can maybe set directly to 80, as Travis is failing now...

**Comment by legalsylvain** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
It's green!

**Comment by bwrsandman** [comment]
Nicely done!
:+1: 

Any plans for testing migrations?

**Comment by pedrobaeza** [comment]
Thanks for the huge work. :+1: 

@bwrsandman, difficult task to test that a migration script is correctly done...

**Comment by legalsylvain** [comment]
@pedrobaeza we are talking about that here : #113 .

**Pull request merged**
