### PR TITLE
[11.0] Update to upstream code

### PR DESCRIPTION
**Pull request by pedrobaeza**
There have been little conflicts in 4 files that have been annotated in merge commit comment, but nothing important.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't understand why stock is being installed...

**Comment by StefanRijnhart** [comment]
Stock is installed because it is a dependency of product_expiry. I created https://github.com/OCA/OpenUpgrade/pull/1300

**Comment by StefanRijnhart** [comment]
Which commit did you merge? I always recreate the merge to check the differences.

**Comment by pedrobaeza** [comment]
The commit is d1a9672182791484279d3d4a3aae20688be08585, but I think all is messed up :(

How do you do it? I did:
```
git pull
<solve conflicts>
git commit
```

**Comment by StefanRijnhart** [comment]
That is the openupgrade commit. For better verifiability, it is better to check the latest commit on odoo/odoo. It is currently b5c660d.

git fetch odoo 11.0
git merge b5c660d
\# resolve conflicts, git add ...;
git commit

And then mention that commit in the commit messsage if possible or in the PR. I can then do the same, and do a git diff on your PR branch.

**Comment by pedrobaeza** [comment]
OK, thanks for explaining that. I'll retry then and do it that way.

**Comment by pedrobaeza** [comment]
@StefanRijnhart I have made the way you have indicated, but it seems the merge commit it's still together with the rest of the changes.

**Comment by StefanRijnhart** [comment]
Yes, but now that I know the commit hash I can start the validation of this PR.

**Comment by StefanRijnhart** [comment]
Looks good! Two remarks:
* in odoo/modules/migration.py, you can actually remove the mergedict method as it is no longer used in OpenUpgrade 11.0
* in requirements.txt, psycogreen is an old dependency of Odoo, not OpenUpgrade so it can be removed as well.

**Comment by pedrobaeza** [comment]
> in odoo/modules/migration.py, you can actually remove the mergedict method as it is no longer used in OpenUpgrade 11.0

AFAIK, I removed it because I got to the same conclusion

> in requirements.txt, psycogreen is an old dependency of Odoo, not OpenUpgrade so it can be removed as well.

Removed!

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by StefanRijnhart** [comment]
There's a bit of a queue in the OCA Travis. Can't the OCA get a discount on more simultaneous jobs? I might consider to sponsor.

**Comment by pedrobaeza** [comment]
Well, the price is not very encouraging:

https://travis-ci.com/plans

**Comment by pedrobaeza** [comment]
CI completed and green.

**Pull request merged**
