### PR TITLE
[IMP] don't autoinstall nonexisting modules

### PR DESCRIPTION
**Pull request by hbrunn**
backport of #651

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by susport — COMMENTED** [review]
👍

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by hbrunn** [comment]
they are not caused by this pr, I'd rather fix them in another one

**Comment by pedrobaeza** [comment]
OK, merging then

**Comment by pedrobaeza** [comment]
I have cherry-picked 9.0 commits to solve Pylint issues. Let's see if there's anything more.

**Pull request merged**
