### PR TITLE
[16.0][OU-ADD] mrp_account: Nothing to do

### PR DESCRIPTION
**Pull request by victoralmau**
Nothing to do

Depends on:
- [ ] https://github.com/OCA/OpenUpgrade/pull/4117
- [x] https://github.com/OCA/OpenUpgrade/pull/4070

@Tecnativa TT43623

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration mrp_account

<dependency></dependency>

**Comment by legalsylvain** [comment]
Could you rebase ?

**Comment by pedrobaeza** [comment]
@legalsylvain the problem is to merge several PRs at the same time, as they commit new changes to the branches (like documentation) and conflict.

/ocabot merge nobump

**Pull request merged**
