### PR TITLE
[15.0][OU-FIX] web: Set the correct report_footer value

### PR DESCRIPTION
**Pull request by victoralmau**
Set the correct report_footer value

Related to https://github.com/OCA/OpenUpgrade/pull/4095

@Tecnativa TT52003

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
This is missing the decorations to be exactly as it was (`<ul>`, `<li>`, icons, etc).

**Comment by pedrobaeza** [comment]
Have you checked that these classes are correctly exported to PDF?

**Comment by victoralmau** [comment]
Yes, it is checked.

**Configure document layout wizard**
ejemplo-1

**Pdf footer**
ejemplo-2

Still, I think an **extra validation** of this change would be nice (for example in a migration).

**Comment by pedrobaeza** [comment]
Great, let's test it in the migration we are going to perform, cc @chienandalu 

I'm merging now and possible amendments will be done through subsequent PRs.

**Pull request merged**
