### PR TITLE
[14.0][FIX] hr: wrong call of delete_records_safely_by_xml_id

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fast-tracking.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why tests weren't acting?

**Comment by MiquelRForgeFlow** [comment]
Because the delete_records have a try exception. But with https://github.com/OCA/openupgradelib/commit/4c9ecada0dedc0b34ef58c67a1ac37bb89c27d9c, which was added later than this PRs, it made able to detect it.

**Comment by pedrobaeza** [comment]
Maybe we should restrict the `except` part on the openupgradelib?

**Comment by MiquelRForgeFlow** [comment]
Yes, it would be good to restrict by KeyError

**Comment by pedrobaeza** [comment]
In fact I was thinking on the exception when DB constraint is raised (not sure which want it is).

**Comment by MiquelRForgeFlow** [comment]
Then KeyError,ValidationError,IntegrityError, right?

**Comment by pedrobaeza** [comment]
Yeah, I think so

**Comment by MiquelRForgeFlow** [comment]
Restriction done in https://github.com/OCA/openupgradelib/pull/266

**Pull request merged**
