### PR TITLE
[16.0][OU-ADD] portal

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Review by legalsylvain — COMMENTED** [review]
Hi @marielejeune. Thanks for your contribution. 

I see that there is a noupdate_changes.xml file for that module, with a mail template. I guess that we should write a post-migration script to refresh the data. don't you think ? 

See according new documentation : https://oca.github.io/OpenUpgrade/use_cases/noupdate_xml_entry_changed.html#write-migration-script

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @marielejeune. Thanks for your contribution. 

I see that there is a noupdate_changes.xml file for that module, with a mail template. I guess that we should write a post-migration script to refresh the data. don't you think ? 

See according new documentation : https://oca.github.io/OpenUpgrade/use_cases/noupdate_xml_entry_changed.html#write-migration-script

**Comment by marielejeune** [comment]
> I see that there is a noupdate_changes.xml file for that module, with a mail template. I guess that we should write a post-migration script to refresh the data. don't you think ?

Right, done

**Review by legalsylvain — APPROVED** [review]
/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@legalsylvain this one is still missing to delete the record translations.

**Comment by legalsylvain** [comment]
> @legalsylvain this one is still missing to delete the record translations.

Hum. That's annoying. I'd like to integrate the deletion of the translation in load_data, if version >= 16.0 this should avoid that noicy second line, that is mandatory in most case. What do you think ?

**Comment by pedrobaeza** [comment]
I'm afraid that's not so easy to be done and will require to patch Odoo itself, but if got, it would be great of course. But meanwhile, we need to complete the scripts with current system.

**Comment by legalsylvain** [comment]
> I'm afraid that's not so easy to be done and will require to patch Odoo itself, but if got, it would be great of course. 

Yes, I thought to this point, and it doesn't seems easy indeed.

> But meanwhile, we need to complete the scripts with current system.

@marielejeune could you provide a PR ?

**Comment by marielejeune** [comment]
@legalsylvain Done here: https://github.com/OCA/OpenUpgrade/pull/4028

**Pull request merged**
