### PR TITLE
Use openupgrade lib and warn old use

### PR DESCRIPTION
**Pull request by bwrsandman**
6.1 version of #341

Reopen of #317 on my own branch

We ported the openupgrade scripts to pypi

[pypi Package](https://pypi.python.org/pypi/openupgradelib)

The recommendation for using those scripts is now: `from openupgradelib import openupgrade`

This patch should properly raise a warning be reverse compatible as long as openupgradelib is intalled in the python path.

The reasoning behind moving this bit of code to a lib is for module migrations within the same Odoo version but with changes in a module such as a field rename.

Prior to this, the recommended way was to copy code into migrations if not use OpenUpgrade. This makes the code reusable and gets rid of code duplication.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
For this version, there's this error:

```
    from openerp.tools.mail import plaintext2html
ImportError: No module named mail
```

Because this module is available from 7.0. We should protect this import with a `try: ... except ImportError:`

**Comment by pedrobaeza** [comment]
:+1: when https://github.com/OCA/openupgradelib/pull/11 will be merged.

**Comment by pedrobaeza** [comment]
Finishing migration, I found one last problem that has been fixed on https://github.com/bwrsandman/OpenUpgrade/pull/2. @bwrsandman, please merge, or if you really want to quit from all these duties, please tell me and I will superseed it with a new PR.

**Comment by bwrsandman** [comment]
@pedrobaeza merged

**Comment by pedrobaeza** [comment]
:+1: Thanks

**Comment by pedrobaeza** [comment]
I also tried this one with the patched openupgradelib, so this one is ready to merge.

**Comment by StefanRijnhart** [comment]
Thanks @pedrobaeza for testing!

**Pull request merged**
