### PR TITLE
[12.0][FIX] website_livechat: convert bootstrap

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Ups!

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Are you sure that field is editable through website editor?

**Comment by MiquelRForgeFlow** [comment]
Nop, I am not sure. How can I see that?

**Comment by pedrobaeza** [comment]
First check if the field is html. Then, look if the field is added in a QWeb template with editing purposes.

**Comment by MiquelRForgeFlow** [comment]
Yes, it is `html`. In the template, it appears as `<div t-field="channel.website_description" class="oe_structure mt16" />`. Is it ok? 🤔

**Comment by pedrobaeza** [comment]
Yes, it's a `t-field`, so the possibility exists.

/ocabot merge

**Pull request merged**
