### PR TITLE
Add sponsors to README

### PR DESCRIPTION
**Pull request by simahawk**
The board got 1k from Odoo Italia community after we launched the funding campaign.

We'd like to give all sponsors a bit of recognition.

As many people/companies already put a lot of effort here, maybe we should add more items to the list (suggestions?).

Maybe there's a better place or an additional place where we want to put this (suggestions?).

@OCA/openupgrade-maintainers can you provide your feedback?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Instead of here, I would put them at the same level than OCA general sponsors.

**Comment by simahawk** [comment]
@pedrobaeza thanks for you feedback.
Regarding sponsorship presence on the website: we'll do that (should be there already indeed).
At the same time it would be nice to see some attribution on specific projects.
Maybe we can handle this in the future at website level w/ a relation to supported projects/modules but for now this seems a cheap option. No?

**Comment by pedrobaeza** [comment]
But that way visibility is going to be asymmetric: one general sponsor only appears on website and OU sponsor in 2 places? I think all should be handled in the website, not splitting this around GitHub.

**Comment by simahawk** [comment]
I see your point and somehow you are right. The board will establish some rules to handle such cases better. Discussion ongoing.
For now I keep this on hold.

**Pull request closed without merging**
