### PR TITLE
[13.0][WIP] Testing GitHub actions

### PR DESCRIPTION
**Pull request by pedrobaeza**
To see if it works properly.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
The error is not detected

**Comment by pedrobaeza** [comment]
Yeah, @etobella is going to check it

**Comment by MiquelRForgeFlow** [comment]
will you close it or do rebase to test it?

**Comment by pedrobaeza** [comment]
I'm doing more tests in this PR for checking the rest of the actions.

**Comment by pedrobaeza** [comment]
Everything working properly, so I close.

**Pull request closed without merging**
