### PR TITLE
[ADD] Migration of the procurement references on the sale order line

### PR DESCRIPTION
**Pull request by StefanRijnhart**
I'm taking on sale, but it contains a change that needs migration in sale_stock. Requesting a pull of this atomic change to prevent conflicts when someone wants to work on sale_stock.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Additionally, this change contains a renaming of the m2o_to_m2m API method to m2o_to_x2m because it works just as well in the case of migration to a one2many. Keeping the old function name as a reference for backwards compatibility.

**Comment by legalsylvain** [comment]
:+1: LGTM.
Maybe you could mark some "TODO" notes in "openupgrade_analysis_work.txt" or a "work in progress" in the file "migration_70-80.rst" to prevent people believe that 'sale_stock' is done.

Regards.

**Comment by paulius-sladkevicius** [comment]
:+1: 
I don't think it's worth to pull in progress to "migration_70-80.rst", it will confuse that somebody is working on it.

**Comment by bwrsandman** [comment]
@StefanRijnhart Can we get an answer to this?
Do we need a work in progress note?

**Comment by StefanRijnhart** [comment]
It should be clear from the 'work' file that only one aspect has been handled, right?

**Comment by bwrsandman** [comment]
Quickly looking at it, I can say that it's not immediately clear.

**Comment by StefanRijnhart** [comment]
OK, WIP as requested

**Comment by legalsylvain** [comment]
@komsas No because if there is no people in the wiki page that means that nobody is working on that.
(https://github.com/OpenUpgrade/OpenUpgrade/wiki/Pending-Work)
Don't you think it is sufficient ?

**Comment by StefanRijnhart** [comment]
I consider this change a part of the sale module really so I don't think we should mark the module coverage. But I will mark the work file.

**Comment by StefanRijnhart** [comment]
Resubmit

**Comment by pedrobaeza** [comment]
:+1:  LGTM

**Pull request merged**
