### PR TITLE
[11.0][MIG] product_expiry & stock_picking_wave

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
The `stock` module is already migrated.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
How I fix this? @pedrobaeza @StefanRijnhart 

selection_027

**Comment by pedrobaeza** [comment]
Next time please only one module per PR.

**Comment by pedrobaeza** [comment]
Why do you need to merge instead of renaming?

**Comment by MiquelRForgeFlow** [comment]
Because with renaming I got the error I showed you above. Also, in the migration issue https://github.com/OCA/OpenUpgrade/issues/1005 it is put as a merging.

**Comment by pedrobaeza** [comment]
Uhm, that's very weird. I think that maybe `update_module_names` method doesn't perform operations in the proper order. @StefanRijnhart do you have any clue about this?

**Comment by StefanRijnhart** [comment]
The error implies that model/table stock.picking.wave is not properly renamed to stock.picking.batch. Can you point out to me where that is supposed to happen?

**Comment by MiquelRForgeFlow** [comment]
Well, finally, what should we do with this PR?

**Comment by StefanRijnhart** [comment]
Don't merge, but rename and properly migrate stock.picking.wave to stock.picking.batch in the module's migration script.

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart Yes, done! (I don't know why but before I didn't see analysis file, thus why I asked that)

Ready to review and merge! :green_apple:

**Review by StefanRijnhart — APPROVED** [review]
Great, thanks!

**Comment by pedrobaeza** [comment]
I don't see the name renaming in this PR. Have you removed it?

**Comment by MiquelRForgeFlow** [comment]
The rename was already in the aprori file.

**Comment by pedrobaeza** [comment]
OK then

**Pull request merged**
