### PR TITLE
[MIG][15.0] website_sale: migration script

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
### **This PR**
Migration done

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @duong77476. Thanks for sharing this migration script.
A question : you proposed ``website_sale`` module but I don't see the migration PR for the ``sale`` module. Could you do it if you did it ? 

kind regards.

**Comment by daiduongnguyen-odoo** [comment]
Hi @legalsylvain The migration PR for sale module will have soon, maybe in next 24 hours. I and my team are going to have full migration PR for the modules of Odoo CE, i hope you could save sometime to review them for us.

kind regrards.

**Comment by pedrobaeza** [comment]
Superseded by #3693

**Pull request closed without merging**
