### PR TITLE
[14.0][OU-IMP] *: remove obsolete SQL views

### PR DESCRIPTION
**Pull request by remi-filament**
As per #4313 this PR removes obsolete views from concerned modules

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks !

**Review by rvalyi — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Wait a moment: why the `CASCADE` thing? It can have side effects

**Comment by remi-filament** [comment]
I just kept the Odoo default behaviour : https://github.com/odoo/odoo/blob/b7777c50d40cc56e094f43d8f35753d713e17f77/odoo/tools/sql.py#L244

I could remove the cascade although I do not see how it would get side effect except if extra module would be making external link to a view ?

**Review by pedrobaeza — APPROVED** [review]
OK then. I was fearing that the FK constraints provokes legit data tables to be removed as well, but I suppose is only on the other way.

**Pull request merged**
