### PR TITLE
[FIX] website: delete group assignments for views

### PR DESCRIPTION
**Pull request by hbrunn**
let's wait for the test results this time

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Better to wait, yes, but tentatively OK

**Comment by pedrobaeza** [comment]
Now the error is on stock module (which has been merged meanwhile), and we also have an error on the documentation build. We can merge this and continue fixing the rest.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza @hbrunn The problem with stock is that a function is being called to re-confirm an a demo inventory adjustment that was already created an completed in Odoo 9: https://github.com/OCA/OpenUpgrade/blob/10.0/addons/stock/data/stock_demo.xml#L133

I am not sure why a function defined under a noupdate=1 data tag would be triggered again. I would assume that updating the stock module in a demo database in normal circumstances would trigger this error as well.

**Comment by pedrobaeza** [comment]
@jbeficent this branch doesn't contain the stock migration, so the error will be gone for sure when merged.

**Comment by hbrunn** [comment]
so let's merge :-)

**Comment by pedrobaeza** [comment]
@hbrunn please check the documentation build part while I check account one

**Pull request merged**
