### PR TITLE
[ADD] rename letter_mgmt_v6

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
The rename was not effective as 7.0 still keeps the list of renamed modules at two places. I backported the change we made in 8.0 to fix that and merged the two lists. You might want to review again

**Comment by pedrobaeza** [comment]
Thanks, I thought it was already backported.

:+1:

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Pull request merged**
