### PR TITLE
[OU-ADD] l10n_fr

### PR DESCRIPTION
**Pull request by legalsylvain**
/ocabot migration l10n_fr

### CODE REVIEW

**Comment by rvalyi** [comment]
worth mentioning the l10n_fr_oca fork in v16 somewhere in the logs?

**Comment by legalsylvain** [comment]
@rvalyi. Not the role of openupgrade IMO to promote new OCA alternative.
Also the logs are read to know if migration is OK, not to discover things.

Could akretion write some blogpost in the oca website ?

**Review by remytms — APPROVED** [review]

**Pull request merged**
