### PR TITLE
[FIX] calendar: Handle recurring events

### PR DESCRIPTION
**Pull request by pedrobaeza**
Solves #1412 

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This tries to showcase for now the problem. If it arises, then I will add the migration code for avoiding it.

**Comment by pedrobaeza** [comment]
And here we have it!

https://travis-ci.org/OCA/OpenUpgrade/builds/401748434#L2494

Let's go for the solution.

**Comment by pedrobaeza** [comment]
And pre-creating the column everything's back to normal.

@davidtranhp @jonerikceberio you can review this.

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Waiting for feedback from @davidtranhp @jonerikceberio

**Comment by jonerikceberio** [comment]
Good on my side, although I still do not understand why it wasn't able to 'translate' the fake ids to real ids to write on DB.

**Comment by davidtranhp** [comment]
I confirm that this PR solves the issue

**Comment by StefanRijnhart** [comment]
Thanks for the feedback!

**Pull request merged**
