### PR TITLE
[8.0] Fix migration script of module account

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1:, verified it's now like this in 7.0: https://github.com/OCA/OCB/blob/7.0/addons/account/account_bank_statement.py#L567 but at the time of writing this script, it was probably this: https://github.com/OCA/OCB/commit/59e5b3e475e4037c480b83059e5bfd6ad29c5dff

**Comment by pedrobaeza** [comment]
Isn't this a stable version where no DB layout change is made?!!

Thanks for the patch. :+1:

**Comment by ghost** [comment]
@pedrobaeza I ported account and stock successfully, except for this small error, so I guess the branch is stable.

**Comment by pedrobaeza** [comment]
I mean about stability in Odoo. Changing a field name in the middle of the version 8.0 doesn't mean that.

**Comment by hbrunn** [comment]
@pedrobaeza mind you this is a change in 7.0, which was introduced quite early in its lifetime

**Comment by pedrobaeza** [comment]
Ah, OK, I mixed the information. I proceed with the merge.

**Comment by pedrobaeza** [comment]
Eh, wait... if now it's `statement_line_id`, why are we changing it to `statement_id`? I think I wouldn't merged the PR. The problem is an outdated 7.0. Am I wrong?

**Comment by hbrunn** [comment]
you made me think, that hurts. But yes, I think you're right. Outdated v7, we need to revert this commit.

**Comment by pedrobaeza** [comment]
Reverted. @dufresnedavid, please check what we commented.

**Comment by ghost** [comment]
@pedrobaeza I don't understand your point. In both Odoo 7.0 and Odoo 8.0. The field is statement_id. There is no such thing as statement_line_id in any version of Odoo anymore. So why are we changing this ?

Also, this is the post-migration script, so why are we talking about v7 ?

**Comment by pedrobaeza** [comment]
No, in 7.0 is the other column name: https://github.com/OCA/OCB/blob/7.0/addons/account/account_bank_statement.py#L567

**Comment by ghost** [comment]
@pedrobaeza ok, I get it. Thanks!

**Pull request merged**
