### PR TITLE
[IMP] account: Synchronize partner_id on account invoice lines

### PR DESCRIPTION
**Pull request by pedrobaeza**
I have ended up in several migrations with the same foreign key error in the account invoice line, so this little method avoid the issue. Anyways, in the best case, this SQL runs with no modifications.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Harmless indeed, so :+1:. Any idea what caused this inconsistency?

**Comment by pedrobaeza** [comment]
I think it's a bug of the old ORM dealing with related fields, but I didn't investigate further.

**Comment by StefanRijnhart** [comment]
I think it's this bug: https://github.com/odoo/odoo/pull/6774. Stored related fields without recompute triggers are never recomputed. This is bigger than just this particular case. Maybe something for the database_cleanup module. Can you add this as a comment to the method?

**Comment by pedrobaeza** [comment]
Uhm, not sure that it's that one, because that happens on v8 with new API, not in 6.1/6.0.

**Comment by StefanRijnhart** [comment]
It was noted on the thread that this was already the case in older versions.

**Comment by pedrobaeza** [comment]
Ahm, OK, I didn't see it. I'll document then the method. Anyways, I have only seen problems with this object, not another ones.

**Comment by pedrobaeza** [comment]
Added the comment on the method. _database_cleanup_ can include this method, but you will face the problem before you can get the occasion to run it.

**Comment by pedrobaeza** [comment]
Can you merge this if there's no opposition?

**Comment by StefanRijnhart** [comment]
Do we need to be more strict about this now that this is an OCA project?

**Comment by pedrobaeza** [comment]
Well, I don't think so. I have only faced this in this concrete case and a possible generic method can be time consuming in developing and execution.

**Comment by StefanRijnhart** [comment]
No, I mean: merging without the minimum of two approvals

**Comment by pedrobaeza** [comment]
Ah, OK, well, this is not a mass people repo, so maybe we can set a maximum delay to act, but please tell your opinion.

**Comment by pedrobaeza** [comment]
Can anyone check this?

**Comment by paulius-sladkevicius** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Thanks

**Comment by StefanRijnhart** [comment]
And another OCA rule is not to merge your own work, of course (next time).

**Comment by pedrobaeza** [comment]
@StefanRijnhart, I don't know why are you now so sensible now with these rules, but if you are so upset, I can stop and let these PRs die in the time. I don't have any problem.

**Comment by StefanRijnhart** [comment]
Less well reviewed changes can be harmful. _You_ should be setting an example as a board member. And if there is a problem with not enough reviewers, than we should fix _or_ change the rules to adapt to that situation instead.

**Comment by StefanRijnhart** [comment]
BTW I have always been strict with rules on OCA projects. It is just that on OpenUpgrade we did not have to abide by the OCA rules because it was not an OCA project.

**Comment by pedrobaeza** [comment]
This PR is all except harmful. I'm giving my example, working in all branches, all repos, all reviews, so please don't tell me how to be a board member, OK? I'm strict enough. I'm not merging something that it's not tested. Everyone can make mistakes. I've made mistakes, you've made mistakes, and it's at one commit of distance to be amended. Just that.

**Comment by StefanRijnhart** [comment]
That basically means that I cannot ask anyone else anymore not to merge their own changes because the board members do it too.

**Comment by StefanRijnhart** [comment]
BTW if you think I am being too rigid with the rules, that is a personal trait I must admit so we don't have to decide on this issue here between the two of us ;-)

**Comment by pedrobaeza** [comment]
BTW, I'm not asking that rule to anyone because I have never understood it and I find it absurd. It had any sense in the Launchpad times because it requires some manual operations and it can be screwed by a non-experienced person, but now that we only need to push a button...

We already have 2 approvals (that I have been waiting patiently for), the code is well tested by my part, so I have merged. What is the problem?

I have asked in other occasion to remove that rule and you silently ignored me...

**Comment by StefanRijnhart** [comment]
Sorry, I had not understood that you asked me about that rule before if you did. So maybe it is good to discuss it in a larger context?

**Comment by pedrobaeza** [comment]
Yeah, of course we can discuss the convenience of the rule. I'm writing to the contributors list.

**Comment by pedrobaeza** [comment]
And apologize me if I sounded rude, but I'm a bit frustrated of my PRs not being treated, specially in this branch. And as I want to avoid this sensation to other collaborators, that's why I sometimes "bend" the rules. You know that there are other ways to bend these rules, like asking collaborators to blindly put a thumb up or similar, and I prefer to avoid that: if I merge something, it's up to me. Doesn't make that more sense?

**Comment by StefanRijnhart** [comment]
Yes, I understand it is hard, especially on the less populated projects such as this one. I'll try and do some promotion of the project after the holiday season.

**Pull request merged**
