### PR TITLE
[ADD] Rename l10n_nl_intrastat

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I suppose it's correct, but I don't know this localization module. I think @hbrunn's quick confirmation serves for giving a go.

**Comment by StefanRijnhart** [comment]
Here's a reference: https://github.com/OCA/l10n-netherlands/issues/118#issuecomment-396529112

**Comment by pedrobaeza** [comment]
OK, then I assume extra migration scripts will be needed, but on the target module.

**Review by pedrobaeza — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Added a flake8 fix

**Comment by pedrobaeza** [comment]
Can you squash both?

**Comment by StefanRijnhart** [comment]
Done

**Pull request merged**
