### PR TITLE
[FIX] move wiki attachments to document_page attachments

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by parthivgls** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Could this be added to rename_models() in openupgradelib instead? https://github.com/OCA/openupgradelib/blob/develop/openupgradelib/openupgrade.py#L239

**Comment by hbrunn** [comment]
@StefanRijnhart yes, makes a lot of sense: https://github.com/OCA/openupgradelib/pull/22

**Pull request closed without merging**
