### PR TITLE
[ADD] crm_claim migration

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Updated https://github.com/OCA/OpenUpgrade/issues/400

**Comment by StefanRijnhart** [comment]
Should we maybe branch off the crm.case.categ's that were used as categ_id on any claims as items of the new crm.claim.category model?

**Comment by hbrunn** [comment]
@StefanRijnhart do you mean something else than https://github.com/OCA/OpenUpgrade/pull/574/files#diff-39a14eae8c8a7e993a88c6b386b3b968R12 ?

**Comment by StefanRijnhart** [comment]
Thanks, I had not even looked at that. It just occurred to me that the XML ids needed some more work. I created https://github.com/OCA/OpenUpgrade/pull/595 for that.

**Pull request merged**
