### PR TITLE
[15.0][OU-ADD] purchase_batch_invoicing: Merged into purchase

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36502

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please, could you link to the relevant Odoo code?

**Comment by sergio-teruel** [comment]
Hi @MiquelRForgeFlow 

Here is the action..

https://github.com/odoo/odoo/blob/37bebefd36ab138222a6ce1543ad2e47921f132c/addons/purchase/views/purchase_views.xml#L751-L761

**Review by MiquelRForgeFlow — APPROVED** [review]
Thanks

**Comment by pedrobaeza** [comment]
Please rebase and fix conflicts

**Comment by sergio-teruel** [comment]
Rebase done!

**Pull request merged**
