### PR TITLE
[10.0][ADD] Updated 'openupgrade_analysis.txt' files.

### PR DESCRIPTION
**Pull request by reinka**
Description of the issue/feature this PR addresses:
@pedrobaeza @jbeficent @StefanRijnhart @NL66278  After running openupgrade analysis again, we saw there have been some changes since the first openupgrade analysis back in Oct 2016. This was the motivation for checking and updating all related migration scripts if needed.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by omar7r** [comment]
:+1:

**Review by pedrobaeza — APPROVED** [review]
Tentatively approved, but I would like to know @StefanRijnhart's opinion

**Review by NL66278 — CHANGES_REQUESTED** [review]
It is clear that something is wrong with the analysis text. Many fields are now said to be in the hw_ecspos module, but that does not have any models at all.

The first change in this PR says currency_id is in hw_ecspos instead of in analytic. In reality it is in analytic still.

**Comment by pedrobaeza** [comment]
I think we need to blacklist this module because it explodes the system for having an stripped version for PosBox

**Comment by NL66278** [comment]
@pedrobaeza Actually the module is in odoo/addons/openupgrade_records/blacklist.py.

But the blacklist might me needed in more places then used now.

**Comment by pedrobaeza** [comment]
Yeah, it seems so. Then I bet now simply to remove the folder manually for making the analysis.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I remove my approval meanwhile

**Comment by StefanRijnhart** [comment]
I arrive at the following changes: https://github.com/OCA/OpenUpgrade/pull/871

**Comment by NL66278** [comment]
I would recommend closing this in favor of Stefan's PR: https://github.com/OCA/OpenUpgrade/pull/871

**Comment by hbrunn** [comment]
closing as this is superseded by #871

**Pull request closed without merging**
