### PR TITLE
[MIG][15.0] gamification: migration script

### PR DESCRIPTION
**Pull request by sang250399**
This PR
======
Migration done

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
Thanks again @sang250399

A question regarding noupdate_changes.xml

You are updating ``mail.template``. I think that you should also reset translation for  ``email_template_badge_received``, ``email_template_goal_reminder`` and ``mail_template_data_new_rank_reached``. Don't you think ? 


See similar work : 

https://github.com/OCA/OpenUpgrade/pull/3319/files#diff-46a6904a929ab8ba20acae0852dad5d3722dbb6c8e468cc5fb7268acfc1fa177R7

thanks.

**Comment by sang250399** [comment]
> Thanks again @sang250399
> 
> A question regarding noupdate_changes.xml
> 
> You are updating `mail.template`. I think that you should also reset translation for `email_template_badge_received`, `email_template_goal_reminder` and `mail_template_data_new_rank_reached`. Don't you think ?
> 
> See similar work :
> 
> https://github.com/OCA/OpenUpgrade/pull/3319/files#diff-46a6904a929ab8ba20acae0852dad5d3722dbb6c8e468cc5fb7268acfc1fa177R7
> 
> thanks.

sorry, my mistake. that is necessary, thank you

**Comment by daonamutc1** [comment]
@legalsylvain May you review again?

**Pull request merged**
