### PR TITLE
[ADD] have migrate.py download its own copy of openupgradelib

### PR DESCRIPTION
**Pull request by hbrunn**
This is more in line with the script fetching everything specific to openupgrade

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why do you need this?

**Comment by hbrunn** [comment]
This guarantees that openupgradelib's version matches openupgrade's version. Given that `migrate.py` pull the latest sources of openupgrade, it might rely on features not yet available in the user's openupgradelib installed via pypi

**Comment by pedrobaeza** [comment]
OK, I understand, because while we don't tag a commit, this won't be push to PyPi.

:+1:

**Comment by StefanRijnhart** [comment]
:+1:

**Pull request merged**
