### PR TITLE
[MIG][15.0] utm: migration script

### PR DESCRIPTION
**Pull request by sang250399**
This PR
======
Migration done

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
LGTM. Thanks.

**Review by daonamutc1 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@legalsylvain please wait until we resolve the CI problem (tests are not being executed) for merging new PRs.

**Comment by pedrobaeza** [comment]
@legalsylvain you can continue, but please check before merging if the modules are being detected correctly (check in the logs for `missing dependency` text)

**Comment by pedrobaeza** [comment]
In fact, in this PR the test haven't been correctly executed. Check in https://github.com/OCA/OpenUpgrade/runs/6892985524?check_suite_focus=true#step:13:54 that only `base` test has been run.

**Comment by pedrobaeza** [comment]
But on main branch tests they are: https://github.com/OCA/OpenUpgrade/runs/7210598841?check_suite_focus=true#step:13:54

I'm totally puzzled about what's happening...

**Comment by legalsylvain** [comment]
> @legalsylvain please wait until we resolve the CI problem (tests are not being executed) for merging new PRs.

sorry I've missed that point. is there a dedicated issue for that trouble ?

**Comment by pedrobaeza** [comment]
Please follow the conversation on mail PR

**Pull request merged**
