### PR TITLE
[DOC-ADD] Use Case : Model renaming

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Review by bguillot — APPROVED** [review]

**Comment by legalsylvain** [comment]
Looks like Benoit is taking part in a spanish code sprint today. thanks for all the reviews, and enjoy your beer!

**Comment by bguillot** [comment]
Yes indeed ! Thanks !

**Comment by legalsylvain** [comment]
Hi @rvalyi @primes2h. You set a :heart: on the PR. Is it an approval ? if yes could you do it by github approval, to merge this PR. 
thanks !

**Review by remytms — APPROVED** [review]
LGTM. Thanks for this great job. :)

**Pull request merged**
