### PR TITLE
[16.0][OU-ADD] pos_sale module

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration pos_sale

<dependency>Depends on : 

- point_of_sale : #4392</dependency>

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@legalsylvain please wait, that I'm checking something. There's a weird force installation process in pos.config (although not sure why the function is called even in noupdate=1). I hope having merge `pos_restaurant` will fix it.

**Pull request merged**
