### PR TITLE
[MIG][15.0] project: migration script

### PR DESCRIPTION
**Pull request by hoangtiendung070797**
This PR
======
migration done

### CODE REVIEW

**Comment by daiduongnguyen-odoo** [comment]
The title of PR should contain the version. BTW maybe you miss this PR @legalsylvain

**Review by phamgiang2510 — APPROVED** [review]

**Comment by daiduongnguyen-odoo** [comment]
> /ocabot migration project

@legalsylvain Thanks, if you have some time, please take a look at some of major module like Account, Payment, Sale, ... I will appriciate that sir

**Comment by phamgiang2510** [comment]
@hoangtiendung070797 correct the PR title pls

**Comment by legalsylvain** [comment]
> @legalsylvain Thanks, if you have some time, please take a look at some of major module like Account, Payment, Sale, ... I will appriciate that sir

Hi. Well, i'm more working on méta things to make life of openupgrader easier. (Work on ocabot, work on dependencies problem (sée #3399))
Also i dont use account apocalypse framework so i'm not the best to understand account migration)

Dix you answered to the oca survey regarding openupgrade strategy ?

Regards.

**Comment by daiduongnguyen-odoo** [comment]
> > @legalsylvain Thanks, if you have some time, please take a look at some of major module like Account, Payment, Sale, ... I will appriciate that sir
> 
> Hi. Well, i'm more working on méta things to make life of openupgrader easier. (Work on ocabot, work on dependencies problem (sée #3399)) Also i dont use account apocalypse framework so i'm not the best to understand account migration)
> 
> Dix you answered to the oca survey regarding openupgrade strategy ?
> 
> Regards.

Nice, love what you 're doing, but where is the oca survey openupgrade strategy, i can't find it.

**Comment by legalsylvain** [comment]
> Nice, love what you 're doing, but where is the oca survey openupgrade strategy, i can't find it.

I don't know if you have a twitter account, but if yes, I recommand to follow the OdooCommunity status
Here is the link.

https://twitter.com/OdooCommunity/status/1544468968655966208

Also you can subscribe to the OCA mailing list here. https://odoo-community.org/groups

the mailing is "contributors" and it also talked here : https://odoo-community.org/groups/contributors-15/contributors-247283?mode=thread&date_begin=&date_end=

Note, yes : in the odoo-community.org website, the survey is not very visible.

**Comment by MiquelRForgeFlow** [comment]
conflicts

**Comment by MiquelRForgeFlow** [comment]
Continued in https://github.com/OCA/OpenUpgrade/pull/3491.

**Pull request closed without merging**
