### PR TITLE
[IMP] Add moved fields to the analysis of their new module

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
Nice :+1:

**Review by pedrobaeza — APPROVED** [review]
Thanks again, @StefanRijnhart 

@mreficent please review new analysis lines of the already migrated modules to see if they impact something on the migration scripts.

**Comment by mreficent** [comment]
Ok

**Comment by MiquelRForgeFlow** [comment]
Ok @pedrobaeza 

@StefanRijnhart , should'nt this change be applied also in previous versions?

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza, I reviewed the new analysis lines (just the selection fields) and there is only a new impact. It is in `sale` module, one that is not migrated yet.

**Comment by pedrobaeza** [comment]
OK, thanks.

**Pull request merged**
