### PR TITLE
[MIG][14.0]pos_restaurant_adyen: nothing to do

### PR DESCRIPTION
**Pull request by hieu1211**
This PR
======
Nothing to do

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]

**Review by tranngocson1996 — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
What are dependencies?

**Comment by pedrobaeza** [comment]
@legalsylvain please refrain from merging PRs whose dependencies are not yet merged, and more being "Nothing to do". Please let this task to @MiquelRForgeFlow and me.

**Comment by legalsylvain** [comment]
sorry. i didn't noticed that point.

**Pull request merged**
