### PR TITLE
[11.0] update upstream 90c2e0c75e0

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Merge remote-tracking branch 'odoo/11.0' into 11.0-update-upstream-90c2e0c75e0

Without conflicts

**Desired behavior after PR is merged:**

Adds support for 0.0.0 versions migration scripts (https://github.com/odoo/odoo/commit/7b16abbae1d3af0e57730be872cef6b1f7d7a244)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Uhm, interesting... @mreficent how did you do the merge in this case? Or maybe some fixup are in the commit list?

**Comment by MiquelRForgeFlow** [comment]
There is not fixup. The merge was without conflicts. I just think that ocabot is not prepared for doing this kind of merges that contain merge commits.

**Comment by MiquelRForgeFlow** [comment]
:green_apple: yeah

**Pull request merged**
