### PR TITLE
[14.0][MIG] account_edi_facturx: nothing to do

### PR DESCRIPTION
**Pull request by tranngocson1996**
This PR
-------
Nothing to do

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]

**Comment by tranngocson1996** [comment]
thank @legalsylvain

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please put the `Nothing to do` in the coverage file, and that way the CI also activates the check to see if everything goes OK.

**Comment by pedrobaeza** [comment]
Seeing the file in

https://github.com/OCA/OpenUpgrade/blob/14.0/docsource/modules130-140.rst

in fact it should be put as `Done. Renamed from account_facturx`

**Comment by tranngocson1996** [comment]
@pedrobaeza Done sir

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
