### PR TITLE
[ADD] disable workflow transitions for stock.picking

### PR DESCRIPTION
**Pull request by hbrunn**
while replaying stock moves

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: We will gain speed with this

**Comment by hbrunn** [comment]
@pedrobaeza I'm not so sure if this is a speed improvement, as the workflow engine will be pulled anyways, only all transition conditions evaluate to `False`. In my case, `stock.picking` has transition conditions set which can't be evaluated at this point, that's why I propose to deactivate them.
By assumption the pickings are already in the correct state, so this shouldn't be harmful.

Unfortunately, there's no way I'm aware of to just disable the workflow engine completely, in a context key or something.

**Comment by pedrobaeza** [comment]
Uhm, I understand. Anyway, it's harmless as you say.

**Comment by hbrunn** [comment]
so given my ~200.000 stock moves take hours to migrate, I went for a radical disabling of the workflow. For OpenUpgrade, I think this is okay, because there's no multithreading and no multi database issues. This way, it's a few hours less. What do you think?

**Comment by pedrobaeza** [comment]
Well, you can do it if only for certain operations like this one, but yes, it's a valid approach for OpenUpgrade I think.

**Comment by StefanRijnhart** [comment]
It's like you say, the goal of this method is to fill quants. Any side effects from rerunning the workflow may even be harmful. :+1:

**Pull request merged**
