### PR TITLE
Make private methods private

### PR DESCRIPTION
**Pull request by blaggacao**
Assuming that there are only two true entry points into this module,
mark all other methods as private to the module.
Preparing: https://github.com/OCA/OpenUpgrade/issues/1587#issuecomment-433121344

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
What does it matter if they are private or public methods?

**Comment by blaggacao** [comment]
I wanted to outfactor this into a pip installable library. So it should become syntactically correct and transparent to consume, I guess.

Another way to look at it:
'' Vs '_' conveys meaning.
It's like a faulty documentation.

**Comment by pedrobaeza** [comment]
I'm not sure if you would be able to decouple this from ORM and module architecture itself.

**Comment by blaggacao** [comment]
@pedrobaeza, well the interface of this `compare` module is damn pretty minimal, so how you provide ORM capabilities to the wrapper code is not a concern of this module, actually.

~But you are right, it will not work without ORM, but there are other ways to provide it.~

Actually looking carefully this module only interfaces with a handful table in an odoo DB, so ORM could be easily obviated.

**Comment by pedrobaeza** [comment]
The problem I see decoupling the analysis to this architecture is that there are some information that you can't get only browsing the code (or it's very hard to do). Are you sure you want to go to that ride that can lead to frustration?

**Comment by blaggacao** [comment]
> The problem I see decoupling the analysis to this architecture is that there are some information that you can't get only browsing the code (or it's very hard to do). Are you sure you want to go to that ride that can lead to frustration?

Do you mean analyzing (in other words report generation) is not entirely contained in this module (excluding file writing and such stuff, just data structure wise)? If so, then we (I) should first change the interface of this module, of course.

Are there any specific side effects for analyzing not contained here or for which no clear interface description could be defined (eventually requiring an ORM)?

**Comment by pedrobaeza** [comment]
No, it's all here, but with the help of ORM of both analyzed versions and communicating through XML-RPC.

**Comment by blaggacao** [comment]
> No, it's all here, but with the help of ORM of both analyzed versions and communicating through XML-RPC.

Understand. Thanks, that's not a problem, all _that_ boilerplate can live in `click-odoo-migrator` without any problem.

**Comment by blaggacao** [comment]
My motivation for all this is: I don't need a whole OpenUpgrade > 1GB repo just as boilerplate to get a report of the changes that have occurred between two databases.

**Comment by pedrobaeza** [comment]
Yeah, I understand and share the motivation, but sometimes it's not so easy.

**Comment by blaggacao** [comment]
Here we go, with complete history: https://github.com/xoe-labs/openupgradelib-contrib

**Comment by blaggacao** [comment]
@pedrobaeza 

> Are you sure you want to go to that ride that can lead to frustration?

It took me 2 days, so far, and I'm already pretty happy... :smile: 

> No, it's all here

[Is it really?](https://github.com/xoe-labs/dodoo-migrator/tree/master/src/analyzer/schema_analyzer) :wink:

**Comment by pedrobaeza** [comment]
Can you put an example of what this analyzes?

**Comment by blaggacao** [comment]
Sure, it's still very `WIP`, but I'd explain the strategy:
```python
# 0. define receiving data structures for field spec of both branches
# 1. execute subroutine on two branches
# # 1. checkout branch (recursively)
# # 2. start odoo environment
# # 3. run get_dataframe_of_all_fields
# # 4. stop odoo environment
# 2. return a diff data frame with changed rows
# 3. identify known transitions
# 3bis. report known transition in a txt format similar to the OU analyzer format
# 4. generate PRE migration code stubs based on the known transitions - divided into: 
# - fully endogenous stubs (nothing to do)
# - exogenous stubs which provide code scaffolding and must be reviewed / completed manually
# 5. analyze noupdate=True body changes
# 6. Not sure yet: define body transformation functions for noupdate=True body changes
```
The key to understanding this strategy is:
- The [exogenous file](https://github.com/xoe-labs/dodoo-migrator/blob/master/src/analyzer/exogenous_schema_information.yaml)
- The [field slot analysis](https://github.com/xoe-labs/dodoo-migrator/blob/933c6e75a70c6c443e6b208f465d474aee9d0fe4/src/analyzer/schema_analyzer/analyzer.py#L39-L64) and it's [comparison](https://github.com/xoe-labs/dodoo-migrator/blob/933c6e75a70c6c443e6b208f465d474aee9d0fe4/src/analyzer/schema_analyzer/analyzer.py#L178)

Based on the field slot transitions we can catch transitions we couldn't before with the OU approach (because they are not visible from db introspection, only), furthermore those transitions are defined in [such an atomic way](https://github.com/xoe-labs/dodoo-migrator/blob/master/src/analyzer/schema_analyzer/_transitions.py) so that they can become the building blocks of composable code generators. The generated code might not be the shortest and most elegant code, but it will be standardized and repeatable.

After dealing with schema changes in PRE migration scripts and after executing a migration we can analyze [data body (`text`, `char`, `html`, `binary`) changes](https://github.com/xoe-labs/dodoo-migrator/blob/933c6e75a70c6c443e6b208f465d474aee9d0fe4/src/analyzer/data_analyzer/_transitions.py#L16) on `noupdate=true` records and see if we can find generic transformation functions for specific cases, and [high-lite suspect cases](https://github.com/xoe-labs/dodoo-migrator/blob/933c6e75a70c6c443e6b208f465d474aee9d0fe4/src/analyzer/data_analyzer/_transitions.py#L34-L37) otherwise.

**Comment by pedrobaeza** [comment]
OK, got it, but for now it's very similar in `openupgrade_records` module way of working from what I'm seeing. When you have a real full analysis file, please show me.

**Comment by blaggacao** [comment]
@pedrobaeza Yes, it's very similar. After all, that's the module I wanted to out-factor and give it's independence. Yet, it sticks with more atomic definitions than `openupgrade_records` this should be the game changer for enabling migration script stub generators. Generated code will be generally more transparent than borrowed library functions.

**Pull request closed without merging**
