### PR TITLE
[IMP] also install modules where there was nothing to do

### PR DESCRIPTION
**Pull request by hbrunn**
we also should install modules that are considered nothing to do

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should wait until we have a green build to see if everything is correct.

**Comment by hbrunn** [comment]
the intention is to get a green build with this. Modules like `hr_contract` won't be installed otherwise, and we need this to make `base_action_rule` work...
The problem now is that we have a bunch of modules depending on `website` migrated, while `website` itself errors out. I'll add a migration for that, let's see how this goes. But merging this won't make things worse, so I suggest to merge this anyways instead of hacking other stuff to make runbot green

**Comment by pedrobaeza** [comment]
Puf, this is getting really complicated...

Are you going to include here website migration or in a separate PR?

**Comment by hbrunn** [comment]
separate (completely untested) PR: #899

**Comment by pedrobaeza** [comment]
OK, merging this one, and reviewing the other.

**Pull request merged**
