### PR TITLE
[MIG][14.0] association: nothing to do

### PR DESCRIPTION
**Pull request by tranngocson1996**
This PR
-------
Nothing to do (it didn't have a migration folder)

### CODE REVIEW

**Comment by legalsylvain** [comment]
Migration folder should be present.
Don't you think ? Cc @pedrobaeza, @StefanRijnhart ?
 Could you try to regenerate it, with upgrade analysis ?'otherwise thanks for the work.

**Comment by tranngocson1996** [comment]
> Migration folder should be present. Don't you think ? Cc @pedrobaeza, @StefanRijnhart ? Could you try to regenerate it, with upgrade analysis ?'otherwise thanks for the work.

Thank @legalsylvain. I tried to regenerate it, but it didn't have a migration folder.

**Comment by pedrobaeza** [comment]
When there's no change, no `migrations` folder is generated AFAIK.

**Comment by tranngocson1996** [comment]
> When there's no change, no `migrations` folder is generated AFAIK.

@pedrobaeza I think that right

**Comment by legalsylvain** [comment]
@pedrobaeza : thanks for your answer.

I don't understand the difference between : 
* ``association`` module : no analysis file created.
* ``analytic`` module : an analysis file created that says that nothing changed. [Ref](https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/scripts/analytic/14.0.1.1/upgrade_analysis.txt).

any idea ?

**Comment by pedrobaeza** [comment]
Well, you tell me that maintains the `upgrade_analysis` module. I think there's a decision branch that creates nothing depending on the detected things.

**Comment by legalsylvain** [comment]
I don't see it. 
https://github.com/OCA/server-tools/blob/14.0/upgrade_analysis/models/upgrade_analysis.py#L245

maybe there is a silent error like this one : 
https://github.com/OCA/server-tools/blob/14.0/upgrade_analysis/models/upgrade_analysis.py#L101

**Comment by pedrobaeza** [comment]
I can't say, as I have never dug enough on such module.

**Comment by legalsylvain** [comment]
I just meld association manually.
nothing changed.

/ocabot merge nobump

**Pull request merged**
