### PR TITLE
[12.0][IMP] base: Faster ir_translation removal

### PR DESCRIPTION
**Pull request by pedrobaeza**
Using window function OVER (PARTITION BY ...), as explained in PostgreSQL wiki:

https://wiki.postgresql.org/wiki/Deleting_duplicates

In a real DB, it passes from requiring almost 10 minutes to require only 3 seconds.

cc @Tecnativa TT20635

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Ready to be reviewed.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by StefanRijnhart — APPROVED** [review]
Excellent!

**Pull request merged**
