### PR TITLE
[ADD] marked account_balance_line as merged in Odoo core. (account)

### PR DESCRIPTION
**Pull request by legalsylvain**
Ref : https://github.com/OCA/account-financial-tools/issues/1472

>  [X] ~account_balance_line~ Included in core

### CODE REVIEW

**Comment by pedrobaeza** [comment]
No need to wait in this one.

**Comment by hbrunn** [comment]
@legalsylvain @pedrobaeza but this should then also be added to the `merged_modules` dict, this is the `renamed_modules` dict which breaks the migration.

good reason to merge #3680? then we'll have a working CI...

**Comment by pedrobaeza** [comment]
Ouch, I trusted too much in Sylvain, hehe

I have fixed it in a02bcdd11934d33ade8d7c74517a06b055011337

I'm reviewing the base PR now for merging it.

**Comment by legalsylvain** [comment]
Hi @hbrunn I didn't pay attention. Sorry for the inconvenience and the broken tests.
have a nice day.

**Pull request merged**
