### PR TITLE
[12.0] update upstream 1341cc6ab92

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Updated.

No conflicts.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The same about the diff on noupdate file.

**Comment by pedrobaeza** [comment]
I suppose there's no diff now in noupdate, isn't it?

**Comment by MiquelRForgeFlow** [comment]
> I suppose there's no diff now in noupdate, isn't it?

Exactly 😅

**Pull request merged**
