### PR TITLE
[11.0][MIG] delivery

### PR DESCRIPTION
**Pull request by yvaucher**
Description of the issue/feature this PR addresses:

Migration of delivery module.

_inherits an product.product was removed from delivery.carrier. name and active fields

to merge before:

- [x] stock

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by StefanRijnhart** [comment]
I'm waiting to merge this until this module's dependency `stock` has been migrated, otherwise it will be making tests red until then.

**Comment by StefanRijnhart** [comment]
Oh, can you set the status of the module to Done in odoo/openupgrade/doc/source/modules100-110.rst?

**Comment by yvaucher** [comment]
Rebased and added Done to odoo/openupgrade/doc/source/modules100-110.rst

**Comment by cubells** [comment]
@yvaucher can you rebase as stock dependency is merged?

**Comment by pedrobaeza** [comment]
I have rebased it. Let's see CI result.

**Comment by cubells** [comment]
I have rebased too to correct a typo. Let's see CI result now.

**Pull request merged**
