### PR TITLE
[IMP] procurement: Use SQL for post messages

### PR DESCRIPTION
**Pull request by hbrunn**
my first approach was nonsense. This is a rewrite to use sql instead of `message_post`. My current database has ~80000 procurements with messages/notes, it would take hours to do this via the ORM, and given we don't need most of the things `message_post` does, I think this suffices

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I have changed the PR title to go accordingly. The body field should be in HTML, so please enclose the field into a `<p>` tag.

**Comment by hbrunn** [comment]
thanks! For good measure, I also escape `<` now

**Comment by pedrobaeza** [comment]
Should we scape also other characters (accentuated for example)? Isn't a method to make it?

**Comment by hbrunn** [comment]
No sql method I'm aware of. But given Odoo is delivered as utf8, escaping shouldn't be necessary.

But `&apos;` still has to be escaped

**Comment by StefanRijnhart** [comment]
I can see why you'd want this :+1:

**Comment by hbrunn** [comment]
@pedrobaeza with & and < escaped by now, we should be safe html wise. Also rebased

**Comment by pedrobaeza** [comment]
:+1:

**Comment by legalsylvain** [comment]
thanks. :+1:

**Pull request merged**
