### PR TITLE
[MRG] merge upstream 2019-02-05

### PR DESCRIPTION
**Pull request by hbrunn**
I propose this because in v10 the code for the Khmer language was changed:
https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/addons/base/res/res.lang.csv#L38
vs
https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res.lang.csv#L38

So if we run a succession of v10, v11, v12 upgrades, v12 will break because it tries to write the code field and breaks in https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_lang.py#L217

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@hbrunn The code change was reverted as it broke also Odoo itself. It was merged in other version (not sure if v11 or v12), but seeing the links, here it's not the change. I would bet you have to put it on pre-migration of the base module for v12.

**Comment by hbrunn** [comment]
ah, I looked at the wrong places, it's `km_KM` there still, but v12 wants to write `km_KH`. Do we add an SQL statement in v12 base's pre migration for this, or how are we going to fix inter version issues?

**Comment by pedrobaeza** [comment]
> Do we add an SQL statement in v12 base's pre migration for this, or how are we going to fix inter version issues?

Yes, a direct SQL update in base pre-migration is the best option for me, and we fix #1665 in that moment.

**Comment by hbrunn** [comment]
ah, didn't see this issue. Will come with a patch soon I think. The problem doesn't arise in the test db as 11 just doesn't have the language at all

**Comment by MiquelRForgeFlow** [comment]
hahaha And why won't you merge this PR anyway? there is a new module added (l10n_be_intrastat_2019), so eventually we will need to update upstream 😏

**Comment by hbrunn** [comment]
oh, if this is helpful anyways, I'll reopen. It's an unchanged merge of odoo/odoo

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
The problem here is that we have lost the SHA1 of the last upstream commit for tracking this. May I ask you to do the merge through commit and put it on the merge commit?

**Comment by hbrunn** [comment]
you mean as in rebase?

**Comment by pedrobaeza** [comment]
No, this is something learnt from @StefanRijnhart: instead of doing simply a pull over origin, you make a pull with a pin commit for having that commit reference. He can give more details.

**Comment by hbrunn** [comment]
then I wait here to learn the same thing

**Comment by StefanRijnhart** [comment]
In the PR, you need to mention the commit from upstream that you merged up to (instead of the date). That way, a reviewer can perform the same merge locally and check that the updated code is the same (with a git diff on your branch), and/or that any conflicts are solved in a sane manner.

**Comment by hbrunn** [comment]
so I rewrite this to the commit hash and then we're happy?

**Comment by StefanRijnhart** [comment]
Yes, either you recover the upstream commit that you merged or you start all over again keeping track of that commit, and mention it in the PR description either way.

**Comment by MiquelRForgeFlow** [comment]
Closed by https://github.com/OCA/OpenUpgrade/pull/1754.

**Pull request closed without merging**
