### PR TITLE
[FIX] Commit module state to database before migrating next module

### LINKED ISSUE #2255: Question about OpenUpgrade migration process
Still in the process of migrating a database from 11.0 to 12.0 I just go an issue that made me asking for the migration process.

At the first attempt to migrate [A], I got an exception raised from UoM `_check_category_reference_uniqueness` because I had two entries set as reference for the same category.
After fixing the DB manualy, I made a new attempt to migrate [B], but a new exception is raised about a non existing column from the resource module pre-migration script.

After watching logs, I can see that the resource module has already been migrated during [A] (pre and post migration scripts are executed) and looking at the database schema, I can see that the column `openupgrade_legacy_12_0_tz` is already there.

So my question is :
- Does the migration process is made using transaction ?
- Why the resource module version has not been written during [A] since the exception is raised from another module migration (uom) ?

[A: migrate-11-07_26__120_Upgrade_dec_database_to_OpenERP_Odoo_12_via_openupgrade.log](https://github.com/OCA/OpenUpgrade/files/4381673/migrate-11-07_26__120_Upgrade_dec_database_to_OpenERP_Odoo_12_via_openupgrade.log)
[B: migrate-14-14_45__120_Upgrade_dec_database_to_OpenERP_Odoo_12_via_openupgrade.log](https://github.com/OCA/OpenUpgrade/files/4381676/migrate-14-14_45__120_Upgrade_dec_database_to_OpenERP_Odoo_12_via_openupgrade.log)

### PR DESCRIPTION
**Pull request by ypapouin**
fixes #2255
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by pedrobaeza** [comment]
Is this needed in v13?

**Comment by StefanRijnhart** [comment]
Porting as we speak

**Comment by StefanRijnhart** [comment]
https://github.com/OCA/OpenUpgrade/pull/2257

**Pull request merged**
