### PR TITLE
[14.0][FIX] documentation: Prefix merged/renamed modules with `Done`

### PR DESCRIPTION
**Pull request by pedrobaeza**
So that the CI can detect them and check if there's something incorrect.

The paragraph about OCA modules has been removed as well, as that one is not maintained at all, and it's confusing then.

Let's see if this doesn't provoke a failed CI due to dependencies not yet "migrated".

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As expected, this fails as it installs all the dependencies chain. We will have to progressively switch the comments according the evolution of the migration scripts. I keep this opened meanwhile as reminder.

**Comment by MiquelRForgeFlow** [comment]
I don't like the deletion of the OCA modules section, as it might be used someday again. It was used to link an obsolete odoo module converted into OCA module.

**Comment by pedrobaeza** [comment]
@MiquelRForgeFlow that's not true. See the `account_bank_statement_import` one for example, that is documented inline in the Odoo modules table. It was used marginally for OCA modules that were renamed, but nobody cares/maintains/checks this.

**Comment by StefanRijnhart** [comment]
Are all of these covered by migration scripts if necessary?

If the OCA section is unused, it can go as far as I am concerned.

**Comment by StefanRijnhart** [comment]
Can you rebase to see what the failed Github workflow does this time? Or trigger a rerun in some other way.

**Comment by MiquelRForgeFlow** [comment]
We cannot merge it as it depends of other modules like `account`.

**Comment by StefanRijnhart** [comment]
So that's the point, the modules should not be set to done unless they and all their dependencies are covered by migration scripts.

**Comment by MiquelRForgeFlow** [comment]
Due to conflicts, rebased in https://github.com/OCA/OpenUpgrade/pull/3523.

**Pull request closed without merging**
