### PR TITLE
[11.0] update upstream a219bdb85e

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Merging upstream Odoo up until commit https://github.com/odoo/odoo/commit/a219bdb85e9078f88bb5a7b43b3598762a7bd819.

There were no conflicts.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Why is this commit part of this merge? https://github.com/OCA/OpenUpgrade/pull/1594/commits/ef5f69093a500ea262275cfa809e3f9737fda678

**Comment by MiquelRForgeFlow** [comment]
Because this is what my `compare_no_update_records` outputs. As it's likely the same but reordered, I am a bit lazy to check record by record if a new thing has appeared. So I overwrote it.

**Comment by StefanRijnhart** [comment]
Can you propose that one separately from the upstream update?

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart I think last commit is better and easier to review than before :)

**Comment by StefanRijnhart** [comment]
Sorry if I was unclear but I think such updates should be proposed in a separate PR

**Comment by MiquelRForgeFlow** [comment]
Ok, no problem. Commit deleted. What to do now?

**Review by StefanRijnhart — APPROVED** [review]
We can now merge once green

**Comment by MiquelRForgeFlow** [comment]
But doesn't get green :S

**Comment by StefanRijnhart** [comment]
It's the dreaded `fatal: Could not parse object` error from git. In my experience, the only thing that helps in this case is a rebase.

**Comment by MiquelRForgeFlow** [comment]
It's already rebased.

**Comment by MiquelRForgeFlow** [comment]
:green_apple:

**Pull request merged**
