### PR TITLE
[16.0][OU-ADD] sale_crm: Nothing to do

### PR DESCRIPTION
**Pull request by diamondnguyenkc**
Nothing to do

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration sale_crm

<dependency>Depends on : 

- sale : #4240</dependency>

**Review by robinkeunen — APPROVED** [review]
LGTM, nothing to do

**Review by remytms — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
`sale` module is not yet merged, so better not to merge this. Aborting. I'll check soon.

**Comment by legalsylvain** [comment]
Thanks @pedrobaeza . sorry i didn't saw the label "blocked by dependency"

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
