### PR TITLE
[12.0][FIX] base: deduplicate more translations

### LINKED ISSUE #1672: [12.0] could not create unique index "ir_translation_unique"
I tried to migrate a production database (11.0, migrated in the past from 8.0) to 12.0 and got this error (the key is randomly):

2019-01-02 22:35:38,462 11540 INFO prod_migrated odoo.modules.registry: module base: creating or updating database tables
2019-01-02 22:35:39,328 11540 ERROR prod_migrated odoo.sql_db: bad query: b'CREATE UNIQUE INDEX "ir_translation_unique" ON "ir_translation" (type, name, lang, res_id, md5(src))'
ERROR: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(field, sale.order.line,product_tmpl_id, nl_NL, 0, 9a1d6522e61266f6da2f9754109b8c46) is duplicated.

2019-01-02 22:35:39,331 11540 WARNING prod_migrated odoo.modules.loading: Transient module states were reset
2019-01-02 22:35:39,332 11540 ERROR prod_migrated odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 414, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 224, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 296, in init_models
    model._auto_init()
  File "/var/tmp/openupgrade/12.0/server/odoo/addons/base/models/ir_translation.py", line 278, in _auto_init
    ['type', 'name', 'lang', 'res_id', 'md5(src)'])
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/sql.py", line 205, in create_unique_index
    cr.execute('CREATE UNIQUE INDEX "{}" ON "{}" ({})'.format(indexname, tablename, args))
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(field, sale.order.line,product_tmpl_id, nl_NL, 0, 9a1d6522e61266f6da2f9754109b8c46) is duplicated.

2019-01-02 22:35:39,334 11540 CRITICAL prod_migrated odoo.service.server: Failed to initialize database `prod_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/12.0/server/odoo/service/server.py", line 1042, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 414, in load_modules
    report=report, models_to_check=models_to_check, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/loading.py", line 224, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/var/tmp/openupgrade/12.0/server/odoo/modules/registry.py", line 296, in init_models
    model._auto_init()
  File "/var/tmp/openupgrade/12.0/server/odoo/addons/base/models/ir_translation.py", line 278, in _auto_init
    ['type', 'name', 'lang', 'res_id', 'md5(src)'])
  File "/var/tmp/openupgrade/12.0/server/odoo/tools/sql.py", line 205, in create_unique_index
    cr.execute('CREATE UNIQUE INDEX "{}" ON "{}" ({})'.format(indexname, tablename, args))
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/12.0/server/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: could not create unique index "ir_translation_unique"
DETAIL:  Key (type, name, lang, res_id, md5(src))=(field, sale.order.line,product_tmpl_id, nl_NL, 0, 9a1d6522e61266f6da2f9754109b8c46) is duplicated.

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Detected in migrating OCA.

Fixes #1672

### CODE REVIEW

**Comment by ypapouin** [comment]
You should also add 'report' type

**Comment by MiquelRForgeFlow** [comment]
@ypapouin thanks, added.

**Comment by mgielissen** [comment]
This fix works for https://github.com/OCA/OpenUpgrade/issues/1672

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by StefanRijnhart** [comment]
Thanks for your testimony @mgielissen!

**Comment by pedrobaeza** [comment]
@mreficent @StefanRijnhart 

Odoo is adding some deduplication code in odoo/odoo#32826, so maybe we don't need this anymore if we update upstream after this change. Or this is a different case?

**Comment by StefanRijnhart** [comment]
It's a different case. The Odoo fix refers to a situation in which a part of the translation label contains an XML ID that is converted to a res_id in the database. If the XML IDs were different but referred to the same record, the deduplication did not take place and the constraint was triggered. It's only a problem when importing the translation files and does not affect migration of translations in the database. Well spotted, though, and could be useful to merge upstream after the fix is merged there.

**Comment by pedrobaeza** [comment]
Thanks for the insights! That's why I asked, as I'm not too deep in this topic for knowing it.

**Pull request merged**
