### PR TITLE
[12.0][MIG] phone_validation & crm_phone_validation

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
`#Nothingtodo` in `phone_validation` module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi, 

as this PR is "nothing to do", I think we could merge it. (and all other with the same status), because in fact, it is not blocked by dependency. don't you think ?

regards.

**Comment by pedrobaeza** [comment]
Well, first of all, a reviewer should validate if it's nothing to do (although on OpenUpgrade we can fast-merge if the contributor is very sure and CIs are OK), but this is in fact all blocked until the `base` migration PR is merged.

**Comment by legalsylvain** [comment]
Hi @pedrobaeza, I was not talking about the pr review process, just about the interest to mark the PR as "blocked". This PR can be merged now technically without any problem, even if the base module is not migrated. Or did I missed something ?

**Comment by pedrobaeza** [comment]
CI is red because it can't be merged while not their dependencies are merged, so they should be marked with "Blocked by dependency", or simply don't merge.

**Comment by MiquelRForgeFlow** [comment]
@legalsylvain The process of merging PRs should follow the graph of module dependencies. Like a tree, first merging the roots, and in the end the leaves.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
