### PR TITLE
[REF] Remove openupgradelib API from the OpenUpgrade documentation

### PR DESCRIPTION
**Pull request by legalsylvain**
- Remove openupgradelib API from the openupgrade documentation
- Add a link to the dedicated website : https://oca.github.io/openupgradelib

@pedrobaeza : it makes the build of the documentation quite trivial now. (ref [comment](https://github.com/OCA/OpenUpgrade/issues/3862#issuecomment-1538379919))

Depends on https://github.com/OCA/openupgradelib/pull/318

### CODE REVIEW

**Comment by legalsylvain** [comment]
This can be merged now.

**Comment by pedrobaeza** [comment]
But openupgradelib documentation is not yet published...

**Comment by legalsylvain** [comment]
> But openupgradelib documentation is not yet published...

Totally right ! PR merged, but undeployed. 
Let's wait a little bit.

**Comment by legalsylvain** [comment]
Now good. 

Openupgradelib documentation is finally up to date and available here : https://oca.github.io/openupgradelib

Can be merged

**Comment by pedrobaeza** [comment]
The methods signature and explanation are not being shown in the URL. Have you checked?

**Pull request merged**
