### PR TITLE
[11.0][MIG] note migration

### PR DESCRIPTION
**Pull request by fayezqandeel**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You have to clean your branches, as you are accumulating commits from other migrations. When you do that, I will be able to merge this as the analysis is correct.

**Comment by pedrobaeza** [comment]
Please cleanup this PR with only the migration of note, not other commits.

**Comment by pedrobaeza** [comment]
This is still not clean, and you are overloading Travis with a lot of commits launching a build.

**Comment by fayezqandeel** [comment]
@pedrobaeza I removed all commits and code from other branches, please have a look and let me know if now its fine, thanks.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
