### PR TITLE
[UPD] Analysis after last upstream merge

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Also change the way to detect if a selection is a list or a function, because now a function can also be referred to as a string instead of a function reference.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Conflicts

**Comment by StefanRijnhart** [comment]
@mreficent Thanks for noting! Conflict now fixed.

**Comment by MiquelRForgeFlow** [comment]
I rebased the PR again. Still travis in red :(

**Comment by StefanRijnhart** [comment]
Thanks for noting! Fixing tests here: https://github.com/OCA/OpenUpgrade/pull/1123

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
