### PR TITLE
[MIG][14.0] crm_iap_lead: Migration script

### PR DESCRIPTION
**Pull request by tranngocson1996**
This PR
-------
Migration done

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please, only one module per PR.

**Review by legalsylvain — APPROVED** [review]

**Comment by tranngocson1996** [comment]
> only one module per PR.

@pedrobaeza sr, i don't know. I'll remember that the next time.
@legalsylvain Thank for approve

**Comment by pedrobaeza** [comment]
Please split it.

**Comment by tranngocson1996** [comment]
> Please split it.

@pedrobaeza ok

**Comment by tranngocson1996** [comment]
@pedrobaeza done sir
cc: @legalsylvain

**Review by legalsylvain — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
