### PR TITLE
Fix duplicate removing script

### PR DESCRIPTION
**Pull request by ghost**
When the script is applied over a many2one field, the records will not be sorted properly
if some of them have null values.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
@dufresnedavid This code is [being moved](https://github.com/OCA/OpenUpgrade/pull/317) to https://github.com/OCA/OpenUpgradeLib

Do you mind making the same PR there?

**Comment by guewen** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Thanks, but needs to be proposed onto openupgradelib instead.

**Pull request closed without merging**
