### PR TITLE
[12.0][ADD] hr.holidays/.status models renames

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Added more model renames.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
AFAIK, `hr.holidays` has been split in 2 models, so it's not exactly a model rename...

**Comment by MiquelRForgeFlow** [comment]
Yeah, I know, but the main fields of hr.holidays went to the hr.leave instead of the other (hr.leave.allocation)

**Comment by pedrobaeza** [comment]
OK, just take into account possible XML-ID renames for data records.

**Pull request merged**
