### PR TITLE
[14.0][IMP] add l10n-italy renamed modules

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Comment by matteoopenf** [comment]
non andrebbe fatto anche per altri moduli? come mai lo fai solo per alcuni?

**Comment by sergiocorato** [comment]
> non andrebbe fatto anche per altri moduli? come mai lo fai solo per alcuni?

Feel free to list the other modules you refer, I'll put them in this PR.

**Comment by matteoopenf** [comment]
> > non andrebbe fatto anche per altri moduli? come mai lo fai solo per alcuni?
> 
> Feel free to list the other modules you refer, I'll put them in this PR.
Thank you @sergiocorato 

I see is only missing that;
l10n_it_dichiarazione_intento --> l10n_it_declaration_of_intent

**Review by legalsylvain — APPROVED** [review]
hi @sergiocorato.
Thanks for your contribution.
When you contribute to the apriori.py, could you provide PR / issue related to the renaming ? so the review is easier to do.

Regards.

**Comment by sergiocorato** [comment]
> > > non andrebbe fatto anche per altri moduli? come mai lo fai solo per alcuni?
> > 
> > 
> > Feel free to list the other modules you refer, I'll put them in this PR.
> > Thank you @sergiocorato
> 
> I see is only missing that; l10n_it_dichiarazione_intento --> l10n_it_declaration_of_intent

That one has already a function to rename the module, directly inside (I didn't know it was possible): https://github.com/OCA/l10n-italy/blob/c0ce8b454fb962f5270a4d43039e6353a5dcb60f/l10n_it_declaration_of_intent/__init__.py#L12

**Comment by matteoopenf** [comment]
> > > > non andrebbe fatto anche per altri moduli? come mai lo fai solo per alcuni?
> > > 
> > > 
> > > Feel free to list the other modules you refer, I'll put them in this PR.
> > > Thank you @sergiocorato
> > 
> > 
> > I see is only missing that; l10n_it_dichiarazione_intento --> l10n_it_declaration_of_intent
> 
> That one has already a function to rename the module, directly inside (I didn't know it was possible): https://github.com/OCA/l10n-italy/blob/c0ce8b454fb962f5270a4d43039e6353a5dcb60f/l10n_it_declaration_of_intent/__init__.py#L12

ok

**Pull request merged**
