### PR TITLE
[10.0][account] fix migration of account_reconcile_model_template

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Supersedes https://github.com/OCA/OpenUpgrade/pull/1131
Error on migration.

Right table should be account.reconcile.model.template

https://github.com/odoo/odoo/blob/10.0/addons/account/models/chart_template.py#L876

Trace error:
| 2017-10-18 09:53:26,539 18 INFO v10 odoo.modules.migration: module account: Running migration [10.0.1.1>] post-migration
| 2017-10-18 09:53:26,541 18 INFO v10 OpenUpgrade: account: post-migration script called with version 9.0.1.1
| 2017-10-18 09:53:26,544 18 INFO v10 odoo.sql_db: bad query: INSERT INTO account_reconcile_model_template
| (create_uid, create_date, write_uid, write_date,
| name, sequence, has_second_line,
| account_id, label, tax_id, amount_type, amount,
| second_account_id, second_label, second_tax_id, second_amount_type,
| second_amount)
| SELECT
| MIN(create_uid), MIN(create_date), MAX(write_uid), MAX(write_date),
| name, sequence, has_second_line,
| account_id, label, tax_id, amount_type, amount,
| second_account_id, second_label, second_tax_id, second_amount_type,
| second_amount
| FROM account_reconcile_model
| GROUP BY
| name, sequence, has_second_line,
| account_id, label, tax_id, amount_type, amount,
| second_account_id, second_label, second_tax_id, second_amount_type,
| second_amount
|
| 2017-10-18 09:53:26,545 18 ERROR v10 OpenUpgrade: account: error in migration script /opt/odoo/sources/odoo/addons/account/migrations/10.0.1.1/post-migration.py: insert or update on table "account_reconcile_model_template" violates foreign key constraint "account_reconcile_model_template_account_id_fkey"
| DETAIL: Key (account_id)=(30) is not present in table "account_account_template".

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@victormartinelicocorp please review

**Review by martintorresvm — APPROVED** [review]
LGTM. And migration passed.

**Comment by pedrobaeza** [comment]
Travis is failing

**Comment by martintorresvm** [comment]
> Travis is failing

@pedrobaeza May I ask what should be done on this situation? 
I mean as I checked Travis logs that as far I understand it is not because this PR, so might be better fix on separated PR?

BTW I follow your recommendation to use latest version of `openupgradelib` and it works.

cc @jbeficent

**Comment by pedrobaeza** [comment]
Relaunching Travis to see if it disappears, but if not, then the guilty is this PR.

**Comment by StefanRijnhart** [comment]
Thanks! Travis breakage is unrelated, while building the sphinx documentation. Hoping to fix that in https://github.com/OCA/OpenUpgrade/pull/1134

**Review by StefanRijnhart — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Merging as the red status has been proved to be unrelated.

**Comment by pedrobaeza** [comment]
It seems that at the end, Travis is broken after merging this.

**Pull request merged**
