### PR TITLE
[10.0][MIG] all pending noupdate=1 records

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This PR contains the migration scripts of the noupdate=1 records for the modules that in the [modules90-100.rst](https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/openupgrade/doc/source/modules90-100.rst) list are as `Done ` or `Nothing to do`.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for this!! :clap: :clap:

**Comment by cubells** [comment]
Thanks a lot!

**Comment by JordiBForgeFlow** [comment]
Good!

**Review by pedrobaeza — APPROVED** [review]
I have amended default website changes as they break the process.

**Pull request merged**
