### PR TITLE
[13.0][FIX] web_editor: remove deleting noupdate=0 xml records

### PR DESCRIPTION
**Pull request by zurawmaco**
_web_unsplash_ module depends on _web_editor_ module. 

In Odoo 12 _web_unsplash.web_unsplash_assets_ qweb template inherits from  _**web_editor.assets_editor**_. 

In Odoo 13 _web_unsplash.web_unsplash_assets_ inherits from _**web_editor.assets_wysiwyg**_. 

_web_editor.assets_editor_ should be deleted after update of _web_unsplash_ module.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't see this need. It's handled by the framework.

**Comment by zurawmaco** [comment]
It's not handled. 
1. First of all I saw an error in logs when OU tried to remove _web_editor.assets_editor_ qweb template. 
2. After migration I saw in database that _web_editor.assets_editor_ qweb template was still there.
3. Generally, in UI everything works, but unnecessary data is still in database

How OU handle cleaning data? Do You use another modules for those purpose?

**Comment by pedrobaeza** [comment]
It's cleaned by Odoo on the next `-u all` pass.

**Comment by zurawmaco** [comment]
1. I run Odoo 12 with new database with parameters below:
**-c ../odoo.conf -i base --without-demo=all -d maco_12_test_xml -p 13377**

2. I installed Invoicing module.

3. Then I run OU13 with parameters below:
**-c ../odoo.conf -d maco_12_test_xml -p 1376 --update=all --stop-after-init**

4. Then I run Odoo 13 with parameters below:
**-c ../odoo.conf -d maco_12_test_xml -u all**

5. I checked in _pgAdmin_ that  _web_editor.assets_editor_ is still in database. Additionally _account_invoice_ table is still in database :(
 
Are You sure that those records should be deleted itself by Odoo framework?

**Comment by pedrobaeza** [comment]
Tables and columns are not removed. Records for noupdate XML-IDs are.

**Comment by zurawmaco** [comment]
In Odoo 12 database when I checked record  in _ir_model_data_ table and I see that there is noupdate=0. 

After OU13 this record has noupdate=1. It's normal beacause _delete_records_safely_by_xml_id_ function changed this record. 

My question is: 
Why this record is not automatically deleted after updating _web_editor_ module?

**Comment by pedrobaeza** [comment]
This doesn't go through `delete_records_safely_by_xml_id` in normal update process.

**Comment by zurawmaco** [comment]
It does. 
addons > web_editor > migrations > 13.0.1.0 > post-migration.py

**Comment by pedrobaeza** [comment]
@kos94ok-3D you did such script. Can you tell us about the reasons?

**Comment by zurawmaco** [comment]
It doesn't matter. 

I removed unnecessary script in new commit. 

I am not sure. Should I create new PR with one commit or can I leave this PR as it is now?

**Comment by kos94ok-3D** [comment]
> @kos94ok-3D you did such script. Can you tell us about the reasons?

It was my first introduction with an Openupgrade so I could miss that these templates are noupdate='0'

**Comment by pedrobaeza** [comment]
Please squash all the commits into one.

**Review by StefanRijnhart — APPROVED** [review]
Tested successfully. With this code, web_editor.assets_editor is still removed on upgrade. Thanks!

Next time you will want to give your branch a meaningful name, as it makes it easier to manage your contributions.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
