### PR TITLE
[ADD][9.0] migration script for module 'hr_expense'

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**

### CODE REVIEW

**Comment by hbrunn** [comment]
https://travis-ci.org/OCA/OpenUpgrade/builds/146670836#L259

**Comment by hbrunn** [comment]
could you follow up on this one please?

**Comment by hbrunn** [comment]
and the last one: https://travis-ci.org/OCA/OpenUpgrade/builds/148052303#L269

**Comment by JordiBForgeFlow** [comment]
Not sure why Travis fails.

**Comment by hbrunn** [comment]
I linked the problematic line in the message above

**Comment by JordiBForgeFlow** [comment]
@hbrunn Travis passed.

**Pull request merged**
