### PR TITLE
[ADD] migration of addon warning

### PR DESCRIPTION
**Pull request by christophlsa**
simple migration of addon warning

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
:+1:, thanks!

**Comment by hbrunn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Don't you need to rename columns and get them with get_legacy_name on post migration?

**Comment by StefanRijnhart** [comment]
@pedrobaeza, to answer your question: the columns live in separate tables so renaming is not necessary.

**Comment by pedrobaeza** [comment]
Ok, thanks for the information.

**Pull request merged**
