### PR TITLE
Renamed l10n_it_account_balance_report

### PR DESCRIPTION
**Pull request by SirTakobi**
It happens in the PR https://github.com/OCA/l10n-italy/pull/3343

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please, put it above l10n_it_causali_pagamento to maintain alphabetical order.

**Comment by SirTakobi** [comment]
> Please, put it above l10n_it_causali_pagamento to maintain alphabetical order.

Thanks, done.

**Comment by MiquelRForgeFlow** [comment]
Once that PR is merged, I will merge this one.

**Comment by SirTakobi** [comment]
> Once that PR is merged, I will merge this one.

Thanks!
https://github.com/OCA/l10n-italy/pull/3343 is merged

**Pull request merged**
