### PR TITLE
[14.0][OU-FIX] website: fix extract_footer_copyright_company_name

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
Fix the way to get the views

cc @Tecnativa TT44601

@chienandalu @pedrobaeza please review

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The same about the commit message as in #4244

**Comment by pilarvargas-tecnativa** [comment]
> The same about the commit message as in #4244

Thanks

**Comment by pedrobaeza** [comment]
Check about the first line of the commit message and the `sub` command I mentioned in other pull request.

**Comment by pilarvargas-tecnativa** [comment]
> Check about the first line of the commit message and the `sub` command I mentioned in other pull request.

Done!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
