### PR TITLE
[MIG][15.0] crm_iap_lead_website: nothing to do

### PR DESCRIPTION
**Pull request by daiduongnguyen-odoo**
**This PR
Nothing to do**

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
If it's a rename, could you also set a line in the apriori.py file ? 

thanks !

**Comment by daiduongnguyen-odoo** [comment]
> If it's a rename, could you also set a line in the apriori.py file ?
> 
> thanks !

@legalsylvain Yes, i'll do it right away

**Review by legalsylvain — APPROVED** [review]

**Comment by legalsylvain** [comment]
thanks !

**Comment by pedrobaeza** [comment]
Can you please rebase and fix conflicts?

**Comment by daiduongnguyen-odoo** [comment]
> Can you please rebase and fix conflicts?

Done sir, have a good day

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
