### PR TITLE
[16.0][OU-ADD] point_of_sale

### PR DESCRIPTION
**Pull request by carmenbianca**
Work in progress during analysis. I may not have time to continue working on this soon.

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration point_of_sale

Thanks for this work. Please ping me when ready for review.

**Comment by pedrobaeza** [comment]
I would need this soon, so please tell Carmen if you are going to complete it. It doesn't seem too much to do.

**Comment by carmenbianca** [comment]
@pedrobaeza I will not work on this next week, as I will be at a conference. I do not yet know about the week after that, but the planning says no.

By all means feel free to take this from me.

**Comment by carmenbianca** [comment]
I will look at this again today.

**Comment by carmenbianca** [comment]
Done! :tada: In my manual testing all data that I've flagged is correctly migrated.

**Comment by pedrobaeza** [comment]
Thanks for the update, Carmen. There are several things to do, but I'm going to merge this and put another PR with them for not making you to perform the changes.

**Pull request merged**
