### PR TITLE
[12.0][IMP] openupgrade_records: defaults and many2manys tables

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Implements https://github.com/OCA/OpenUpgrade/issues/1204 and https://github.com/OCA/OpenUpgrade/issues/213.

Needs https://github.com/OCA/OpenUpgrade/pull/1907 to be merged.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Great! Can you create a separate branch with the resulting analysis between 11 and 12 with this patch? It would help to review this code.

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart done in https://github.com/OCA/OpenUpgrade/pull/1910.

**Comment by StefanRijnhart** [comment]
Nice. I like the side effect that it shows the target model of many2one fields!

What I don't like is that it shows the default values when the field is not required. Back in the day, I chose explicitely only to show the default value for required fields only, because that is where it matters (if there is a sane default value for a new required field, no migration is necessary). Would you consider restoring this behaviour? (I think the new behaviour does not improve readability, and the value of req_required is mostly just 'function' which is not very informative)

**Comment by MiquelRForgeFlow** [comment]
Ok, but then you should close https://github.com/OCA/OpenUpgrade/issues/1204

**Comment by pedrobaeza** [comment]
Stefan, this was the result of a discussion in a pr for knowing if a new field is providing a default value for acting according that, but unfortunately, there's no link to it. I still think it's valuable.

**Comment by StefanRijnhart** [comment]
Haha I opened an issue for that :-P

@mreficent I'll leave it to your own judgment then.

**Review by StefanRijnhart — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
