### PR TITLE
[FIX+IMP] stock: Several refinements

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Error in comparison in create_specific_procurement_rules_from_globals
* Compute stock.move.reference & stock.picking.scheduled_date through SQL
* Add logging trace for each post-migration method

@Tecnativa

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
I think you also should update the `openupgrade_analysis_work.txt` file

**Comment by pedrobaeza** [comment]
That fields are not present there, as there were before. The change has been in their `store` attribute. Maybe we should log that change also in `openupgrader_records` module.

**Comment by MiquelRForgeFlow** [comment]
Yes, I think that should be logged. In fact, I thought that it was already logging that.

**Comment by pedrobaeza** [comment]
But that's something out of the scope of this PR.

**Comment by MiquelRForgeFlow** [comment]
Of course.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by cubells — APPROVED** [review]
:+1: 

LGTM too

**Pull request merged**
