### PR TITLE
[ADD] Migration scripts for project_issue

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by paulius-sladkevicius** [comment]
:+1: Ignore Travis, it's failing because of MRP migration.

**Comment by bwrsandman** [comment]
> :+1: Ignore Travis, it's failing because of MRP migration.

Can you link to the issue in question?
Should the merge wait for another first?
@StefanRijnhart you should be able to rerun the test on travis-ci.org

**Comment by legalsylvain** [comment]
Hi.
I really don't understand Travis result. 
- This PR fails in Travis; but in this branch, there is no 'mrp' files because this PR is no up to date
  https://github.com/StefanRijnhart/OpenUpgrade/tree/8.0-project_issue says : 
  "This branch is 155 commits ahead and 0 commits behind master" 
- The OpenUpgrade/8.0 succeed in Travis;

@Stephan, can you try to git pull upstream 8.0 and git rebase your 2 last commits ?
(Not sure that it will solve the problem).

+++

**Comment by StefanRijnhart** [comment]
Will do. Setting to WIP. Coming to think of it, I need to adopt the API addition in the project module to remap the issue priorities as well.

**Comment by StefanRijnhart** [comment]
Rebased and green

**Comment by legalsylvain** [comment]
Thanks!

**Pull request merged**
