### PR TITLE
[15.0][OU-ADD] mass_mailing_event_track: Nothing to do

### PR DESCRIPTION
**Pull request by pedrobaeza**
Even no analysis file.

@Tecnativa TT41016

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It's not blocked by dependency, @legalsylvain. It's simply a bad interaction, as we do a trick in the CI installing all modules in the previous version (and thus, having the records), and then marking them as `uninstalled` by SQL. I'm going the straight way not doing the conflicting XML-IDs renaming. It was just completeness effort.

**Comment by legalsylvain** [comment]
I didn't put "Blocked by Dependency". the script I ran did it ! 
(https://github.com/OCA/OpenUpgrade/issues/3979, feedback welcome BTW)

It is based on the parsing of the file https://github.com/OCA/OpenUpgrade/blob/15.0/docsource/modules140-150.rst. For instance, ``website_event_track`` is marked as TODO.

After investigation, it is because you forgot to update the coverage file in this PR. https://github.com/OCA/OpenUpgrade/pull/3751

This trivial PR should fix the problem : https://github.com/OCA/OpenUpgrade/pull/4049

**Comment by pedrobaeza** [comment]
OK, thank you for checking.

**Pull request merged**
