### PR TITLE
[FIX] Improve Accounting migration SQL performance

### PR DESCRIPTION
**Pull request by mourad-ehm**
Improve Accounting migration SQL performance. 
Current behaviour before PR:

Update query is very slow (It was still running after 24 hours). Here Execution plan. 

```SQL
EXPLAIN update account_cashbox_line l set cashbox_id=(select id from account_bank_statement_cashbox where l.id=any(openupgrade_legacy_9_0_cashbox_lin
e_ids));   
                 QUERY PLAN                                            
 --------------------------------------------------------------------------------------------------
 Update on account_cashbox_line l  (cost=0.00..3025693421.44 rows=1055204 width=63)
  ->  Seq Scan on account_cashbox_line l  (cost=0.00..3025693421.44 rows=1055204 width=63)
         SubPlan 1
           ->  Seq Scan on account_bank_statement_cashbox  (cost=0.00..2867.35 rows=3445 width=4)
                 Filter: (l.id = ANY (openupgrade_legacy_9_0_cashbox_line_ids))
(5 rows)
```
Desired behavior after PR is merged:
Query was executed in less then 10 minutes : 

```SQL
EXPLAIN update account_cashbox_line l set cashbox_id=cb.id                                                                                          
FROM (select id, openupgrade_legacy_9_0_cashbox_line_ids from account_bank_statement_cashbox) cb
where l.id=any(cb.openupgrade_legacy_9_0_cashbox_line_ids);

QUERY PLAN                                                      
----------------------------------------------------------------------------------------------------------------------
  Update on account_cashbox_line l  (cost=0.43..536956.10 rows=704597 width=69)
   ->  Nested Loop  (cost=0.43..536956.10 rows=704597 width=69)
         ->  Seq Scan on account_bank_statement_cashbox  (cost=0.00..1986.60 rows=70460 width=91)
         ->  Index Scan using account_cashbox_line_pkey on account_cashbox_line l  (cost=0.43..7.49 rows=10 width=59)
               Index Cond: (id = ANY (account_bank_statement_cashbox.openupgrade_legacy_9_0_cashbox_line_ids))
(5 rows)
```

I suggest to never use Update Select but Update From. 
Ex:
Not 
```SQL
Update Table t set column1 = (Select column2 from Table2 where col3=t.id ...)
```
But
```SQL
Update Table t Set column1 = t2.column2
From (Select column2 from Table2 (where  ...)) as t2
WHERE t.id = t2.col3
```

### CODE REVIEW

**Review by hparfr — APPROVED** [review]
Impressive perf boost

**Review by sylvainc — APPROVED** [review]

**Comment by mourad-ehm** [comment]
ping @pedrobaeza

**Comment by jholze** [comment]
@rruebner

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Jordi, `UPDATE` expressions are not optimal because they contain a subselect and it's not needed. Please don't merge so quickly if I have been pinged.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Oh, ok.

**Pull request merged**
