### PR TITLE
[ADD] sales_team

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Updated DOC
* Work analysis file
* Pre-migration script

### CODE REVIEW

**Comment by lfreeke** [comment]
ping @gfcapalbo

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by pedrobaeza** [comment]
This one continues with the same error about crm.lead that will be fixed on crm migration, so it can be merged.

**Comment by pedrobaeza** [comment]
Merging this one for being able to test crm one

**Pull request merged**
