### PR TITLE
 Merge upstream until 0916a03 

### LINKED ISSUE #2356: [13.0] need to refresh Odoo
We need [this commit](https://github.com/odoo/odoo/commit/0e3c5d3ee1726db2641cd683a84fe59e867d4319) in OpenUpgrade 13.0, because `product_variant_configurator` adds a `product_id` field on `product_product`.

How is it usually done in this project?

### PR DESCRIPTION
**Pull request by sbidoul**
There were merge conflict in 
- `README.md`
- `addons/website/models/ir_ui_view.py`
- `addons/mail_bot/__manifest__.py`

Closes #2356 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please put the diff for the conflict resolution? GitHub is not visualizing it.

**Comment by sbidoul** [comment]
@pedrobaeza here is the merge commit

```patch
Author: Stéphane Bidoul <stephane.bidoul@acsone.eu>  2020-06-28 11:56:54
Committer: Stéphane Bidoul <stephane.bidoul@acsone.eu>  2020-06-28 11:56:54
Parent: dae6189b770e65e7511cdc0067a4587a4a249cd2 (Merge pull request #2355 from kos94ok-3D/13.0-mig-product-fix)
Parent: 0916a03c561ec76406f0c921140f9f9a0c789d62 ([I18N] Update translation terms from Transifex)
Branches: ou-13-upd-20200628-sbi, remotes/openupgrade-acsone/ou-13-upd-20200628-sbi
Follows: 10.0-wip-aabd02a-odoo
Precedes: 

    Merge upstream until 0916a03c5

--------------------- addons/website/models/ir_ui_view.py ---------------------
index a7a8ffaddf5,f2b70c0f8a8..70ba7ee432c
@@@ -174,15 -165,8 +165,15 @@@ class View(models.Model)
                      view.with_context(website_id=website.id).write({'name': view.name})
  
          specific_views = self.env['ir.ui.view']
 -        if self and self.pool._init:
 +
 +        # OpenUpgrade: force a False condition to never enter this code block.
 +        # This is needed because the update process could correctly unlink
 +        # website-agnostic views, but we don't want the website-specific
 +        # equivalents to be removed during the migration.
 +        if False and self and self.pool._init:
 +        # OpenUpgrade: end of modification
 +
-             for view in self:
+             for view in self.filtered(lambda view: not view.website_id):
                  specific_views += view._get_specific_views()
  
          result = super(View, self + specific_views).unlink()

```

**Comment by pedrobaeza** [comment]
Uhm, now that I see that, I'm not sure that patch is needed here in v13. It was put in v12, and possibly translated to v13 as "a block". @StefanRijnhart can you tell if you put that with any intention or was it only the FW port in block?

**Comment by StefanRijnhart** [comment]
@pedrobaeza This change was ported as part of the framework patch extracted from the previous version.

**Comment by pedrobaeza** [comment]
Then it can be removed as suspected. @sbidoul if you want to do it, or we can do it after merging this.

**Comment by pedrobaeza** [comment]
Anyway, it should be in a different commit.

**Comment by sbidoul** [comment]
I would'nt know what to write as message on such commit, so better do that in another PR.

**Comment by pedrobaeza** [comment]
OK, I'll do it. Thanks for the update.

**Comment by pedrobaeza** [comment]
@Yajo I would like to have your confirmation before removing that lines from this version.

**Comment by yajo** [comment]
Yes, that was only needed for v12.

**Comment by pedrobaeza** [comment]
OK, thanks for the confirmation.

Reverted in dd2f0510da76f5b21270109dc05034dd9a070a4b

**Pull request merged**
