### PR TITLE
[10.0][FIX] hr_timesheet: Create project for all possible timesheets

### PR DESCRIPTION
**Pull request by pedrobaeza**
If you have disabled "use_timesheets" in an analytic account, but you have already introduced timesheets for it, when migrating, you get a problem, as these timesheets won't have any linked project.

Changing the SQL for creating missing projects, basing it also in the existing timesheets, apart from the existing criteria, fixes the problem.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@bodi000 please review

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Having read the conversation on #2362, I agree with this alternatie. @bodi000 about not renaming the one field while the other field is renamed, you are right about the consistency but it's a bit late in the 10.0 development cycle to do so now.

**Review by MiquelRForgeFlow — APPROVED** [review]
Very special case, but ok.

**Comment by bodi000** [comment]
fine with me. I thought the second version was cleaner, but I got your point :-)

Best

**Pull request merged**
