### PR TITLE
[ADD] base_action_rule

### PR DESCRIPTION
**Pull request by pedrobaeza**
* Analysis work
* Migration script
* Update documentation
* noupdate changes not present

Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hbrunn** [comment]
any thoughts on CI failing? https://travis-ci.org/OCA/OpenUpgrade#L1514

**Comment by hbrunn** [comment]
hmmm, not much to do, this is caused by demo data originating from crm (https://github.com/OCA/OCB/blob/9.0/addons/crm/crm_action_rule_demo.xml). I suggest we simply migrate the crm module next, then things should work fine

**Comment by pedrobaeza** [comment]
Well, I suppose it's that. Then we know which module to prioritize :wink:

**Comment by hbrunn** [comment]
ping @lfreeke

**Comment by StefanRijnhart** [comment]
@hbrunn @pedrobaeza Breaking the CI changes everything wrt. optimistic merging. Is anyone working on a fix yet? It is quite an awful situation.

**Pull request merged**
