### PR TITLE
Analytic

### PR DESCRIPTION
**Pull request by arthru**
This add file openupgrade_analysis_work.txt for analytic module (no migration is needed here)

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
I suggest to keep this on hold until we have the API to fill message_last post, which should then be applied here.

**Comment by bwrsandman** [comment]
The API is part of #13

**Comment by arthru** [comment]
Just updated, thanks bwrsandman !

**Comment by bwrsandman** [comment]
:+1: 
LGTM

**Comment by bwrsandman** [comment]
Just update `openerp/openupgrade/doc/source/modules70-80.rst` to reflect the coverage of Analytic.
You will need to rebase with upstream/master

```
git remote add upstream https://github.com/OpenUpgrade/OpenUpgrade.git
git pull --rebase upstream master
```

**Comment by StefanRijnhart** [comment]
Tnx! :+1: now

**Pull request merged**
