### PR TITLE
Use openupgrade lib and warn old use

### PR DESCRIPTION
**Pull request by bwrsandman**
7.0 version of #341 

Reopen of #317 on my own branch

We ported the openupgrade scripts to pypi

[pypi Package](https://pypi.python.org/pypi/openupgradelib)

The recommendation for using those scripts is now: `from openupgradelib import openupgrade`

This patch should properly raise a warning be reverse compatible as long as openupgradelib is intalled in the python path.

The reasoning behind moving this bit of code to a lib is for module migrations within the same Odoo version but with changes in a module such as a field rename.

Prior to this, the recommended way was to copy code into migrations if not use OpenUpgrade. This makes the code reusable and gets rid of code duplication.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@bwrsandman, can you please rebase? Or may I superseed the branch?

**Comment by pedrobaeza** [comment]
Finished a 7.0 migration with this PR properly rebased and the changes in https://github.com/OCA/openupgradelib/pull/11, so :+1:

**Comment by bwrsandman** [comment]
@pedrobaeza done

**Comment by pedrobaeza** [comment]
:+1: again

**Comment by pedrobaeza** [comment]
@StefanRijnhart, can you merge this one now that openupgradelib contains the fix for supporting this version? You should push to pypi that version although.

**Comment by StefanRijnhart** [comment]
@pedrobaeza have you tested a migration with this branch?

**Comment by StefanRijnhart** [comment]
Oh, I see you have, 28 days ago ;-)

**Comment by StefanRijnhart** [comment]
@pedrobaeza I have made a release commit and tagged it 1.1.0, pushing it to develop and syncing develop to master. However, Pypi does not allow me to upload the release. I think it is because I am not an owner on the project. Only board members are owners of the project, so I think you will have to do it.

**Comment by pedrobaeza** [comment]
OK, I have finally got it to push it, so now library is in final version. We should eventually grant access to a new openupgradelib-maintainers role for doing these things, although it can't be a group, but a login+password thing.

**Pull request merged**
