### PR TITLE
[12.0][MIG] board

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Migration scripts of `board` module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You have left out this noupdate record change:
```xml
<?xml version='1.0' encoding='utf-8'?>
<odoo>
  <record id="open_board_my_dash_action" model="ir.actions.act_window">
    <field name="help" type="html"/>
  </record>
</odoo>
```

**Comment by MiquelRForgeFlow** [comment]
I have left out this on purpose. It gives error if you put this because that field doesn't exist.

**Comment by pedrobaeza** [comment]
I have just checked in a fresh 12.0 DB and it exists:
seleccion_032

**Comment by MiquelRForgeFlow** [comment]
Then check the error message if you put that :S

**Comment by pedrobaeza** [comment]
And where is that error message? Can you show me?

**Comment by MiquelRForgeFlow** [comment]
Here: https://travis-ci.org/OCA/OpenUpgrade/builds/466071582

```python
2018-12-10 16:30:58,433 6419 INFO openupgrade odoo.tools.convert: /home/travis/build/OCA/OpenUpgrade/addons/board/migrations/12.0.1.0/noupdate_changes.xml:3:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element odoo has extra content: record 
2018-12-10 16:30:58,433 6419 ERROR openupgrade OpenUpgrade: board: error in migration script board/migrations/12.0.1.0/post-migration.py: Element odoo has extra content: record, line 3 
2018-12-10 16:30:58,433 6419 ERROR openupgrade OpenUpgrade: Element odoo has extra content: record, line 3 
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/home/travis/build/OCA/OpenUpgrade/addons/board/migrations/12.0.1.0/post-migration.py", line 9, in migrate
    env.cr, 'board', 'migrations/12.0.1.0/noupdate_changes.xml')
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 296, in load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode=mode)
  File "/home/travis/build/OCA/OpenUpgrade/odoo/tools/convert.py", line 856, in convert_xml_import
    relaxng.assert_(doc)
  File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src/lxml/lxml.etree.c:184715)
AssertionError: Element odoo has extra content: record, line 3
2018-12-10 16:30:58,434 6419 ERROR openupgrade odoo.modules.loading: Error executing post migration script for module board
: Element odoo has extra content: record, line 3 
2018-12-10 16:30:58,436 6419 WARNING openupgrade odoo.modules.loading: Transient module states were reset 
2018-12-10 16:30:58,436 6419 ERROR openupgrade odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/loading.py", line 364, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/loading.py", line 259, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/home/travis/build/OCA/OpenUpgrade/addons/board/migrations/12.0.1.0/post-migration.py", line 9, in migrate
    env.cr, 'board', 'migrations/12.0.1.0/noupdate_changes.xml')
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 296, in load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode=mode)
  File "/home/travis/build/OCA/OpenUpgrade/odoo/tools/convert.py", line 856, in convert_xml_import
    relaxng.assert_(doc)
  File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src/lxml/lxml.etree.c:184715)
AssertionError: Element odoo has extra content: record, line 3
2018-12-10 16:30:58,437 6419 CRITICAL openupgrade odoo.service.server: Failed to initialize database `openupgrade`. 
Traceback (most recent call last):
  File "/home/travis/build/OCA/OpenUpgrade/odoo/service/server.py", line 1042, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/loading.py", line 364, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/loading.py", line 259, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/travis/build/OCA/OpenUpgrade/odoo/modules/migration.py", line 187, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 1445, in wrapped_function
    if use_env2 else cr, version)
  File "/home/travis/build/OCA/OpenUpgrade/addons/board/migrations/12.0.1.0/post-migration.py", line 9, in migrate
    env.cr, 'board', 'migrations/12.0.1.0/noupdate_changes.xml')
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 296, in load_data
    tools.convert_xml_import(cr, module_name, fp, idref, mode=mode)
  File "/home/travis/build/OCA/OpenUpgrade/odoo/tools/convert.py", line 856, in convert_xml_import
    relaxng.assert_(doc)
  File "src/lxml/lxml.etree.pyx", line 3501, in lxml.etree._Validator.assert_ (src/lxml/lxml.etree.c:184715)
AssertionError: Element odoo has extra content: record, line 3
```

**Comment by pedrobaeza** [comment]
OK, it's an "error" on the compare script. Remove `type="html"` part and everything will go well.

**Comment by MiquelRForgeFlow** [comment]
ok

**Pull request merged**
