### PR TITLE
[ADD] Migrate crm_claim category data

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Why do you need such kind of tests?

**Comment by StefanRijnhart** [comment]
@jbeficent To validate this problem: https://travis-ci.org/OCA/OpenUpgrade/builds/148793610#L3194

**Comment by StefanRijnhart** [comment]
Note that the green travis is misleading (https://github.com/OCA/OpenUpgrade/issues/588)

**Comment by hbrunn** [comment]
:+1: will have a look on the travis issue right now

**Pull request merged**
