### PR TITLE
[MRG] merge upstream 2015-02-19

### PR DESCRIPTION
**Pull request by hbrunn**
This is necessary as OpenUpgrade's version of the new API doesn't handle selection_add correctly, resulting in exceptions when module to be migrated rely on the added selection options.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you point us to the conflic resolution commit?

**Comment by hbrunn** [comment]
```
    Conflicts:
        README.md
        openerp/modules/loading.py
        openerp/modules/migration.py
```

`README.md` and `openerp/modules/migration.py` was solved by `git checkout --ours`, `openerp/modules/migration.py` had the following conflict:

```
@@@ -289,13 -248,15 +279,19 @@@ def load_marked_modules(cr, graph, stat
      while True:
          cr.execute("SELECT name from ir_module_module WHERE state IN %s" ,(tuple(states),))
          module_list = [name for (name,) in cr.fetchall() if name not in graph]
++<<<<<<< HEAD
 +        module_list = openupgrade_loading.add_module_dependencies(cr, module_list)
++=======
+         if not module_list:
+             break
++>>>>>>> odoo/8.0
          graph.add_modules(cr, module_list, force)
          _logger.debug('Updating graph with %d more modules', len(module_list))
 -        loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
 +        loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
          processed_modules.extend(processed)
          loaded_modules.extend(loaded)
-         if not processed: break
+         if not processed:
+             break
      return processed_modules
```

Which was trivial, but I also needed commit 018cddb7d0f3d84332fca413601dc011c5ecde51

**Comment by pedrobaeza** [comment]
Thanks

:+1:

**Comment by hbrunn** [comment]
is the minus a typo?

**Comment by pedrobaeza** [comment]
Of course, a bad move over of mouse pointer. Fixed. Sorry

**Comment by pedrobaeza** [comment]
We should move forward this PR to prevent problems when migrating to 8.0.

**Comment by StefanRijnhart** [comment]
:+1:

**Pull request merged**
