### PR TITLE
[FIX] ignore view errors during upgrade

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This was in previous versions of OpenUpgrade. Has this been deactivated in the switch to Odoo?

**Comment by hbrunn** [comment]
Not on purpose, but it didn't make it through the automatic transition as this is new code (from the point of view of 7.0)

**Comment by StefanRijnhart** [comment]
My bad for quick and dirty merge of Odoo 8.0 stable recently. Thanks! :+1:

**Comment by legalsylvain** [comment]
Thanks. :+1:

**Pull request merged**
