### PR TITLE
[FIX] cleanup a view from account_report_company

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Can you also clean up the dangling reference in ir_model_data?

**Comment by hbrunn** [comment]
@StefanRijnhart shouldn't OpenUpgrade remove that automatically after the migration of account?

**Comment by StefanRijnhart** [comment]
The uninstallation of account_report_company does that, yes. As such, it is an inconsistency but a harmless one at that. I guess I can live with that. :+1:

**Comment by legalsylvain** [comment]
:+1: Thanks.

**Pull request merged**
