### PR TITLE
[12.0][ADD] apriori: product and uom model renames

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
More model renames.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Don't you have to rerun the analysis after this?

**Comment by MiquelRForgeFlow** [comment]
Yeah, but it's not required to rerun it. Maybe I will rerun it after the next update from upstream.

**Comment by pedrobaeza** [comment]
Well, it's convenient to do it if you are going to continue migrating things for having proper analysis files, but I let you to decide when.

**Comment by MiquelRForgeFlow** [comment]
Sure. When we begin "officially" the process to migrating then I will rerun the analysis :)

**Review by pedrobaeza — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
I have found more model renames. I will do a full search of model renames to avoid doing X PRs.

**Comment by pedrobaeza** [comment]
OK, great.

**Pull request merged**
