### PR TITLE
[IMP] speedup commercial field sync

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
wait for #137

**Comment by pedrobaeza** [comment]
You have to rebase due to the change of branch

**Comment by hbrunn** [comment]
rebasing done

**Comment by StefanRijnhart** [comment]
You are replacing a call from _fields_sync with _commercial_sync_from_company. It looks like this way, addresses are not propagated.

Then, if you would solve that by calling update _address manually, there seems to be a fringe case in which there is a partner structure A -> B -> C where B and C both would want to use A's address. If C comes before B in the loop, then C syncs B's empty address, after which B syncs A's address, leaving C's empty. Not sure what the real impact of this would be though.

**Comment by StefanRijnhart** [comment]
Hope I'm not misusing the Question tag when I am looking for a replacement of Launchpad's 'Needs information' review.

**Comment by pedrobaeza** [comment]
As you can see here: https://github.com/OpenUpgrade/OpenUpgrade/blob/7.0/openerp/addons/base/res/res_partner.py#L467, that method makes commercial fields sync + address sync if "Use parent address" is marked. As this field is not set in migration, the result is the same.

**Comment by pedrobaeza** [comment]
@hbrunn, please rebase again.

**Comment by StefanRijnhart** [comment]
Thanks for the insight! That makes it a lot easier to accept this. :+1: after rebase.

**Comment by hbrunn** [comment]
rebase done

**Pull request merged**
