### PR TITLE
[16.0][OU-ADD] hr_work_entry: Nothing to do

### PR DESCRIPTION
**Pull request by victoralmau**
Nothing to do

Depends on:
- [x] https://github.com/OCA/OpenUpgrade/pull/3911

@Tecnativa TT42391

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration hr_work_entry

<dependency></dependency>

**Review by chienandalu — COMMENTED** [review]
Depends on:

- [ ] https://github.com/OCA/OpenUpgrade/pull/3911

**Review by SirAionTech — APPROVED** [review]

**Pull request merged**
