### PR TITLE
[ADD] build most recent docs; support python3

### PR DESCRIPTION
**Pull request by hbrunn**
you can see the result on https://doc.therp.nl/openupgrade (and didn't we want to move this to some OCA server? Or should we maybe publish this as github pages?)

### CODE REVIEW

**Comment by hbrunn** [comment]
travis error seems unrelated

**Comment by StefanRijnhart** [comment]
Thanks! Travis error is usually fixed by forcing a different commit (git commit --amend +force push). Can you give it a try?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by pedrobaeza** [comment]
Please tell me what is needed for moving this to OCA server. cc @sbidoul

**Comment by hbrunn** [comment]
you'll need python3-sphinx (it has autodoc included already) and a checkout of of latest openupgrade. Then run a cronjob that pulls it every night and runs this script. And configure the webserver to serve `/odoo/openupgrade/doc/build/html` from this checkout.

**Comment by pedrobaeza** [comment]
OK, I'm not very used on this sysadmin works, but let's see if @sbidoul can handle this.

**Comment by sbidoul** [comment]
Can't we do this with readthedocs.io (as I do for mis builder)? Or using travis to publish to github pages (as is done for connector). I'd rather avoid yet another cron on the OCA server, and give full control to projects over the publish of their docs. 

If the doc building script does not work for readthedocs, then gh pages should work.

**Comment by pedrobaeza** [comment]
No problem for me :)

**Comment by hbrunn** [comment]
I also don't mind. Who needs to do what?

**Pull request merged**
