### PR TITLE
[13.0][FIX]Product combination indices move logic from post to pre migration

### PR DESCRIPTION
**Pull request by flotho**

### CODE REVIEW

**Comment by flotho** [comment]
FIX #2983

**Comment by flotho** [comment]
ping @pedrobaeza

**Comment by flotho** [comment]
and squashed !

**Comment by pedrobaeza** [comment]
Is this superseded by #2987 ?

**Comment by flotho** [comment]
Hi @pedrobaeza , not at all, it doesn't superseed.

What I've discovered is that OpenUpgrade correctly compute the indices and put it on the product_product table.
Yet the Odoo core python logic is based on a computation (https://github.com/OCA/OpenUpgrade/blob/13.0/addons/product/models/product.py#L215) that call a many2many relation ( https://github.com/OCA/OpenUpgrade/blob/13.0/addons/product/models/product.py#L100) that doesn't exist in prior version. As a consequence during the update of the module, if the table is absent it will be created as an empty table and odoo will recompute the indices and use the many2many fields but no attribute_value_ids will be bound so that the indice computed is empty.
That's why I propose to create the table if it doesn't exist and fill it with values in the premigration so that the python logic will compute appropriate datas.
Additionally we could test the fact that if the table exists and is filled then the python logic will do its job properly and setting up the combination indices by SQL will could be irrelevant. I didn't try this for the moment.

**Comment by pedrobaeza** [comment]
Yeah, but we need clear steps to reproduce the problem for knowing the why of the change, and not based on a code reading.

**Comment by flotho** [comment]
superseeded by #3011

**Pull request closed without merging**
