### PR TITLE
[FIX] add hr_gamification in the coverage file

### PR DESCRIPTION
**Pull request by legalsylvain**
Finish #3253

CC : @pedrobaeza

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Shouldn't it be nothing to do?

**Comment by MiquelRForgeFlow** [comment]
Oh, right.

**Comment by MiquelRForgeFlow** [comment]
Also I see @legalsylvain used a branch of OCA haha

**Comment by legalsylvain** [comment]
> Also I see @legalsylvain used a branch of OCA haha

Indeed, I don't know how to select an alternative remove when making trivial PR by UI. Do you ?

thanks !

**Comment by MiquelRForgeFlow** [comment]
> when making trivial PR by UI. Do you ?

Right, when doing it by UI, the branch is created in the same remote/repo.

**Pull request merged**
