### PR TITLE
[13.0] update upstream 7cca00acacf

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
It's time.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Still red

**Comment by MiquelRForgeFlow** [comment]
FYI: It's thanks to https://github.com/OCA/OpenUpgrade/pull/3630/commits/b89b70cc196bb44c62b175f09be2961500ea79c9 that we are detecting this kind of errors.

**Comment by pedrobaeza** [comment]
That's why the guideline to include in the XML-ID a reference to the model for avoiding collapsing with the same one belonging to other models.

**Comment by MiquelRForgeFlow** [comment]
Ready

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
