### PR TITLE
[ADD] crm_phonecall: Auto-install it if present and don't convert phonecalls to logged activities

### PR DESCRIPTION
**Pull request by pedrobaeza**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@cubells please review

**Comment by pedrobaeza** [comment]
@mreficent can you please check?

**Comment by MiquelRForgeFlow** [comment]
But the `crm_phonecall` doesn't exist in v8.

**Comment by pedrobaeza** [comment]
This is not for v8, but for v9. It detects if you have the new v9 module in the module in the list (this checks happens after base update, which refresh module list), and it avoids the heavy task of converting calls to the log.

**Comment by MiquelRForgeFlow** [comment]
I don't understand. Why not put `auto_install = TRUE` in that module?

**Comment by pedrobaeza** [comment]
You don't want that module autoinstalled on a fresh v9. You do if you are migrating from v8. And not only that, you don't want that hacky and ugly way of having the calls somehow logged on the chatter if you are going to have the same features than in v8.

**Review by MiquelRForgeFlow — APPROVED** [review]
Ah, now I understand :+1:

**Comment by MiquelRForgeFlow** [comment]
Shouldn't you check if `calendar` module is already installed? I ask this because `crm_phonecall` depends on `calendar`.

**Comment by pedrobaeza** [comment]
It's a dependency of `crm`, so no problem on that.

**Pull request merged**
