### PR TITLE
[REM] Remove migrate.py

### PR DESCRIPTION
**Pull request by pedrobaeza**
After the n-th posted issue trying to migrate with this script, it's better to remove it for avoiding confusions.

cc @Tecnativa

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
```
[31;01mWarning, treated as error:[39;49;00m
/home/travis/build/OCA/OpenUpgrade/odoo/openupgrade/doc/source/index.rst:12:unknown document: migrate.py
travis_time:end:247386ea:start=1558827536367848776,finish=1558827544503906541,duration=8136057765
[0K[31;1mThe command "sh scripts/build_openupgrade_docs" exited with 2.[0m
```

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
@mreficent fixed. Merge when CI finishes

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
