### PR TITLE
[11.0][MIG] account_check_printing

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Migration scripts for `account_check_printing` module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Looks good! Can you update module coverage?

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart done!

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by StefanRijnhart** [comment]
@pedrobaeza should we use cla bot to merge PRs in this project as well? Asking because it is a different kind of project than most other OCA projects.

**Comment by pedrobaeza** [comment]
Except for update stream PRs, it seems to work well, so yes, you can use it and make sure this works on a rebased branch.

**Comment by StefanRijnhart** [comment]
OK, thanks for the info!

**Pull request merged**
