### PR TITLE
[15.0][FIX] hr_expense: fail when account_journal_lock_date

### PR DESCRIPTION
**Pull request by remytms**
Modifying account.move when module `account_journal_lock_date` is installed failed due to settings in `*_lock_date`.

```
2024-09-16 13:07:41,298 1 CRITICAL coopiteasy-upgrade odoo.service.server: Failed to initialize database `coopiteasy-upgrade`. 
Traceback (most recent call last):
  File "/odoo_env/src/odoo/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/odoo_env/src/odoo/odoo/modules/registry.py", line 88, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo_env/src/odoo/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo_env/src/odoo/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo_env/src/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/odoo_env/src/openupgrade/openupgrade_framework/odoo_patch/odoo/modules/migration.py", line 18, in migrate_module
    MigrationManager.migrate_module._original_method(self, pkg, stage)
  File "/odoo_env/src/odoo/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/opt/venv/lib/python3.8/site-packages/openupgradelib/openupgrade.py", line 2292, in wrapped_function
    func(
  File "/odoo_env/src/openupgrade/openupgrade_scripts/scripts/hr_expense/15.0.2.0/post-migration.py", line 51, in migrate
    _fill_payment_state(env)
  File "/odoo_env/src/openupgrade/openupgrade_scripts/scripts/hr_expense/15.0.2.0/post-migration.py", line 46, in _fill_payment_state
    move.payment_state = new_pmt_state
  File "/odoo_env/src/odoo/odoo/fields.py", line 1247, in __set__
    records.write({self.name: write_value})
  File "/odoo_env/src/oca/account-financial-tools/account_journal_lock_date/models/account_move.py", line 17, in write
    self._check_fiscalyear_lock_date()
  File "/odoo_env/src/oca/account-financial-tools/account_journal_lock_date/models/account_move.py", line 52, in _check_fiscalyear_lock_date
    raise UserError(message)
odoo.exceptions.UserError: You cannot add/modify entries for the journal 'Vendor Bills' prior to and inclusive of the lock date 12/31/2023
```

This propose a fix to deactivate `*_lock_date` during migration process.

I'm not sure if this process should go in this script. Advise are welcome.

Testing in progress.

### CODE REVIEW

**Comment by legalsylvain** [comment]
Sorry. I don't get it. check will be done also if the OCA module are not installed. Or did i missed something ? AFAIK, _check_lock_date is a core function.

Note: if I missed something (it's possible, I don't use this module !), maybe you can just use the context "bypass_journal_lock_date", that will disable all the checks. It will avoid all the stuff to save and restore lock dates.

**Comment by remytms** [comment]
Yes, indeed, I didn't catch the `bypass_journal_lock_date` in the context. I will use this way.

**Comment by legalsylvain** [comment]
lighter patch ! 
Could you take pre-commit ?

**Comment by pedrobaeza** [comment]
I think the module `account_journal_lock_date` is not correct not filtering out certain fields that shouldn't raise the error, like `payment_state`. The patch should be there, not here.

**Comment by remytms** [comment]
This PR may be replaced by #4577 I will test and keep you informed.

**Comment by remytms** [comment]
Closed in favor of #4577

**Pull request closed without merging**
