### PR TITLE
[14.0][MIG] im_livechat

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Migration done.

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Review by RaulOForgeFlow — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
@pedrobaeza do you know this OCA-git-bot error? 
```
The merge process could not start, because of exception 403 Must have admin access to view repository collaborators..
```

**Comment by eLBati** [comment]
https://github.com/OCA/OpenUpgrade/pull/2854#issuecomment-920090435
cc @sbidoul

**Comment by matteoopenf** [comment]
> @pedrobaeza do you know this OCA-git-bot error?
> 
> ```
> The merge process could not start, because of exception 403 Must have admin access to view repository collaborators..
> ```

https://github.community/t/github-api-collaborators-access-changed-today/201259

I found that

**Comment by sbidoul** [comment]
If GitHub does not revert that change, someone will have to change the bot permissions. PSC representatives and the board can do it. I'm on holidays till next week, so I can't do this myself.

**Comment by pedrobaeza** [comment]
I have explicitly added OCA Bot as admin. Let's see if it works:

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
It works, but such permission level is too much IMO. Let's see in the started thread in https://github.community/t/github-api-collaborators-access-changed-today/201259/4 if they change their mind.

**Comment by Yajo** [comment]
It seems this is still failing: https://github.com/OCA/social/pull/770#issuecomment-920716213

**Pull request merged**
