### PR TITLE
[WIP] Openupgrade framework

### PR DESCRIPTION
**Pull request by StefanRijnhart**
WORK IN PROGRESS

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
FYI this is the diff between current OpenUpgrade 11.0 and the latest upstream merge ec7109c9 [framework.diff.txt](https://github.com/OCA/OpenUpgrade/files/2422739/framework.diff.txt)

**Comment by pedrobaeza** [comment]
Great! I was about to ask you if you are going to do this year the initial setup. Thanks as always for this work!

**Comment by StefanRijnhart** [comment]
I'm in the middle of three go-lives, but I'll try my best to finish the port and the analysis in time for the code sprint. There is always the trainride to Belgium.

**Comment by pedrobaeza** [comment]
Wow, good luck with all. See you soon!

**Comment by StefanRijnhart** [comment]
Sorry, I pushed to the wrong branch. New attempt: https://github.com/OCA/OpenUpgrade/pull/1529

**Pull request merged**
