### PR TITLE
[MIG] account_analytic_distribution: Migration scripts

### PR DESCRIPTION
**Pull request by pedrobaeza**
cc @Tecnativa

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@StefanRijnhart check the use I have done of `sql.SQL` method from psycopg2 for building queries. It's very versatile and more secure than `AsIs`. For v13 I will use it massively.

**Comment by StefanRijnhart** [comment]
Yes, I've seen it. I think I wasn't sure if it actually prevents SQL injections when I looked into this module some time ago. Do you have info on that?

**Comment by pedrobaeza** [comment]
using `sql.Identifier()` for adding the column/table names prevents the SQL injection through a check performed on `format` method.

**Comment by StefanRijnhart** [comment]
That's great!

**Comment by pedrobaeza** [comment]
Look this snippet:
```python
>>> query = sql.SQL("SELECT * FROM {table}")
>>> env.cr.execute(query.format(table=sql.Identifier('res_partner')))  # no error
>>> env.cr.execute(query.format(table=sql.Identifier("res_partner; UPDATE res_partner SET name='x' WHERE id=1")))

ERROR: relation "res_partner; UPDATE res_partner SET name='x' WHERE id=1" does not exist
LINE 1: SELECT * FROM "res_partner; UPDATE res_partner SET name='x' ...
                      ^

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: relation "res_partner; UPDATE res_partner SET name='x' WHERE id=1" does not exist
LINE 1: SELECT * FROM "res_partner; UPDATE res_partner SET name='x' ...
```

In fact, more than a check itself, it's that it's enclosed for fully qualified query.

**Pull request merged**
