### PR TITLE
[12.0][MIG] website_quote / sale_quotation_builder

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Migration scripts for `sale_quotation_builder` module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't have any migration with this module for now, so I'm not reviewing it, but you shouldn't merged as well without any review, being a whole module with scripts.

**Comment by cvinh** [comment]
We used that PR.
It worked well.
The only thing we noticed is that the `portal_confirmation_sign`, `module_sale_quotation_builder` and the `group_sale_order_template` options in `res_config_settings` should be selected after the migration

**Comment by MiquelRForgeFlow** [comment]
@cvinh right, I didn't take into account the settings! Now I updated the PR with the settings update for sale_payment, sale_order_dates and website_quote. Can you check again?

**Comment by MiquelRForgeFlow** [comment]
@cvinh @pedrobaeza fixed minor things. Ready to review and merge! 🤓🙏 

Make sure you have updated `openupgradelib` to last commit in https://github.com/OCA/openupgradelib!!

**Comment by MiquelRForgeFlow** [comment]
@cvinh please, can you check again?

**Comment by thinkwelltwd** [comment]
Would be glad if this could get merged soon.

**Comment by pedrobaeza** [comment]
Merging blindly the part of `website_quote`, but the other commit seems OK.

**Pull request merged**
