### PR TITLE
8.0 'delivery' (onesteinbv)

### PR DESCRIPTION
**Pull request by legalsylvain**
Port 'delivery' modification realized by OneStein BV. (branch onesteinbv:8.0-os)

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Where are the notes on analysis file?

**Comment by pankk** [comment]
Sorry, it seems the notes for this were not created when we worked on this.

**Comment by pedrobaeza** [comment]
Please include it to see if all is correct.

BTW, I want to take the occassion to thank you for the huge work you have done.

**Comment by StefanRijnhart** [comment]
Second that! And high quality work as well. Thanks indeed.

**Comment by pedrobaeza** [comment]
I have checked it this migration script and there's nothing to do, because sequence value is assigned by default, so I have updated PR and create the corresponding analysis work file.

**Comment by StefanRijnhart** [comment]
Thanks @pedrobaeza, :+1:

**Pull request merged**
