### PR TITLE
[13.0] Merge base_vat_sanitized with base_vat

### PR DESCRIPTION
**Pull request by rconjour**
[13.0] Merge base_vat_sanitized with base_vat

See description: https://github.com/OCA/partner-contact/tree/13.0/base_vat_sanitized

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
In which conditions the sanitized vat is written in the same vat field? I can't reproduce such conditions.

**Comment by rconjour** [comment]
@pedrobaeza it is possible to have databases where the `vat` field is not sanitized, and the vat_sanitized is filled, so it would be appropiate to move the value of `vat_sanitized` to the vat field since we merge `base_vat_sanitized` with `base_vat`

**Comment by pedrobaeza** [comment]
Yeah, but the merge makes sense if Odoo now sanitizes the field. If not, `base_vat_sanitized` is still needed.

**Comment by rconjour** [comment]
Odoo sanitizes the field in `_fix_vat_number()`: https://github.com/odoo/odoo/blob/9ebc6f2bfd9868398bb55bb782338beab9afcb2e/addons/base_vat/models/res_partner.py#L466-L474

This function is triggered on the create and write of a partner:
https://github.com/odoo/odoo/blob/9ebc6f2bfd9868398bb55bb782338beab9afcb2e/addons/base_vat/models/res_partner.py#L480
https://github.com/odoo/odoo/blob/9ebc6f2bfd9868398bb55bb782338beab9afcb2e/addons/base_vat/models/res_partner.py#L486

**Comment by pedrobaeza** [comment]
Yeah, you are right. Thanks for the insights. The problem is that there's an issue with such sanitizing:

https://github.com/odoo/odoo/issues/69333

but the merge (and deprecation of the other module) is correct.

**Pull request merged**
