### PR TITLE
[11.0][MIG] mail

### PR DESCRIPTION
**Pull request by kaerdsar**
+ Moved data from notify_email to notification_type in users
+ Update binding_model_id in mail template action windows 
+ Added noupdate changes for ir.cron records

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thanks! Would be good to rebase after https://github.com/OCA/OpenUpgrade/pull/1121 so that we can check the Travis result.

**Comment by StefanRijnhart** [comment]
I mean rebase once #1121 is merged...

**Comment by StefanRijnhart** [comment]
#1121 now merged. Can you rebase onto the updated 11.0 branch so that we can check the test run on travis?

**Comment by StefanRijnhart** [comment]
Or actually, I can just restart Travis...

**Comment by StefanRijnhart** [comment]
Or no, I can't because travis was never run for this branch.

**Comment by pedrobaeza** [comment]
Closing and reopening to see if it launches a Travis rebuild

**Comment by pedrobaeza** [comment]
Travis is now green. I haven't followed these PRs yet, so @StefanRijnhart should say if it can be merged.

**Comment by StefanRijnhart** [comment]
@pedrobaeza I'm a little confused now. This branch does not have travis config but travis stil runs. Except that the mail migration is not actually run. How about a proper rebase @kaerdsar?

**Comment by pedrobaeza** [comment]
hehe, yeah, it's strange then. I have just restarted Travis without looking at it. A rebase is always recommended indeed.

**Comment by kaerdsar** [comment]
@StefanRijnhart I updated the code but something is failing in the coverage. I'm not sure why, maybe is because dependencies bus and web_tour are still not migrated. Do you have any idea?

**Comment by StefanRijnhart** [comment]
Small changes in coverage can always occur, no problem. Thanks for the update!

**Comment by StefanRijnhart** [comment]
Merging as Travis is green with mail migration being run.

**Pull request merged**
