### PR TITLE
[14.0][IMP] ir_attachment: binary_conversion_for_db_attachments

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
In versions of Odoo prior to 14, attachments stored in the database were kept as base64-encoded data. However, starting from Odoo 14, these attachments are maintained as binary data, and only encoded to base64 within the _compute_datas method for the datas field. Therefore, when migrating from version 13 to 14 with attachments stored in the database, these attachments may not display properly within their respective records.

@qrtl

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please point to the relevant pieces of code in Odoo v13 and v14 where it's shown this change?

**Comment by AungKoKoLin1997** [comment]
> Can you please point to the relevant pieces of code in Odoo v13 and v14 where it's shown this change?

In odoo13, [this line](https://github.com/odoo/odoo/blob/e6d1a7531dc02601eca7d704134990896ed493d4/odoo/addons/base/models/ir_attachment.py#L534) will store the `db_datas` with base64-encoded data. In odoo14, [this line](https://github.com/odoo/odoo/blob/652fb88281f4d3659c3203716dc3b75bd4789089/odoo/addons/base/models/ir_attachment.py#L611-L614) use decoded data to store.

**Comment by pedrobaeza** [comment]
Thanks for the pointer. Correct me if I'm wrong, this is only preprocessing the dictionary in the `create` method, but that's independent on how this actual serialize in the DB. And this also only seen to be a problem if you store attachments in the DB, which is not the default since a lot. Is that the case?

**Comment by AungKoKoLin1997** [comment]
Yes. You are right.

**Comment by pedrobaeza** [comment]
In which thing am I right?

**Comment by AungKoKoLin1997** [comment]
I mean this is preprocessing  on `create` method. It will not depend on database and use the same column type `bytea` that can be solve bytes and base64-encoded data in v13 and v14.

**Comment by pedrobaeza** [comment]
Yeah, but I think this is only to adapt data in ORM layer, but on DB storage, the result is the same. I let others to review this, as I don't know this part very deep.

**Review by MiquelRForgeFlow — APPROVED** [review]
Makes sense to me. The change was done in https://github.com/odoo/odoo/commit/172722c4d229063ba964095df5bcfadc25ba65c9 and obviously the OU analysis didn't catch it.

**Comment by AungKoKoLin1997** [comment]
@OpenUpgrade-maintainers
Is it possible to review this PR?

**Pull request merged**
