### PR TITLE
[ADD] product_variant_supplierinfo: Merged in product

### PR DESCRIPTION
**Pull request by pedrobaeza**
Odoo core now manages vendors for variants in core.

@Tecnativa

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Does the data model of the OCA module correspond one on one with the Odoo functionality?

**Comment by pedrobaeza** [comment]
Yes, there's only a new field in product.supplierinfo: `product_id`, that it's now on core (in fact, it was in v10, but without use). The rest were tricks for making it work. You can check it in https://github.com/OCA/product-variant/tree/10.0/product_variant_supplierinfo/models

**Comment by pedrobaeza** [comment]
OK to go?

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Pull request merged**
