### PR TITLE
select remote modules for install

### PR DESCRIPTION
**Pull request by ferdiga**
mark all uninstalled modules for installation - based on the modules installed on a remote db

how can I remove the openupgrade_analysis.txt from the pull request ?

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Thanks! I can see this being useful. Just remove the extra lines in the analysis file and commit that, it will show up with no change here, I suppose.

Can you use map module names using renamed_modules in openupgrade_records/lib/apriory.py, and remove your initials in l.124?

**Comment by ferdiga** [comment]
fixed

**Comment by StefanRijnhart** [comment]
LGTM :+1:

**Comment by legalsylvain** [comment]
LGTM :+1:

**Pull request merged**
