### PR TITLE
[11.0][MIG] web_kanban_gauge migration

### PR DESCRIPTION
**Pull request by fayezqandeel**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@fayezqandeel, when you create new branches, you should create them from origin/11.0. If not, it happens that in each new branch you are accumulating all commits from previous branches.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please clean the branch. Each time you switch to a new development, you need first to checkout to the main branch, and then create the new branch:
```
git checkout 11.0
git checkout -b migration_web_kanban_gauge
```

**Comment by pedrobaeza** [comment]
This branch has the same problem with extra commits.

**Comment by fayezqandeel** [comment]
@pedrobaeza  extra commits removed

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
