### PR TITLE
[9.0][FIX] Don't (also) insert child taxes as parent taxes

### PR DESCRIPTION
**Pull request by StefanRijnhart**
After using OpenUpgrade 9.0, parent-child relationship between account.tax records are perfectly circular. There was code to populate the many2many tables in the correct way and code to populate them the wrong way around.

Trying to update the taxes in the UI raises a recursion error.

image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Test `addons/account/migrations/9.0.1.1/tests/test_product_property.py` is broken, just like in the previous merge from the 28th of November. In the merge before that, on 26th of October 2020, the test succeeded. I don't see any relevant changes in those PRs or in OpenUpgradelib for that matter. I'll come back to this.

**Review by legalsylvain — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM, it's that kind of "common sense" PR

**Comment by StefanRijnhart** [comment]
The field from the test was renamed twice, which became a problem after this fix in openupgradelib through one of @pedrobaeza's direct commits (or rather 3: https://github.com/OCA/openupgradelib/commits/01e27a9). I'm proposing an improvement here: https://github.com/OCA/openupgradelib/pull/227. I like to think that someone would have suggested somethig like this if the original change had gone through a proper PR but maybe that's wishful thinking.

I'm fixing the programming error of renaming the field twice in the second commit in this PR.

**Comment by StefanRijnhart** [comment]
Also, this should be an encouragement for all of us to write some migration tests sometimes.

**Comment by hbrunn** [comment]
@StefanRijnhart thank you for the fix. @pedrobaeza I share Stefan's concern that you sidestep the process in your effort to move on fast. Can we start a discussion how to combine speed and reviews? If used sparsely, I could do priority reviews when tagged a certain string or some other filter

**Comment by pedrobaeza** [comment]
Don't want to be in a defensive way, but honestly would you anticipate these things through a PR in openupgradelib? If you see dates, that was done on a Saturday, performing a migration, and due to the "fragmentation" of things (Python library, OCA modules, OpenUpgrade), preparing an environment for the temporary pull requests does things harder, and more when this was something already detected in the past (see #2339). The commits are well documented about the whys and the how.

Sorry for the extra time you have needed for this PR that is unrelated to what you are contributing. If you have suspected in any moment that is due to that, you can tell me and I will spend the needed time for fixing it. You know I'm responsible with any of my actions.

Said that, `rename_property` is doing only half of the operations needed on a renaming (no export profiles adjustment, no filters change, etc). What was the original error or calling both? Maybe we can call `rename_property` from `rename_fields` if we detect that is a property.

**Comment by StefanRijnhart** [comment]
The error was that the original method to rename properties (like the one from openupgradelib) renames the ir_model_fields. Then, `openupgradelib.rename_fields`, which also renames the ir_model_fields, was called on all fields from the module including the property fields. As of the 5th of December, this method is no longer reentrant. The ir_model_fields of the new field was found to exist and was deleted, removing entries from ir_property with it as per cascade.

Agreed that the `rename_property` method is lacking. I've adapted my second commit here so that `rename_fields` can still be called.

I regularly use a custom openupgradelib when I need an unmerged bugfix by installing it from my own fork so I don't see how production pressure should allow unreviewed changes, although I agree with you that this issue might not have been picked up in any review.

**Comment by StefanRijnhart** [comment]
I'm removing the second commit, which fixes the way that properties from the account module are renamed as it's a very hairy issue in itself. I'm working on a fix for that separately.  I think it would be wise not to run a final migration using openupgrade 9.0 until the field renaming issue is fixed.

**Comment by pedrobaeza** [comment]
@StefanRijnhart I have migrated a v8 database to v9 with current main branch code without problems. Why is this failing though?

**Comment by StefanRijnhart** [comment]
This PR fails in Travis because of the terrible situation with the ir.property records that are currently being dropped due to the change in `rename_fields`. That can only be fixed properly by fixing the way that Odoo 9, 10 and 11 treat ir.model.fields and their ir.model.data entries when loading databases (I'm actively working on that, but evenings only. See https://github.com/OCA/OpenUpgrade/pull/2535 for what that is going to look like in 9.0). 
So you might have lost your product account settings. And you will have circular tax hierarchy but that is only a problem when you edit certain values of the taxes in the UI (e.g. when you change the order of the child taxes).

**Comment by StefanRijnhart** [comment]
I would feel much better if we could agree to revert those commits from 5th of december in openupgradelib (in the mean time). That would give an error migrating from 8.0 to 13.0 but the workaround is to remove the notified_partner_ids field entry and its ir_model_data entry manually before executing the 13.0 migration.

**Comment by StefanRijnhart** [comment]
https://github.com/OCA/openupgradelib/pull/229 made this PR green, so with three approvals I'm merging.

**Comment by pedrobaeza** [comment]
@StefanRijnhart do you have any query for fixing the problem on migrated DBs with the previous code?

**Comment by StefanRijnhart** [comment]
That would be
```
delete from account_tax_filiation_rel rel
where exists(
    select * from account_tax at
    where at.id = rel.parent_tax and at.parent_id = rel.child_tax);
```

**Comment by pedrobaeza** [comment]
Thank you very much! Very helpful.

**Pull request merged**
