### PR TITLE
[17.0][OU] New analysis

### PR DESCRIPTION
**Pull request by royle-vietnam**
It solves the problems found in [#4042](https://github.com/OCA/OpenUpgrade/pull/4294):
- the most constraints still exist but are considered deleted

With latest changes in Odoo.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
> It solves the problems found in https://github.com/OCA/OpenUpgrade/pull/4294:

I think this link is wrong. Could you link correctly to where the problem of constraints is mentioned?

**Comment by StefanRijnhart** [comment]
Thanks, changes are looking good. Do you have a fix on upgrade_analysis to arrive to these results?

**Comment by pedrobaeza** [comment]
Isn't this simply a result of changes upstream in Odoo since the release?

**Comment by StefanRijnhart** [comment]
Ah yes, it must be this one: https://github.com/odoo/odoo/commit/b278241a719264

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
