### PR TITLE
Planned migration scripts by ONESTEiN

### PR DESCRIPTION
**Pull request by diellenne**
Added migration scripts for the modules:
- account
- delivery
- mrp
- procurement
- sale
- sale_stock
- stock
- portal
- portal_sale
- purchase

### CODE REVIEW

**Comment by plaes** [comment]
:+1: 

I have tested it on my data and works fine, though it has some minor issues that can be handled by extra fixes:
1. The **mrp**'s `domain` fixup misses one entry where `context = {'default_product_tmpl_id': active_id, 'search_default_product_tmpl_id': active_id}`
2. seems like `product_template.supply_method` = `produce` is not handled at all:

```
 supply_method | procure_method 
---------------+----------------
 buy           | make_to_order
 buy           | make_to_stock
 produce       | make_to_stock
```

**Comment by diellenne** [comment]
@plaes Thank you, we are going to handle these issues ASAP! If you want and you already have an idea about how to fix them you can fork our repository (https://github.com/onesteinbv/OpenUpgrade) and make a pull request with the fixes directly on that...we will be very happy to accept your contribution!

**Comment by plaes** [comment]
@diellenne  Opened pull request which contains commits to both issues in your fork.

**Comment by StefanRijnhart** [comment]
Hi @diellenne, thank you for working on this! You have contributed scripts for a lot of modules, and at least one change in the framework. If we do a full review on this, it will be very complicated to do the review in the first place, and to follow the discussion thread on all the separate issues.

In order to make your contributions reviewable, can you resubmit with separate pull requests for each module and framework improvement/

**Comment by plaes** [comment]
@StefanRijnhart Is it really needed to split this pull request into separate modules?

At least two separate bodies (me, and people from Onestein) have gone over this code for number of times. I have used this code to migrate live data and fixed most of the issues that users have spotted.
Besides, most of the modules here are really intertwined and depend on eachother.

Also, the odoo that's bundled in OpenUpgrade should be migrated to 8.0 first, which would allow us to remove some of the hacks that are used here:
- https://github.com/onesteinbv/OpenUpgrade/commit/ac321bdc71c71ffb3ef0872b8bf567436ad8bb65
- https://github.com/onesteinbv/OpenUpgrade/commit/9bb561fb56a16fb70175008e4fa3892cea8efeb2

**Comment by StefanRijnhart** [comment]
@plaes Yes please. I am a firm believer in the idea that code review is instructive for submitters and reviewers alike. It is a way to enhance collaboration and code quality, and to share knowledge. Therefore, the code should be submitted in a way that is accessible to the reviewers.

**Comment by diellenne** [comment]
Ok. Actually we are doing the backporting of the new modification on our fork. As soon as possible we will reorganize our branches and we will submit our modification in separate pull requests. I don't think it will be possible to create a new branch and a new pull request for each module because (as @plaes already said) most of them are really depending each other but I will try to divide our work as much as possible to make it more easy to be reviewed.

**Comment by pedrobaeza** [comment]
Hi, @diellenne, you can provide PRs for the changes on the framework, and then make one PR for each module, also containing these changes in the framework as a stacked commit.

Regards.

**Comment by legalsylvain** [comment]
Hi @diellenne, 
We planned to do a workshop on OpenUpgrade the next. (At the French Python Conference) (http://www.pycon.fr/2014/)

I would like to work on your PR. If you didn't worked yet to split it, do you want I help you. Can we work together on that ?

Regards.

**Comment by diellenne** [comment]
Hi @legalsylvain,
we will be really happy to accept your help to speed up the review activity.

This afternoon we are going to backport the last modification made on the official OpenUpgrade project and test them together with our work. Actually I didn't decide yet which approach to use for reorganizing the branches of our OpenUpgrade project. For now I was thinking to act in this way:
- close this pull request
- move our work that actually is on branch 8.0  on a new one
- realign branch 8.0 to the official one and use this as basis to create different branches to submit the pull requests to the community.

What do you think about this and in which way do you suggest to collaborate in the split of this pull request?

Gr,
D

**Comment by legalsylvain** [comment]
Hi, 
Yes closing this PR is a good idea. For the rest:
You have worked on a lot of modules:
- delivery, mail, mrp, portal, portal_sale, procurement, product, project_issue, purchase, sale_stock, stock, base
  You have changed somethings in OpenUpgrade Core:
- openupgrade

Idealy: We have to realize a PR by item. 
- In your onesteinbv fork, create a new branch named '8.0_module_xxx'; 
- Past in your xxx addons, the 2 or 3 files updated;
- Git add / Commit / push and realize a PR for the xxx migration";

In that way, 
- little PR will be reviewed and merged very quickly. (like delivery for example, or the core of openupgrade);
- big PR (stock I guess) can wait a little more and we can ask help for people that well know stock changes;

Before that:
- Are you sure that your work is stable ?
  Once your PR split, if you continue to work on you big branche, you'll have to update your X branches manually. It will be a mess for you.
- Did you upgraded a production database successfully ? or when did you planned to do it ?

Regards.

Note: If you have not the time to do that work, I can do it the next week.
remarks: can you remove some 'onestein' references in your PR ?
(addons/stock/migrations/8.0.1.1/openupgrade_analysis_work_onestein.txt, for exemple)

**Comment by diellenne** [comment]
Hi,

ok, I was thinking to work exactly in that way :+1:...this morning I started to reorganize the structure of our project and when the merging of all our work will be over we will keep working in this way (working on small branches and making PR from them).
We want to keep using our new 'big branch' 8.0-os not for active development but just because, until we will not be members of the main OpenUpgrade project, we want to have a stable OpenUpgrade version containing all our improvements irrespective of whether these have been already been approved and merged in the main project.

I'm gonna close the PR now. Yesterday we made the backport of the last modification on our fork: we tested it internally and everything seems to be ok (you can also see that there are no more conflicts). 

For the splitting we will start with it tomorrow or on Monday and we hope to finish everything during the next week...if we want to work together on it just discuss how to do it in an efficient way.

To answer to the rest of your questions:
- when it is possible and all the installed modules are covered we started to use it for production databases and is working pretty good;
- sorry, the _onestein_ files are our internal files...should be removed long time ago. We  are going to remove/rename it before the new pull requests.

Gr,
D

**Comment by legalsylvain** [comment]
Hi, 

Good news. Just about your "main branch", maybe it could be possible to:
- split your big PR into litlle PRs;
- create a new branch "my_pending_work", and just merge the litlles PRs into the big one;

In that way, you have not to duplicate your work; If you want to change something, just do it in the current little PR, and after just sync your main branch. 

(just an idea).

Regards.

**Comment by diellenne** [comment]
Closing the pull request to start the reorganization of ONESTEiN BV Fork. All the modification related with this PR will be proposed again by several small PR in order to be reviewed in a more easily way.

**Comment by StefanRijnhart** [comment]
@dielenne just wanted to say that your cooperation is much appreciated!

**Pull request closed without merging**
