### PR TITLE
[IMP] set_defaults: Don't use ORM by default. Fixes #328

### LINKED ISSUE #328: set_defaults write values with ORM instead of SQL
I'm having very slow performance when migrating a DB with a lot of partners and I ended up finding that this method is the guilty of that.

@StefanRijnhart, I think you wrote this one. Is there any reason to use ORM in it instead of SQL?

### PR DESCRIPTION
**Pull request by pedrobaeza**
When merged, I will cherry-pick for 8.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We will also gain performance for sure (as the ORM write was done record by record).

**Comment by paulius-sladkevicius** [comment]
Great improvement! :+1:

**Comment by hbrunn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Thanks for the merging, although we have to concentrate now on merging https://github.com/OCA/OpenUpgrade/pull/342 and its version variants to avoid duplicating effort, and I will need to submit again this improvement to openupgradelib.

**Comment by pedrobaeza** [comment]
PR against openupgradelib made on https://github.com/OCA/openupgradelib/pull/4

**Pull request merged**
