### PR TITLE
[9.0] account_auto_fy_sequence migration integrated in account

### PR DESCRIPTION
**Pull request by pedrobaeza**
WIP until https://github.com/OCA/openupgradelib/pull/63 is merged

As now Odoo implements a feature for having several sequence numbers  per date range, we don't need anymore this module. This handles a smooth  transition from v8 having it installed to v9 properly configured and  without the module.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@sbidoul, you would be interested in this one

**Comment by hbrunn** [comment]
those look bad: https://travis-ci.org/OCA/OpenUpgrade/builds/186196710#L277-L282

**Comment by pedrobaeza** [comment]
Yeah, I haven't pushed latest version with that fixed as this is WIP. https://github.com/OCA/openupgradelib/pull/63 blocks me from removing the label.

**Comment by pedrobaeza** [comment]
Dependency merged, problem fixed and Travis green, so merging.

**Pull request merged**
