### PR TITLE
[13.0][OU-FIX] mass_mailing: update mailing_domain

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Updating mailing_domain filter.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Comment by pedrobaeza** [comment]
This seems very specific, as this field renaming is one of a lot. A better approach is to include this as part of the `rename_fields` method in openupgradelib.

Anyway, I would say that this is not even correct, as previous field was boolean, and the new one is an integer.

**Comment by MiquelRForgeFlow** [comment]
> A better approach is to include this as part of the rename_fields method in openupgradelib.

how? :S

**Comment by StefanRijnhart** [comment]
Ouch I did not think about the field type. That would leave the domain invalid even after this update.

And rename_fields would not have helped as it is not called on the change from supplier to supplier_rank (for the same reason that the type is different I imagine).

**Comment by StefanRijnhart** [comment]
Not sure what such domains look like but maybe you can try to deserialize into a list and replace by member? Maybe do that in the module that defines these fields in case mass_mailing is installed? And maybe do that for other domains as well?

**Comment by MiquelRForgeFlow** [comment]
I don't see the problem. If in that domain you have "`... ('customer', '=', True) ...`", and you change that by "`... ('customer_rank', '=', True) ...`", then it's still valid, right? I mean, you don't bother if customer_rank is 1, 2 or any value. You only care that it's not 0.

**Comment by pedrobaeza** [comment]
@MiquelRForgeFlow tell that to the ORM, who is the one that should allow that. I don't know right now if it won't fail.

Anyway, I still insist this is very specific, and that domain is not a default that is added by the module (as we needed in v12). I wouldn't go for this here.

About `rename_fields`, you can add to the routines of the renamings to search into this field if the table and column exists. I know that this doesn't work for this specific change, but it's a good improvement for the rest and for avoiding support tickets after migration.

**Comment by StefanRijnhart** [comment]
Odoo itself uses [('supplier_rank','>', 0)]. It seems wise to adhere to that or it will bite some people later on when they start assigning negative ranking (using it as some kind of credit score).

**Comment by MiquelRForgeFlow** [comment]
> Maybe do that in the module that defines these fields in case mass_mailing is installed?

Why? I think the good logic is doing it here in mass_mailing, that's where the field you are modifying is.

> And maybe do that for other domains as well?

Which other domains? If there are others in other modules, then we should attend them in their corresponding modules.

> or it will bite some people later on when they start assigning negative ranking

But negative values don't make sense. This ranks values are counting things. Always.

> tell that to the ORM

What? that doesn't fail. integer ~ boolean comparison don't give errors.

> this is very specific

Yeah, that's a bit true. I can close the PR if you want and use the branch as my custom code, no problem.

**Comment by MiquelRForgeFlow** [comment]
Added in my docker =)

**Pull request closed without merging**
