### PR TITLE
[13.0][OU-IMP] account: Empty move partner on regular entries

### PR DESCRIPTION
**Pull request by pedrobaeza**
On pre-v13, account.move>partner_id was a related stored field that pointed to the first partner found on lines, but now on v13, this field points only to the partner of the invoices, being empty when you fill a regular entry.

For consistency, and also for avoiding problems like duplicating a journal entry, change the parter on the lines, and get a different
partner on header vs lines, we should empty the partner in all the existing regular entries.

@Tecnativa TT38085

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
Not really sure, but seems ok. Go on.

**Comment by MiquelRForgeFlow** [comment]
Shouldn't be better to do a copy_column in pre for this field?

**Comment by pedrobaeza** [comment]
Isn't my explanation clear enough?

**Comment by pedrobaeza** [comment]
> Shouldn't be better to do a copy_column in pre for this field?

Preserving such data is useless, as it's the first partner found on lines. We are not destructing information.

**Comment by MiquelRForgeFlow** [comment]
No. My concern is for migration issues, maybe some other modules that depends on `account` need this partner_id info for some script or related field.

**Comment by MiquelRForgeFlow** [comment]
> We are not destructing information.

Ah, ok :+1:

**Pull request merged**
