### PR TITLE
[ADD] reset window actions context (contains project_id)

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I remember this bug because data is not reset when there are omitted values...

:+1:

**Comment by StefanRijnhart** [comment]
This is usually detected by the compare xml script, but it seems that in this case the context was set in portal_project_issue (can't seem to find a context here : https://github.com/odoo/odoo/blob/8.0/addons/project_issue/project_issue_menu.xml#L8)

**Comment by StefanRijnhart** [comment]
Ah, this is 7.0. That explains.

**Comment by hbrunn** [comment]
yes, that's meant to get rid of https://github.com/odoo/odoo/blob/6.1/addons/project_issue/project_issue_menu.xml#L14

**Pull request merged**
