### PR TITLE
[16.0][OU-ADD] sale_margin: Nothing to do

### PR DESCRIPTION
**Pull request by diamondnguyenkc**
Nothing to do

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration sale_margin

<dependency></dependency>

**Review by victoralmau — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
Thanks.

/ocabot merge nobump

**Review by flotho — APPROVED** [review]
LGTM

**Pull request merged**
