### PR TITLE
[10.0][FIX] procurement: Delete company view

### PR DESCRIPTION
**Pull request by rousseldenis**
Related to https://github.com/OCA/maintainer-tools/issues/390

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza

**Comment by MiquelRForgeFlow** [comment]
Why?

**Comment by rousseldenis** [comment]
See above.

**Comment by MiquelRForgeFlow** [comment]
OMG, I didn't see before  😅

**Comment by MiquelRForgeFlow** [comment]
Have you tested it in a test migration?

**Comment by rousseldenis** [comment]
Not yet.

**Comment by StefanRijnhart** [comment]
It is not entirely clear to me what the problem is with breaking views during migration. The errors are supposed to be disarmed by changes that we make in OpenUpgrade so that they don't interrupt the migration. In the migration post processing, Odoo deletes the views that are no longer present in the module such as this one (unless it is defined as noupdate). What problems causes this view exactly?

**Comment by rousseldenis** [comment]
Yes. False positive. Happens without Open upgrade. Closing

**Comment by StefanRijnhart** [comment]
OK, thanks for the followup!

**Pull request closed without merging**
