### PR TITLE
[16.0][MIG] digest: Nothing to do

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You have to load the noupdate_changes.xml file and delete translations (if applicable), although right now with new translation system, it should be checked how it works.

**Comment by legalsylvain** [comment]
Hi @marielejeune. Could you apply the change suggested by @pedrobaeza. 

See : https://oca.github.io/OpenUpgrade/use_cases/noupdate_xml_entry_changed.html
and : https://oca.github.io/OpenUpgrade/use_cases/noupdate_xml_entry_changed.html#notes (for the translation part)

thanks !

**Comment by marielejeune** [comment]
Hi @legalsylvain, done.
I'm not sure however what to do with templates `digest_mail_layout` and `digest_section_mobile`. I don't think they are translated?

**Comment by MiquelRForgeFlow** [comment]
> Hi @legalsylvain, done. I'm not sure however what to do with templates `digest_mail_layout` and `digest_section_mobile`. I don't think they are translated?

`digest_mail_layout` doesn't seem to have "translatable text", but `digest_section_mobile` has it. I would put both in the _translations_to_delete list.

**Comment by marielejeune** [comment]
@MiquelRForgeFlow thanks, done

**Comment by legalsylvain** [comment]
@pedrobaeza : could you update your review ? 
Merging this PR will unblock a lot of PRs.

**Review by pedrobaeza — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
Thanks @marielejeune !

/ocabot merge nobump

**Comment by legalsylvain** [comment]
CI is red. Looks related to https://github.com/OCA/openupgradelib/pull/335. Rebasing

/ocabot rebase

**Comment by legalsylvain** [comment]
@MiquelRForgeFlow @duong77476  it look like the function delete_record_translations changed in https://github.com/OCA/openupgradelib/pull/328  and https://github.com/OCA/openupgradelib/pull/335 is failing.
Could you take a look ?

```
   File "/home/runner/work/OpenUpgrade/OpenUpgrade/openupgrade/openupgrade_scripts/scripts/digest/16.0.1.1/post-migration.py", line 20, in migrate
    openupgrade.delete_record_translations(env.cr, "digest", _translations_to_delete)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openupgradelib/openupgrade.py", line 2696, in delete_record_translations
    logged_query(cr, query, (record_id,))
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openupgradelib/openupgrade.py", line 1681, in logged_query
    cr.execute(query, args)
  File "/home/runner/work/OpenUpgrade/OpenUpgrade/odoo/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.FeatureNotSupported: source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression
LINE 3:                 SET (name) = (jsonb_build_object('en_US', na...
```

**Comment by daiduongnguyen-odoo** [comment]
> @MiquelRForgeFlow @duong77476 it look like the function delete_record_translations changed in [OCA/openupgradelib#328](https://github.com/OCA/openupgradelib/pull/328) and [OCA/openupgradelib#335](https://github.com/OCA/openupgradelib/pull/335) is failing. Could you take a look ?
> 
> ```
>    File "/home/runner/work/OpenUpgrade/OpenUpgrade/openupgrade/openupgrade_scripts/scripts/digest/16.0.1.1/post-migration.py", line 20, in migrate
>     openupgrade.delete_record_translations(env.cr, "digest", _translations_to_delete)
>   File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openupgradelib/openupgrade.py", line 2696, in delete_record_translations
>     logged_query(cr, query, (record_id,))
>   File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/openupgradelib/openupgrade.py", line 1681, in logged_query
>     cr.execute(query, args)
>   File "/home/runner/work/OpenUpgrade/OpenUpgrade/odoo/odoo/sql_db.py", line 321, in execute
>     res = self._obj.execute(query, params)
> psycopg2.errors.FeatureNotSupported: source for a multiple-column UPDATE item must be a sub-SELECT or ROW() expression
> LINE 3:                 SET (name) = (jsonb_build_object('en_US', na...
> ```

Working on it at https://github.com/OCA/openupgradelib/pull/337, already test by check out with this PR

**Comment by legalsylvain** [comment]
Thanks @duong77476 !

**Pull request merged**
