### PR TITLE
[FIX] ensure an email for admin to have valid message_posts during

### PR DESCRIPTION
**Pull request by hbrunn**
migration

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I understand then that `mail.catchall.domain` is used in all parts when mail is needed? If not, you should write that value to admin email, or take also the default one.

**Comment by hbrunn** [comment]
It's either an email address or the alias: https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/addons/mail/mail_message.py#L171 - and the alias domain comes from this parameter: https://github.com/OpenUpgrade/OpenUpgrade/blob/8.0/addons/mail/mail_alias.py#L62

**Comment by pedrobaeza** [comment]
Thanks for the explanation!

:+1:

**Comment by StefanRijnhart** [comment]
Can you add a log entry when the email is set?

**Comment by hbrunn** [comment]
done

**Comment by StefanRijnhart** [comment]
Grand, thanks. :+1:

**Pull request merged**
