### PR TITLE
[IMP] purchase: Compute fields through SQL

### PR DESCRIPTION
**Pull request by pedrobaeza**
This saves a lot of time.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This one is ready to review. I have introduced in this version the same hack that @NL66278 put for v9 for blacklisting fields to recompute in order to get columns/m2m tables created by ORM, but compute fields by SQL.

**Review by MiquelRForgeFlow — APPROVED** [review]
But I don't like this kind of blacklist hack

**Comment by pedrobaeza** [comment]
> But I don't like this kind of blacklist hack

Why not? I have got to it because on many2many fields, there are a lot of SQL operations for getting the exact result as with ORM: create tables, indexes, foreign keys, comments... And at the end, it's better to simply not recomputing records.

**Review by StefanRijnhart — APPROVED** [review]
Thank you. Openupgrade needs this kind of code to become performant.

**Pull request merged**
