### PR TITLE
[16.0][OU-ADD] stock_picking_batch: nothing to do

### PR DESCRIPTION
**Pull request by carmenbianca**
Nothing to do.

Depends on #3966

### CODE REVIEW

**Comment by carmenbianca** [comment]
/ocabot migration stock_picking_batch

<dependency></dependency>

**Comment by pedrobaeza** [comment]
@carmenbianca do you agree to switch to #4501 with a more detailed work file?

**Comment by carmenbianca** [comment]
@pedrobaeza of course!

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request closed without merging**
