### PR TITLE
[OU-ADD] pos_restaurant : Nothing to do

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial.

### CODE REVIEW

**Review by remytms — APPROVED** [review]
LGTM

**Review by zamberjo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Aborted as the dependencies are not merged.

**Comment by legalsylvain** [comment]
> Aborted as the dependencies are not merged.

I don't get it :  
- The dependency is point_of_sale : 

https://github.com/odoo/odoo/blob/15.0/addons/pos_restaurant/__manifest__.py#L19

- point_of_sale is done : 

https://github.com/OCA/OpenUpgrade/blob/15.0/docsource/modules140-150.rst

Could you elaborate ?

**Comment by pedrobaeza** [comment]
Oh, sorry, my fault. I didn't see that is 15.0, not 16.0. Anyway, please put the version in the PR title (but not commit message).

Merging.

**Pull request merged**
