### PR TITLE
[15.0][OU-FIX] website: website update website form call

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
Script to update website views containing calls to "/website_form/" to "/website/form/".

cc @Tecnativa TT43689

@chienandalu please review

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Thanks :)

**Comment by pilarvargas-tecnativa** [comment]
please @pedrobaeza can you review?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please change tag from `[OU-ADD]` to `[OU-FIX]`. This is not adding a new migration script, but modifying an existing one for a thing that should be fixed.

**Comment by pilarvargas-tecnativa** [comment]
> Please change tag from `[OU-ADD]` to `[OU-FIX]`. This is not adding a new migration script, but modifying an existing one for a thing that should be fixed.

all right, thanks!

**Pull request merged**
