### PR TITLE
[16.0][OU-ADD] sale_expense: apply noupdate changes

### PR DESCRIPTION
**Pull request by robinkeunen**
superseeds https://github.com/OCA/OpenUpgrade/pull/4030

Blocked by dependency

### CODE REVIEW

**Review by remytms — APPROVED** [review]
LGTM

**Review by victoralmau — APPROVED** [review]

**Comment by andreampiovesana** [comment]
merge?

**Comment by pedrobaeza** [comment]
I think it's too risky to change the policies of the existing products. It's OK to have that new defaults in a fresh v16 DB, but not to switch them when coming from v15, as they will behave different when migrating. Please comment the content on the noupdate_changes.xml file including these reflections.

**Comment by marielejeune** [comment]
Hi @robinkeunen, do you plan to apply Pedro's suggestion?

**Comment by robinkeunen** [comment]
@marielejeune I won't have time in April. Feel free to superseed.

**Comment by pedrobaeza** [comment]
Superseded by #4411

**Pull request closed without merging**
