### PR TITLE
[15.0][MIG] account_menu -> account_usability

### PR DESCRIPTION
**Pull request by Saran440**
rename module account_menu (v14) to account_usability (v15)

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Could you remove the line 56 in the same file. It is writen that account_menu is merged into account_usability, that is wrong.
Thanks !

**Comment by Saran440** [comment]
@legalsylvain Fixed it. Thank you.

If i have module `A` and `B` in V14 and V15 it change name to module `C`. I should use `merged_modules` for this case?
I'm not sure what is difference `merged_modules` and `rename_modules`

**Comment by legalsylvain** [comment]
Merge a + b -> b
Rename a -> b

More info in documentation use case : https://oca.github.io/OpenUpgrade/development.html#learn-from-typical-use-cases

**Review by legalsylvain — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why changing this? Does a module `account_usability` exists in v14? If so, it should remain in `merged_modules`. There's is very few differences between using `update_modules` with merge_modules=True or False, but one on them is to avoid errors if the target name already exists.

**Comment by legalsylvain** [comment]
> Why changing this? Does a module account_usability exists in v14? If so, it should remain in merged_modules. There's is very few differences between using update_modules with merge_modules=True or False, but one on them is to avoid errors if the target name already exists.

well. it is a rename, not a merge. I asked for a fix, because I made a mistake in the initial commit : https://github.com/OCA/OpenUpgrade/pull/3590
 
 account_usability doesn't exist in OCA before V15. https://odoo-community.org/shop/account-missing-menus-saxon-accounting-10561?search=account_usability#attr=22622

regards.

**Comment by pedrobaeza** [comment]
But isn't present in Akretion branches? If so, it would help to keep it as is. It doesn't have any drawbacks, and for those having in the list the old one, it wouldn't crash.

**Comment by legalsylvain** [comment]
> But isn't present in Akretion branches? If so, it would help to keep it as is. It doesn't have any drawbacks, and for those having in the list the old one, it wouldn't crash.

Indeed !

**Pull request merged**
