### PR TITLE
[11.0][IMP] stock: Merge quants by SQL

### PR DESCRIPTION
**Pull request by pedrobaeza**
Now that the merge records SQL method covers the values adjustment, it should be faster to use it for this.

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Testing in a real migration.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
But this merge of quants by ORM has never supposed a long process (as far as I saw in the migrations I have done).

**Comment by pedrobaeza** [comment]
Not sure this worths. I'll check this afternoon, but the process can be very huge, specially with lots. I'm finding a lot of errors, so maybe the SQL merge is not completed, but if I have similar times, I won't switch.

**Comment by pedrobaeza** [comment]
Definitively it doesn't worth. I got even higher times (9h07' against 8h55') than with ORM, and there's an operation that is not correct through this way, so closing.

**Comment by MiquelRForgeFlow** [comment]
> and there's an operation that is not correct through this way

which one?

**Comment by pedrobaeza** [comment]
There was an integrity error doing an update, but I didn't take note of it and I don't remember exactly, sorry.

**Pull request closed without merging**
