### PR TITLE
[13.0][FIX] stock: must delete model data of location_procurement

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
In https://github.com/OCA/OpenUpgrade/pull/2519, the location_procurement was forgotten. @kos94ok-3D 

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by kos94ok-3D — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Shouldn't you include such location in the other part of the scripts?

**Comment by MiquelRForgeFlow** [comment]
>  in the other part of the scripts?

Which part? There is nothing we can do with this location

**Comment by pedrobaeza** [comment]
I mean the part `DONE: post-migration: mapped them to new locations`

**Comment by MiquelRForgeFlow** [comment]
Well, in this case this location cannot be mapped to something else :S

**Comment by pedrobaeza** [comment]
Isn't there any replacement for it?

**Comment by MiquelRForgeFlow** [comment]
No, as far I know.

**Pull request merged**
