### PR TITLE
[16.0][OU-FIX] stock: do not try to compute quantity_done for canceled stock moves

### PR DESCRIPTION
**Pull request by em230418**
Otherwise UserError will be raised [1]

[1] https://github.com/odoo/odoo/blob/0043634d87fdde1fa427eda90e444fe76767bacb/addons/stock/models/stock_move.py#L675-L676

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is it possible to have stock.move.line with quantity done when the move is cancelled?

**Comment by em230418** [comment]
> Is it possible to have stock.move.line with quantity done when the move is cancelled?

Yes.

1. Make sure your user is in group "Manage Multiple Stock Locations"
2. Inventory -> Configuration -> Operation Types
3. For example choose "Delivery orders"
4. Add tick on "Show Detailed Operations" checkbox, save
5. Inventory -> Operations -> Transfers
6. Create transfer with "Delivery orders" type, add product that exist in stock. Demand value for example 1. Save
7. "Mark as Todo" button
8. "Set quantities" button
9. "Cancel" button

In "detailed operations" tab you will see red line with value 1 quantity done.

Reproduced here.
http://oca-event-15-0-a74d199cc222.runboat.odoo-community.org/web?debug=1#cids=1&menu_id=108&action=234&model=stock.picking&view_type=form&id=32

In production database on 14.0 I have 2180 canceled stock move lines from 2022 to 2024.

**Comment by em230418** [comment]
Today I checked, that my patch worked so marked as ready for review.,

**Review by pedrobaeza — APPROVED** [review]
OK, it doesn't harm either.

**Pull request merged**
