### PR TITLE
Draft: [MIG][15.0] openupgrade_framework

### PR DESCRIPTION
**Pull request by jcdrubay**
- in the .github/workflows/test.yml: I updated versions (not 100% sure if it's right)
- pre-migration: Add call to rename/merge modules listed in apriori.py
- Rename the xml ids which have been moved from the module mail to the module base and from module 
- Remove the odoo_patch on function _postprocess_view which became useless after the input argument validate has been removed from native Odoo

Note: this PR is  mostly created to test the github workflows.

https://github.com/legalsylvain/OpenUpgrade/pull/4

### CODE REVIEW

**Comment by jcdrubay** [comment]
@pedrobaeza Could you please help me with the pipeline/workflows?

### issue 1
```
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3; 2615 2200 SCHEMA public postgres
pg_restore: error: could not execute query: ERROR:  schema "public" already exists
Command was: CREATE SCHEMA public;


pg_restore: warning: errors ignored on restore: 1
Error: Process completed with exit code 1.
```

This seems out of the scope of this PR. Let me know if there is anything I can do.

### Issue 2
`openupgrade_scripts/scripts/l10n_generic_coa/15.0.1.1/noupdate_changes.xml:1: [W7930(file-not-used), ]  not used from manifest`

Do you agree that we should disable this test ? I will do that in the next commit.

**Comment by pedrobaeza** [comment]
@StefanRijnhart and @legalsylvain are the men here

**Comment by legalsylvain** [comment]
> Do you agree that we should disable this test ? I will do that in the next commit.

Indeed.

**Comment by legalsylvain** [comment]
> @StefanRijnhart and @legalsylvain are the men here

Don't understand Openupgrade CI very well, but let's try ! 

@jcdrubay : could you uncomment the line regarding ``DROP SCHEMA`` ? 
- the line is commented in [V14.](https://github.com/OCA/OpenUpgrade/blob/14.0/.github/workflows/test.yml#L50)
- the line is not comment in [V13](https://github.com/OCA/OpenUpgrade/blob/13.0/.github/workflows/test.yml#L43)

@MiquelRForgeFlow : do you remember why the lines was commented when you restored the tests for V14 [in that PR ](https://github.com/OCA/OpenUpgrade/pull/2744/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R43)?

**Comment by MiquelRForgeFlow** [comment]
> @MiquelRForgeFlow : do you remember why the lines was commented when you restored the tests for V14 [in that PR ](https://github.com/OCA/OpenUpgrade/pull/2744/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R43)?

No, I don't remember, sorry. Maybe it was because there was not need to execute that.

**Comment by etobella** [comment]
Well, it has no sense to comment the line. It will only drop the schema if it exists, so, IMO, you can execute it without problems. @jcdrubay Can you try it?

**Comment by jcdrubay** [comment]
Ok, I ll do now

**Comment by jcdrubay** [comment]
The click issue seems documented
https://github.com/psf/black/issues/2964

Should we do the same as:

https://github.com/OCA/web/blob/15.0/.github/workflows/pre-commit.yml

**Comment by etobella** [comment]
I can help you with that :smile: 
https://github.com/jcdrubay/OpenUpgrade/pull/5

**Comment by jcdrubay** [comment]
GREEN!!! 😀

**Comment by jcdrubay** [comment]
Thank you everyone for your support on this PR, it's fantastic.  :D

I think I should close it now as it will be processed in another MR, right @legalsylvain ?

**Pull request closed without merging**
