### PR TITLE
[ADD] inject some custom demo data in test database

### PR DESCRIPTION
**Pull request by hbrunn**
This is a proposal for a general approach to fix problems like https://github.com/OCA/OpenUpgrade/pull/556#issuecomment-233965167

To be done in the (n-1)st version, then we'd have to regenerate the test database (we should be able to automate that), and things work out. I'll create a PR soon that uses a database generated with this.

### CODE REVIEW

**Comment by hbrunn** [comment]
#563 shows this works as expected

**Comment by hbrunn** [comment]
@OCA/openupgrade-maintainers do you agree with replacing the current test database with the one generated by the modified script with this PR? This will give us 100% coverage builds again

**Comment by dreispt** [comment]
Sounds good to me.
Wouldn't it be simpler to include an actual yml file in the scripts directory?

**Comment by hbrunn** [comment]
@dreispt not really, because then the script has dependencies. Now, you can drop it wherever and it's going to work

**Comment by pedrobaeza** [comment]
OK, it seems a bit ugly but you should be sure about no other better option

:+1:

**Comment by dreispt** [comment]
OK, I think we can live with it, at least for now. :+1:

**Comment by StefanRijnhart** [comment]
It's a start! :+1:

**Pull request merged**
