### PR TITLE
[FIX] missing report type and tree type

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think we should directly remove that checks, as they block the migration and can have valid values depending on the extra modules in the DB, so adding more and more values is not the ideal situation.

@legalsylvain you added it in 91f7d18d4d993f8ab143305fc00eeaffd7d0c923. Can you explain the reasoning behind this?

**Comment by legalsylvain** [comment]
As far as I remember (5 years ago, certainly for a migration from 5 to 6 or 7...) i had a database with obsoletes values, and need a warning to know it.
I think that we should improve the code instead of removing it, introducing dynamic list but not a blocking point.
I'll check the Pr to know the discussion arpund this commit.

**Review by legalsylvain — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Odoo already checks this, indicating that a selection value is not valid, so I still prefer to remove this.

**Comment by StefanRijnhart** [comment]
It just logs an error doesn't it? Is there much harm in that? Could be informative for developers. Maybe change to WARN?

**Review by StefanRijnhart — APPROVED** [review]

**Comment by sergiocorato** [comment]
Yes, it is only a log

**Comment by StefanRijnhart** [comment]
@pedrobaeza please reconsider. It's only a harmless log message, not a block.

**Comment by pedrobaeza** [comment]
Well, I don't like but I'm not blocking it either, as I haven't pushed "Changes requested". If you still prefer to keep it, go ahead, as this is an old version.

**Comment by StefanRijnhart** [comment]
@pedrobaeza ok, thanks for confirming.

/ocabot merge

**Pull request merged**
