### PR TITLE
[14.0][IMP] project: pre-create computed stored fields

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Tested.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks. makes sense.

A question : 

>  ``DONE: pre-migration: filled by SQL, to avoid computations and inverses``

I understand "computations" but I don't undertand inverses. What do you mean ?

**Comment by MiquelRForgeFlow** [comment]
Well, the fields have inverse methods... 😅 See https://github.com/odoo/odoo/blob/14.0/addons/project/models/project.py#L822

**Review by pedrobaeza — COMMENTED** [review]
Two comments:

- I don't see a comment in the analysis file for the project_allowed_portal_users_rel thing.
- I think the rest of the m2m table setup (fk constraints and indexes) is not correctly done if you create it that way. Check how I did in purchase v13

**Comment by MiquelRForgeFlow** [comment]
Done.

> I don't see a comment in the analysis file for the project_allowed_portal_users_rel thing.

What do you mean? Check https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/scripts/project/14.0.1.1/upgrade_analysis_work.txt#L35

**Comment by MiquelRForgeFlow** [comment]
In v14, due to https://github.com/odoo/odoo/commit/6eb7d5c6a07f678e1d1adca7137652e0626ea17e, we cannot call `update_db` like in v13. But the new trick of calling `init_models` seems to work fine.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
