### PR TITLE
[12.0][MIG] website_livechat 

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Migration scripts for `website_livechat` module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr
👻

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please use usual convention for pre-migration file name.

**Comment by MiquelRForgeFlow** [comment]
Oh, I liked to put this kind of easter eggs haha

**Comment by pedrobaeza** [comment]
And you risk the possibility of an incompatible system with that character... Please go to standards.

**Comment by MiquelRForgeFlow** [comment]
done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
