### PR TITLE
[7.0][FIX] Merge user with existing partner if exists

### PR DESCRIPTION
**Pull request by mistotebe**
Databases might already hold partners for users, merge if that's the case.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Uhm, merge by name is not the best approach...

I remember @hbrunn made something for this.

**Comment by hbrunn** [comment]
hmmm, not sure what you mean. Maybe #219?

But I also think this PR needs a lot more safeguards (match by email for example). And it should also exclude some special partners (base.main_partner for example).

The situation with duplicated partners is annoying, but also our 2k+ employees customer managed with the merge wizard. So every code that tries to match stuff must be super conservative in my opinion, and then I'm not sure how many matches will be found at all.

**Comment by pedrobaeza** [comment]
That's it, @hbrunn. I remember something that involves users, but definitely is not the same as this.

For this, and having the possibility of merging partners with the OCA module, I would say :-1:

**Comment by mistotebe** [comment]
This branch is really only here since we used it in a migration that we did and keep a branch for it for tracking purposes. I'm happy to make it more strict to check on email as well (if set on user) or if you're not inclined to accept it anyway, we'll just keep it as a local patch on top of OpenUpgrade.

**Comment by StefanRijnhart** [comment]
Thanks for understanding! Agree with @pedrobaeza and @hbrunn above

**Pull request closed without merging**
