### PR TITLE
[8.0] Fix production order move_lines, move_lines2 migration to one2many

### PR DESCRIPTION
**Pull request by paulius-sladkevicius**
I hope I'm not loosing something here, but SQL query should do a trick. Now it doesn't work at all because `move_lines` and `move_lines2` returns empty recordsets (I suppose Odoo ORM can't handle automatically m2m to o2m migration).

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this was done this way because you can't obtain all possible values by SQL. @StefanRijnhart you were the original author of this, do you remember about that?

Any way, what's the problem? Is this very slow for you?

**Comment by paulius-sladkevicius** [comment]
@pedrobaeza, it doesn't work at all for me, it's not related with speed or other minor issue.

**Comment by pedrobaeza** [comment]
Then please also explain the exact use case for which is failing. As you know the involved data, you can point relevant data that can make this to fail.

**Comment by paulius-sladkevicius** [comment]
I'm following same approach [like here](https://github.com/OCA/OpenUpgrade/blob/8.0/addons/calendar/migrations/8.0.1.0/openupgrade_analysis.txt#L33) where migration script is done in [a same way](https://github.com/OCA/OpenUpgrade/blob/8.0/addons/calendar/migrations/8.0.1.0/post-migration.py#L137-L144). It's a same scenario [here too](https://github.com/OCA/OpenUpgrade/blob/8.0/addons/mrp/migrations/8.0.1.1/openupgrade_analysis.txt#L26-L27). 
Could be @StefanRijnhart can give his comment why this one done in such way.

**Comment by paulius-sladkevicius** [comment]
@StefanRijnhart could you inform if you can help here?

**Comment by StefanRijnhart** [comment]
Maybe I completely overengineered this and broke a proper mapping. I'll have a look.

**Comment by StefanRijnhart** [comment]
Wait @pedrobaeza 
```
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 107) def update_stock_moves(env):
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 108)     stock_move_obj = env['stock.move']
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 109)     mrp_production_obj = env['mrp.production']
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 110)     ir_property_obj = env['ir.property']
c181c69e465e (Holger Brunn      2015-08-18 17:25:08 +0200 111)     # find all locations that are used as production location
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 112)     locations = [
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 113)         ir_property_obj.get_by_record(p)
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 114)         for p in ir_property_obj.search(
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 115)             [('name', '=', 'property_stock_production')])]
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 116)     location_ids = list(set(x.id for x in locations if x))
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 117)     for move in stock_move_obj.search(
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 118)             [('location_dest_id', 'in', location_ids)]):
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 119)         productions = mrp_production_obj.search([
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 120)             '|',
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 121)             # don't rely on many2manys with domain ignoring it on search
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 122)             ('move_lines', '=', move.id),
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 123)             ('move_lines2', '=', move.id),
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 124)         ])
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 125)         if len(productions) == 1:
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 126)             env.cr.execute(
c181c69e465e (Holger Brunn      2015-08-18 17:25:08 +0200 127)                 'UPDATE stock_move SET raw_material_production_id=%s '
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 128)                 'WHERE id=%s', (productions.id, move.id))
c181c69e465e (Holger Brunn      2015-08-18 17:25:08 +0200 129)         else:
c181c69e465e (Holger Brunn      2015-08-18 17:25:08 +0200 130)             logger.warning("Couldn't find unique production order for %s "
516b88d5abfc (Pedro M. Baeza    2016-03-22 11:49:42 +0100 131)                            "(candidates are %s)", move.id, productions.ids)
```

**Review by StefanRijnhart — APPROVED** [review]
Agreed! The original version queried the field that it attempts to fill, so it could not work. Thanks!

**Comment by StefanRijnhart** [comment]
Actually, @pedrobaeza did not write the original either. I think it should have worked somewhat up until here: https://github.com/OCA/OpenUpgrade/commit/c181c69e465e37d5395c6a232ea8457d5cc3eabb

**Review by pedrobaeza — APPROVED** [review]
Thanks for your patience, @paulius-sladkevicius

**Comment by StefanRijnhart** [comment]
Yes, sorry I missed your first ping :-(

**Pull request merged**
