### PR TITLE
[UPD] documentation: renames, merges & bigger table

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
- Updated documentation with renames and merges.
- Provided bigger table.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can't we avoid to make bigger and bigger tables with other syntax that doesn't need this fixed size? I think RST have a syntax for that

**Comment by MiquelRForgeFlow** [comment]
I don't know, but I don't think we will need to make the table bigger anymore (in this version). Let's begin to think that for v12 :stuck_out_tongue_winking_eye:

**Comment by mreficent** [comment]
Let's begin to think that for v12 :stuck_out_tongue_winking_eye:

**Comment by MiquelRForgeFlow** [comment]
I don't know what happened with Travis, but can we fast-track it? :S

**Comment by StefanRijnhart** [comment]
Can you not tag obsolete modules with 'Done' as it triggers travis to try and upgrade these modules. Not sure if that broke travis now but it's not pretty.

**Comment by pedrobaeza** [comment]
@StefanRijnhart we tag them as "Done" where there's code for handling this disappearance. For example, calling `update_module_names` with `merge_modules=True` argument. So for that part, I think it's correct, but you are right that it's going to try to install that module on Travis, but the only output we will get is a warning about not found module on this version. On the other way, I think it's needed for having the module installed on the previous version.

Any way, the error should come from other place.

**Comment by StefanRijnhart** [comment]
So don't tag those modules with Done, or modify travis config even if it does not break travis __now__. Just tagging them with `Merged with...` is just as clear.

**Comment by pedrobaeza** [comment]
But are you sure they don't need to be installed on version N-1?

**Comment by StefanRijnhart** [comment]
Travis runs the tests on a prefab database with all modules installed, so the migration status of a module does not influence the set of installed modules, if that is what you mean.

**Comment by StefanRijnhart** [comment]
But you are onto something. When a module is renamed, its ir_module_module entry is renamed as well. Travis will set its status to uninstalled and will not run the new module's migration scripts. So we need to split up the selection of modules to uninstall and the selection of modules to upgrade.

For the scope of this PR then we can leave it like this for now if it does not break anything. Travis is already broken so we can merge this and clean up afterwards.

**Review by StefanRijnhart — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Then I merge this as fast-tracking.

**Comment by MiquelRForgeFlow** [comment]
Hmmm... The problem is still there :S

**Comment by MiquelRForgeFlow** [comment]
The problem it's the table's size or what? I don't understand why changing a `.rst` file is giving problems.

**Comment by StefanRijnhart** [comment]
What is the problem?

**Comment by MiquelRForgeFlow** [comment]
I don't know, but Travis now is red in the new PRs

**Pull request merged**
