### PR TITLE
[11.0][IMP] Have postgres process the update

### PR DESCRIPTION
**Pull request by ivantodorovich**
This is continuoing the work in https://github.com/OCA/OpenUpgrade/pull/2341

In an effort to improve the performance of this particular script, this PR drastically reduces the number of queries needed, and pushes the heavy work to postgres.

In our case it reduced ~28 hours down to a few seconds

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
This is great work! We need performance improvements like these. Thanks!

**Comment by pedrobaeza** [comment]
Several things before merging:

- Please rename the commit to follow commit message guidelines (mentioning the module).
- `UPDATE` queries should be done with `logged_query` for having a trace of what's going on.

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by ivantodorovich** [comment]
Sorry @pedrobaeza for not even replying ! 
I seem to have missed the email notification.

I just pushed the changes :)

**Pull request merged**
