### PR TITLE
[ADD] drop some views that prevent changing field types

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sbidoul** [comment]
I've had issues with the report_document_user view. Can you drop it too?

:+1:

**Comment by hbrunn** [comment]
@sbidoul I think that should be done in the prescript of the module creating this view (which would be document)

**Comment by sbidoul** [comment]
@hbrunn agreed

**Comment by pedrobaeza** [comment]
@sbidoul I have made for you on #154 :wink:

**Pull request merged**
