### PR TITLE
[14.0][OU-ADD] sale_order_margin_percent: Merged sale_order_margin_percent to sale_margin. 

### PR DESCRIPTION
**Pull request by victoralmau**
Merged `sale_order_margin_percent` to `sale_margin`

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@sergio-teruel I think the `read_group` part is missing on core for proper percentage average, isn't it? Should we keep the OCA module?

**Comment by sergio-teruel** [comment]
@pedrobaeza This module has not add code to report, so is OK.

But @victoralmau please you must create a pre-migration script to pre-create the fields and compute data by sql queries because the percent fields in OCA module are computed and in Odoo core are store. This will do that in a database migration we have a great performance.

**Comment by victoralmau** [comment]
> @pedrobaeza This module has not add code to report, so is OK.
> 
> But @victoralmau please you must create a pre-migration script to pre-create the fields and compute data by sql queries because the percent fields in OCA module are computed and in Odoo core are store. This will do that in a database migration we have a great performance.

Ok, I think that's a good suggestion. Checking `sale_margin` addon I see that this improvement is already implemented at https://github.com/OCA/OpenUpgrade/pull/3096.

**Review by sergio-teruel — APPROVED** [review]

**Comment by sergio-teruel** [comment]
Thanks @victoralmau

**Pull request merged**
