### PR TITLE
9.0 ref apriori file

### PR DESCRIPTION
**Pull request by legalsylvain**
This PR is to continue the work of analysis I began about migration coverage.
(Réf : https://github.com/OCA/OpenUpgrade/pull/1583)

For that purpose, I have to distinguish merged / renamed modules from OCA + odoo and modules from others repositories.
This PR is just refactoring.

I'll do it the same for version 10.0+ after.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't think that comments are the best way to reflect things. We should have other structured data.

**Review by MiquelRForgeFlow — CHANGES_REQUESTED** [review]
Sorry, but I don't like this approach ❌

**Comment by legalsylvain** [comment]
> I don't think that comments are the best way to reflect things. We should have other structured data.

I mainly splited each list into 2 lists. (the OCA / odoo modules), and others modules that are not under OCA umbrella. And comments are already present in this file. So I don't understand which comments you're talking about.

> Sorry, but I don't like this approach

Could you give a reason @mreficent  ? ;-)

**Comment by MiquelRForgeFlow** [comment]
> Could you give a reason @mreficent  ? ;-)

Aesthetic changes don't need reasons. You just like them or not. 😏

**Comment by pedrobaeza** [comment]
> I mainly splited each list into 2 lists. (the OCA / odoo modules)

@legalsylvain that's why I say that this is not enough for identifying everything with full information, and more in an automated way IMO.

**Comment by MiquelRForgeFlow** [comment]
> and others modules that are not under OCA umbrella

It's not important if the origin name of the module is not in OCA/Odoo. What's important is that the target rename/merge is in OCA/Odoo.

**Comment by legalsylvain** [comment]
> It's not important if the origin name of the module is not in OCA/Odoo.

for the work i began during odoo experience this year, yes it's important. 

> What's important is that the target rename/merge is in OCA/Odoo.

And some modules are not under oca umbrella at all. 

```
    'sale_product_variants': 'sale_variant_configurator',
    'sale_stock_product_variants': 'sale_stock_variant_configurator',
```

**Comment by pedrobaeza** [comment]
That modules were a transfer from odoomrp-wip to OCA as agreed when done.

**Comment by MiquelRForgeFlow** [comment]
> for the work i began during odoo experience this year, yes it's important.

Then upload that work so this way we can value correctly this PR :)

**Comment by StefanRijnhart** [comment]
I don't understand why you need the distinction. As is pointed out above, the odoo-mrp project is an exception. And the distinction is only important if there is a name clash. Do you have an example of such a clash?

**Comment by pedrobaeza** [comment]
Closing as no further news.

**Pull request closed without merging**
