### PR TITLE
8.0 sale_stock

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Sorry, I managed to remotely delete the original branch when I was trying to push my no-branch. So we now lack the excellent discussion which lead to the development of the disable-workflow convenience function for instance. But at least we still have the code, ready as far as I am concerned.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
BTW, we can have the reference to old PR here: #124

**Comment by pedrobaeza** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Thanks, you found it! I thought it was lost after I had deleted the branch in the online dev repository.

**Comment by pedrobaeza** [comment]
Can anyone more check this?

**Comment by legalsylvain** [comment]
yes I planed to work on it next week.

**Comment by njeudy** [comment]
I test on a complete base today. will report PR and errors if any.

**Comment by kirca** [comment]
Any news on whether this is good?

**Comment by pedrobaeza** [comment]
I merge, and if there's any problem, can be reported as an issue and PR.

**Pull request merged**
