### PR TITLE
[16.0][FIX] Switch Flake8 pre-commit source to GitHub

### PR DESCRIPTION
**Pull request by marielejeune**
Cherry-pick commit from branch 15.0

### CODE REVIEW

**Comment by marielejeune** [comment]
@pedrobaeza I just cherry-picked your commit from branch 15.0

**Comment by marielejeune** [comment]
I also would like to fix pre-commit issues but cannot run `copier update` as there is no `.copier-answers.yml` file

**Comment by legalsylvain** [comment]
> I also would like to fix pre-commit issues but cannot run copier update as there is no .copier-answers.yml file

Hi. indeed, there is no .copier-answer file in this project. For the time being, it's quite hard to add one, because some files are different as the default ones. (specifically the test files).

you have to meld between another "classical oca repo" and the openupgrade repo.

**Comment by marielejeune** [comment]
@legalsylvain I did it, from OCA/partner-contact repo

**Comment by legalsylvain** [comment]
Thanks ! 
/ocabot merge nobump

**Pull request merged**
