### PR TITLE
[ADD] account_asset: Move to OCA account_asset_management (renamed mo…

### PR DESCRIPTION
**Pull request by ghost**
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, @apps2grow thanks for this effort for migrating from account_asset to account_asset_management. What belongs here is to put in `apriori.py` the renaming of the module name, but not the renaming of models, that should be done on the module itself pre-migration. And please put it on the merge_modules section, as in 11.0, there's a change you have both modules available in the list.

**Comment by MiquelRForgeFlow** [comment]
I don't understand what happened :S

I did a force push, but not closing :S  And I cannot open :S

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza the merge is already done in https://github.com/OCA/OpenUpgrade/blob/12.0/odoo/addons/openupgrade_records/lib/apriori.py#L44.

**Comment by MiquelRForgeFlow** [comment]
In fact, the full migration is already done in https://github.com/OCA/account-financial-tools/pull/873! :)

**Comment by pedrobaeza** [comment]
Then this is useless. I will review soon the other PR

**Comment by ghost** [comment]
Thank you for coordinating the openupgrade. :)
I just posted a question on https://github.com/OCA/account-financial-tools/pull/873

**Pull request closed without merging**
