### PR TITLE
[12.0][MIG] website_sale_delivery: Migration script

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT20148
@chienandalu @Yajo Can you review?

### CODE REVIEW

**Review by yajo — CHANGES_REQUESTED** [review]
AFAIK you should duplicate the `openupgrade_analysis.txt` file and name it `openupgrade_analysis_work.txt` to document there what changes have been done.

**Comment by sergio-teruel** [comment]
@Yajo Changes done!!

**Review by yajo — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
ok. Although travis is red (surely unrelated)

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@chienandalu the red status is because we use a hack for coming back to the commit that Travis is testing, and this fails sometimes.

**Comment by pedrobaeza** [comment]
I have pushed directly b0b89c9ad52b386d01e21d7a9596cc2374f8d4e1 for fixing the lack of CI / documentation.

**Comment by pedrobaeza** [comment]
and this fix has been needed once the CI has told:

d3ba9eb826765313ed9f4a00285d23b68eca2330

**Pull request merged**
