### PR TITLE
[FIX] Add move of xml_id's to im_livechat.

### PR DESCRIPTION
**Pull request by NL66278**
Description of the issue/feature this PR addresses: Migration crashes on duplicate group

Current behavior before PR: Migration crashed

Desired behavior after PR is merged: Migration succeeds

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please update documentation marking im_livechat as "Done".

**Comment by NL66278** [comment]
@pedrobaeza Maybe I am a little bit foggy in my head due to a severe cold, but I can not quite find where to update this documentation.

**Comment by pedrobaeza** [comment]
It's on https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/openupgrade/doc/source/modules80-90.rst.

I can do it if you want.

I hope you'll get better soon.

**Comment by NL66278** [comment]
Please do. Thanks a lot! I checked the migration analysis and I really think only the rename of the xmlid's is needed, but I am not totally sure. But my primary purpose was that the migration should no longer crash.

**Comment by pedrobaeza** [comment]
Done in this branch and merging when Travis finishes.

**Pull request merged**
