### PR TITLE
[15.0][OU-ADD] sale_project: Migration scripts

### PR DESCRIPTION
**Pull request by pedrobaeza**
@Tecnativa TT35781

### CODE REVIEW

**Comment by remi-filament** [comment]
Hi @pedrobaeza , I see you modify sale_purchase here instead of sale_project, am I missing something or is it a mistake ?

**Comment by pedrobaeza** [comment]
Yes, it has been a mistake. Moving files in a direct commit.

**Comment by pedrobaeza** [comment]
Fixed in 7fe09768b1d6669a3b2e4527747aac9c98f25c68. Thanks to notify it.

**Pull request merged**
