### PR TITLE
[13.0][FIX] account: read fields when computing balance for draft invoices

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Add some stored fields.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by kos94ok-3D — APPROVED** [review]
It just prefetches fields once, so OK for me.

**Comment by pedrobaeza** [comment]
Why not reading all fields for avoiding this problem with other modules that add fields to this computation?

**Comment by kos94ok-3D** [comment]
I just tried to improve some performance and didn't think that it will be a problem.

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza now it reads all fields

**Review by pedrobaeza — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
ocabot still not working :S

**Pull request merged**
