### PR TITLE
[13.0][MIG] stock_landed_costs

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Migration of stock_landed_costs.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kos94ok-3D** [comment]
Hi, @MiquelRForgeFlow 
Can you check this patch https://github.com/OCA/OpenUpgrade/commit/9d3c7eb85da3a79f966631a9881d8e47f092319e?

======================================
Edited:
Create SVL through SQL in order to set correct create_date, create_uid, write_*
New patch: https://github.com/kos94ok-3D/OpenUpgrade/commit/d2e9facf0148fdc812a835e3938b80a2b365ddc0

**Comment by kos94ok-3D** [comment]
HI, @MiquelRForgeFlow  Can you check these changes: https://github.com/OCA/OpenUpgrade/commit/a145c933675a2f8eee14a5f318664b06d518ce1d

**Comment by MiquelRForgeFlow** [comment]
Thanks @kos94ok-3D

**Review by kos94ok-3D — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
I have added some docstrings.

**Pull request merged**
