### PR TITLE
[16.0][OU-ADD] mrp: migration

### PR DESCRIPTION
**Pull request by carmenbianca**
Quite a bit of work. Did some analysis work. A lot of stuff still needs doing. Not sure if I'll have the time budget to see this PR through, but fingers crossed.

internal task: https://gestion.coopiteasy.be/web#id=11154&action=475&active_id=501&model=project.task&view_type=form&menu_id=536

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration mrp

<dependency></dependency>

**Comment by carmenbianca** [comment]
I indeed won't have the time budget to continue work on this for a while.

**Comment by diggy128** [comment]
Any update on this?

**Comment by pedrobaeza** [comment]
As this doesn't contain the reasons why it's nothing to do for some fields, and most of the TODOs are not correct, I have started from scratch and completed the migration scripts in #4381.

Thanks anyway for the initial effort.

**Pull request closed without merging**
