### PR TITLE
[ADD] disable more transitions during sale order update

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks.

:+1:

**Comment by hbrunn** [comment]
wait for #137

**Comment by pedrobaeza** [comment]
You have to rebase due to the change of branch

**Comment by hbrunn** [comment]
rebasing done

**Comment by hbrunn** [comment]
this depends on #163 now

**Comment by StefanRijnhart** [comment]
#163 merged, so this can go too. Thanks! :+1:

**Pull request merged**
