### PR TITLE
[MIG][11.0] website_portal_sale: merged into sale_payment

### PR DESCRIPTION
**Pull request by cubells**
cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I don't see the change in website_sale for renaming the remaining XML-ID. And please rebase (fetching first the origin) for avoiding the current weird error.

**Comment by sergio-teruel** [comment]
@cubells I'm not sure of this... I think that website_portal_sale is merged into sale module, you can see the views definitions and controllers here
v10 (https://github.com/OCA/OCB/blob/10.0/addons/website_portal_sale/views/website_portal_sale_templates.xml#L23) 
v11 (https://github.com/OCA/OCB/blob/11.0/addons/sale/views/sale_portal_templates.xml#L20)

**Comment by pedrobaeza** [comment]
See the internal task for an explanation, but indeed this lacks the the XML-ID renaming I have already mentioned

**Comment by sergio-teruel** [comment]
OK. We wait to remame XML-ID

**Comment by cubells** [comment]
@sergio-teruel @pedrobaeza can you recheck?

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
