### PR TITLE
[16.0][OU-ADD] association: Nothing to do

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT45223

@pedrobaeza please review!

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration association

<dependency>Depends on : 

- membership : #4007</dependency>

**Review by chienandalu — COMMENTED** [review]
Check for dependencies. This should be blocked by: https://github.com/OCA/OpenUpgrade/pull/4007

**Comment by stefan-tecnativa** [comment]
@chienandalu the dependency module is merged. Is this ready?

**Review by chienandalu — APPROVED** [review]
Yes :+1:

**Pull request merged**
