### PR TITLE
[11.0][FIX] base: Adjust res.partner.category colors

### PR DESCRIPTION
**Pull request by pedrobaeza**
Colors have changed over versions, so we try to preserve the most similar ones.

Selección_032

Selección_034

@Tecnativa TT17617

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
:+1: Looks good :)

**Review by ivantodorovich — APPROVED** [review]

**Comment by yajo** [comment]
> Selección_032
> 
> Selección_034



:laughing: Jokes apart, good job!

BTW, would this affect the whole Odoo framework everywhere a given record uses colors? Should this go then into the version-specific file of openupgradelib?

**Comment by pedrobaeza** [comment]
Not sure if these colors are applied in other places. Do you know other cases?

**Comment by yajo** [comment]
A quick search of `color_field` in the v11 codebase yields a few results:

- account.invoice.line.analytic_tag_ids
- crm.lead.tag_ids
- fleet.vehicle.tag_ids
- hr.employee.category_ids
- hr.applicant.categ_ids
- note.note.tag_ids
- project.task.tag_ids

... and a few more. Maybe some of these apply to the same models, I didn't dig that much.

But it seems to me like this could fit fine in openupgradelib then. If you prefer, we can leave that for when this is actually needed? :thinking: But it's good to keep it in mind.

**Pull request merged**
