### PR TITLE
10.0 analysis

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
As expected, mrp_\* are the modules with more changes. You can merge then if you want. There's a typo in a char saying "[nothing to to]" that I'm trying to locate.

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/OpenUpgrade/commit/02825617b57738f298044f63abee9b35a3e1ea34

**Comment by pedrobaeza** [comment]
Are you going to work on base migration + initial test db?

**Comment by StefanRijnhart** [comment]
Ha that typo is terrible. Let me just regenerate. I'll merge in latest Odoo in case there were some last minute (post-release) changes.

**Comment by StefanRijnhart** [comment]
Regenerated with latest Odoo and without typo in 'Nothing to to'

**Comment by StefanRijnhart** [comment]
@pedrobaeza I'd appreciate an optimistic handling, but Hintjen's rule was have someone else merge the code (even if it is one of the kids, or the dog).

If no one else takes the honour, I will look at the base migration and test database in the foreseen future.

**Comment by pedrobaeza** [comment]
OK, then I do the honors of merging this (but let you for now with the base migration). I will catch the script migration sprint very soon (in a couple of weeks I hope).

**Comment by duanyp1991** [comment]
@StefanRijnhart  Thanks for your work! How can I check which commit ID of 9.0 code the analysis work was based on? I generated the analysis result just now and got some difference. I guess there are some updates from odoo on v9.0 (even some on data structure part)

eg,
diff --git a/addons/procurement/migrations/10.0.1.0/openupgrade_analysis.txt b/addons/procurement/migrations/10.0.1.0/openupgrade_analysis.txt
index f453286..5ca104c 100644
--- a/addons/procurement/migrations/10.0.1.0/openupgrade_analysis.txt
+++ b/addons/procurement/migrations/10.0.1.0/openupgrade_analysis.txt
@@ -1,4 +1,3 @@
 ---Fields in module 'procurement'---
-procurement  / procurement.order        / website_message_ids (one2many): DEL relation: mail.message
 ---XML records in module 'procurement'---
 DEL ir.ui.view: procurement.mrp_company

**Comment by StefanRijnhart** [comment]
@duanyp1991 the differences are likely to be caused by something else, as the mrp_company record has been present in all commits of the 9.0 branch. https://github.com/odoo/odoo/commits/9.0/addons/procurement/company_view.xml.

**Pull request merged**
