### PR TITLE
[OU-ADD] project_stage_state > project_task_stage_state

### PR DESCRIPTION
**Pull request by manuelregidor**
Module renamed.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This can't be merged yet, as v15 base is not yet done.

**Comment by HaraldPanten** [comment]
> 

Sorry Pedro, I didn't understand you well. What do you mean that V15 base is not done?

THX

**Comment by pedrobaeza** [comment]
OpenUpgrade v15 `base` module migration scripts are not yet done.

**Comment by HaraldPanten** [comment]
We can leave the PR as it is, pending to the base OpenUpgrade module, right?

**Comment by pedrobaeza** [comment]
Of course! It just to low your expectations when I told you about a fast merge. I didn't know that it was for 15.0 instead of 14.0.

**Comment by HaraldPanten** [comment]
> 

No worries, I understand it. For sure it's not your fault!

**Comment by MiquelRForgeFlow** [comment]
@manuelregidor could you rebase please?

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@MiquelRForgeFlow @pedrobaeza this one can be merged 👍

**Pull request merged**
