### PR TITLE
[11.0] stock account: migrate account_move_ids, value, remaining_value and remaining_qty for stock.moves

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
This is a first proposal, I'm open to advice and opinions on the approach I'm following.

### CODE REVIEW

**Comment by mreficent** [comment]
```
./addons/stock_account/migrations/11.0.1.1/post-migration.py:134:33: W291 trailing whitespace
./addons/stock_account/migrations/11.0.1.1/post-migration.py:136:57: W291 trailing whitespace
./addons/stock_account/migrations/11.0.1.1/post-migration.py:144:33: W291 trailing whitespace
./addons/stock_account/migrations/11.0.1.1/post-migration.py:171:34: W291 trailing whitespace
./addons/stock_account/migrations/11.0.1.1/post-migration.py:173:57: W291 trailing whitespace
./addons/stock_account/migrations/11.0.1.1/post-migration.py:181:33: W291 trailing whitespace
```

**Comment by LoisRForgeFlow** [comment]
This is no longer a WIP (@mreficent could you remove the label?). It is a improvement of what it was available, there is room for more improvements for sure but they are not in my short term plans, so from my side this is ready to merge.

**Comment by pedrobaeza** [comment]
@mreficent have you reviewed this one? I have nothing to say about this.

**Comment by MiquelRForgeFlow** [comment]
I don't have reviewed it, but I know that these changes are tested by @lreficent and @jbeficent and used in production and they worked fine. So I think we can proceed with the merge without worrying.

**Comment by pedrobaeza** [comment]
OK, I'm assuming the risk on clicking on merge button :stuck_out_tongue:

**Pull request merged**
