### PR TITLE
[11.0][FIX] remove unwanted migrations directory (2.0, 9.0.1.1)

### PR DESCRIPTION
**Pull request by njeudy**
Some directory prevent from running openupgrade 11.0 script in french 10.0 databases :)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hbrunn** [comment]
I can imagine the 2.0 folder interferes, but do the 9... too?

**Comment by njeudy** [comment]
@hbrunn we are migrating from 10.0 to 11.0 so no need to have all migration directory I think. 9.0.1.1 is in V9 openupgrade branch .. 

less code, clean fonctionnality ...

**Comment by hbrunn** [comment]
the thing is that we regularly merge from upstream, and if ever they change something on this scripts, we'll have to do manual stuff to fix the conflict. So the risk is worth it imho if the existing scripts break something, but if it's only for cleaning up, I'd prefer to not to

**Comment by njeudy** [comment]
I will try with 9.0.1.1 directory.

**Comment by StefanRijnhart** [comment]
The 2.0 migration is actually part of Odoo 11.0, see https://github.com/odoo/odoo/commit/9a2b9b1ae1dc77ad9a59de585e22388dd2a5f828! As @hbrunn is right and the 9.0.x.x scripts should not intervene I'm closing this.

**Comment by njeudy** [comment]
@StefanRijnhart but openupgrade script failed with 2.0 folder. How can we handle this ?

V10.0 -> V11.0 with l10n_fr fail with .. we need to handle this I think.

**Comment by StefanRijnhart** [comment]
@njeudy it depends on how it fails. Is the function already covered by OpenUpgrade 11, or does it not apply to existing installations (only fresh installations of Odoo 11 before this 2.0 script was added?)?

**Pull request closed without merging**
