### PR TITLE
[15.0][OU-FIX] website: Fix extract_footer_copyright_company_nam script

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
Fix the way to get the views

cc @Tecnativa TT44254

@chienandalu @pedrobaeza please review

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please document correctly the commit message:

```
[OU-FIX] website: Extract copyright information from existing website

Previous code was ignoring possible customizations on the copyright information,
as it took it from the master template. With this change, the information is
taken from the customized template if exists, or the master otherwise, using
the existing CoW mechanism for getting it in a simple way.
```

**Comment by pilarvargas-tecnativa** [comment]
> Please document correctly the commit message:

Done! Thanks

**Comment by pedrobaeza** [comment]
The first line of the commit message is not the one I have put.

**Comment by pilarvargas-tecnativa** [comment]
> The first line of the commit message is not the one I have put.

Sorry, I had only read the message

**Comment by pedrobaeza** [comment]
And check also about the `sub` option.

**Comment by pilarvargas-tecnativa** [comment]
> And check also about the `sub` option.

Done!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
