### PR TITLE
project_issue: migration improvements

### PR DESCRIPTION
**Pull request by red15**

### CODE REVIEW

**Comment by red15** [comment]
May fix issue #108 , please test and confirm.

**Comment by hbrunn** [comment]
:+1:  Other reviewers: Let's push this one through quickly and see what the other project_issue related PRs add afterwards

**Comment by pedrobaeza** [comment]
This is the same as #122.

As I'm waiting for one PR to be integrated in this branch, that it's very close to this one, I vote for fast-tracking this one.

:+1:

**Comment by pedrobaeza** [comment]
@red15 For avoiding duplicate work, I recommend you first to see what are the pendings PRs and issues.

**Comment by red15** [comment]
@pedrobaeza I agree, it's not always easy to see find but in this case I should've been able to see it.

Also it seems @legalsylvain is not actively tracking the merge requests that he made (can't blame him for that, he probably got things working for him and decided to not put much effort in "selling" these improvements) which is why I would propose to take this merge request which avoids the the use of `openerp.pooler`

**Comment by pedrobaeza** [comment]
Indeed, he already made a huge work, and in theory he gave me permissions over his branch to change things, but I couldn't make any commit, and I made a PR against his branch yesterday with the same changes as you propose. For this case, we can use this branch as reference and close the other PR.

**Comment by StefanRijnhart** [comment]
@pedrobaeza offtopic, but maybe we can create an openupgrade-dev team on GitHub to collaborate on these contributions?

**Comment by pedrobaeza** [comment]
@StefanRijnhart, yeah, that can be a solution, but everyone that collaborates should be pre-included in that team and make the PR as the team, so I don't know if we are going to get the expected result. Other possibility is to make a direct PR with the new and the initial changes, closing old PR.

About this one, do you approve it to proceed with the merge?

**Comment by StefanRijnhart** [comment]
I created @OpenUpgrade-dev with some core members. Other members (non committers also) should be able to join to take shared responsability on scripts.

**Comment by StefanRijnhart** [comment]
:+1:, Thanks @red15

**Comment by ploegvde** [comment]
How do you join?

**Comment by StefanRijnhart** [comment]
@erwin-bas-solutions I can add proven contributors. Let me know

**Comment by diellenne** [comment]
The new @OpenUpgrade-dev seems a good idea. :+1:
If is ok for you i'm gonna add some extra members that are collaborating with me on onesteinbv openupgrade project.

**Comment by legalsylvain** [comment]
@red15 : I'm not active on OpenUpgrade because I have no time for that. I'm not selling OpenUpgrade features.
@StefanRijnhart, @all : If you want, I can change the owner of all my "OpenUpgrade" PR (from OnesteinBV), from GRAP organization to "OpenUpgrade-Dev".
I don't wanna block process.

Let me know.
Regards.

**Comment by pedrobaeza** [comment]
HI, @legalsylvain, I understand you about your time, so please change the owner to advance with all the current PRs.

**Comment by legalsylvain** [comment]
Addendum: Quite annoying, I can't change the owner of a PR, only the owner of the whole project.
So, if you want:
https://github.com/grap-openupgrade/OpenUpgrade (with 14 PR of OnesteinBV)
can replace
https://github.com/OpenUpgrade-dev/OpenUpgrade/ (only on simple PR of @hbrunn  we can merge quickly).

let me know.

**Comment by pedrobaeza** [comment]
Maybe you can simply add to team grap-openupgrade the other team (OpenUpgrade-dev)?

**Comment by legalsylvain** [comment]
I can't add an organization as a member of an organization. (or I don't know how to do that)
So I added all member of Openupgrade-dev to grap-openugprade. Maybe it's not the best / definitive solution, but it avoid to block your works.
@pedrobaeza  BTW, you can now commit on the project. (I didn't give the good right to the team "commiters", but I changed it).
Can you test again ?

Regards.

**Comment by legalsylvain** [comment]
We have changed the ownership of the project that had the OnesteinBV PRs.
You can now work on them here :
https://github.com/OpenUpgrade-dev/OpenUpgrade

Regards.

**Comment by legalsylvain** [comment]
@all: As the project has the same name, but it's not the same, maybe a clear "git clone" will be required, if you was working on openupgrade-dev/openupgrade Project.

Regards

**Pull request merged**
