### PR TITLE
[15.0][OU-FIX] Migration scripts were not run during install

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Port of https://github.com/OCA/OpenUpgrade/pull/3155

Fixes: #3285

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by jcdrubay** [comment]
Thanks @StefanRijnhart :)

**Comment by pedrobaeza** [comment]
Hi, @StefanRijnhart I'm facing a problem with this patch in v16. I have added migration scripts in https://github.com/OCA/account-analytic/pull/646, but they are not executed in the module installation:

image

Maybe the framework has changed in this version?

**Comment by StefanRijnhart** [comment]
@pedrobaeza Yes indeed, a new install is being termined in an earlier phase now, and used to avoid calling `migrate_module`: https://github.com/odoo/odoo/commit/0e2b2c9c8a9fa53e80df7e0f9ae1f39275315460#diff-250c832b5654555cb37bc4e064c7d69e0c970ce2b0f5eba5301d94b9e973c8d2R173

**Comment by pedrobaeza** [comment]
Thanks for the research. I was about to propose the `pre_init_hook` as well, as you may not have `openupgrade_framework` available when installing this module later. Doing the changes.

**Pull request merged**
