### PR TITLE
[15.0][OU-ADD] website_google_map: Nothing to do

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT37329

NOTHING TO DO

### CODE REVIEW

**Comment by ernestotejeda** [comment]
ping @pedrobaeza

**Review by pedrobaeza — COMMENTED** [review]
Change the commit message to:

```
[OU-ADD] website_google_map: Nothing to do
```

**Comment by ernestotejeda** [comment]
Done

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
