### PR TITLE
[11.0][REN] openupgrade: Rename stock_pack_operation_quick_lot --> stock_move_quick_lot

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@sergio-teruel Is it a merge of one module to another or is it a rename? I ask it because the commit message puts it's a rename but in the code I see you put it in the merged module list.

**Comment by sergio-teruel** [comment]
It is only module rename...

**Comment by MiquelRForgeFlow** [comment]
The your line should go in the other dictionary.

**Comment by sergio-teruel** [comment]
Sorry!!  I had not noticed about the incorrect dictionary.
@mreficent Changes done!!

**Review by StefanRijnhart — APPROVED** [review]
Good catch ;-)

**Pull request merged**
