### PR TITLE
[ADD] account

### PR DESCRIPTION
**Pull request by hbrunn**
this is #528 with a small fix to make if pass runbot hopefully

### CODE REVIEW

**Comment by hbrunn** [comment]
@OCA/openupgrade-maintainers yay, it's green!

**Comment by StefanRijnhart** [comment]
In order not to break the optimistic flow, can you please remove all the done TODOs so that we can easily grep for what is really left to do?

**Comment by hbrunn** [comment]
@StefanRijnhart done

**Comment by StefanRijnhart** [comment]
Thanks!

**Pull request merged**
