### PR TITLE
[8.0][FIX] procurement,stock: flake8

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why commenting things?

**Comment by MiquelRForgeFlow** [comment]
Because if not, we have the flake8 F401 error of 'imported but unused'

**Comment by pedrobaeza** [comment]
There's no correspondence of what you are saying with the commented code. They are even calling to external methods of openupgradelib or executing a query...

**Comment by MiquelRForgeFlow** [comment]
> There's no correspondence of what you are saying with the commented code.

Let's see.

> Why commenting things?

The only commented things of the code are:

Selection_128
Here `pool` is commented because is not used.

Selection_129
Here I am not commenting anything, just moving the align.

And the rest of the code is just deleting trailing spaces and unused imports. Where is your issue?

**Review by pedrobaeza — APPROVED** [review]
Sorry, my fault. I was seeing the commenting code as the diff, but it's not part of it. It was there before...

**Pull request merged**
