### PR TITLE
[12.0][FIX] stock: avoid duplicated putaway strategies (fixup)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Fixup of https://github.com/OCA/OpenUpgrade/pull/3118. Properly detect the template ones.

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Don't we need again then to reintroduce sequence + 1 for giving less priority to template ones?

**Comment by MiquelRForgeFlow** [comment]
No, I think the sequence should be preserved from stock_putaway_product module.

**Comment by pedrobaeza** [comment]
If you look at the code, they were processed after independently from the sequence and only if no specific product variant is set:

https://github.com/OCA/stock-logistics-warehouse/blob/12.0/stock_putaway_product_form/models/putaway_strategy.py#L46

so we can't merge both or we will have different behavior. The way to do that is through sequence. I would say even more: let's put a sequence + 10000 for avoiding coincidences.

**Comment by MiquelRForgeFlow** [comment]
stock_putaway_product_form module doesn't exist in v11.

**Comment by pedrobaeza** [comment]
Ah, which one is then?

**Comment by MiquelRForgeFlow** [comment]
stock_putaway_product in v11, has a sequence field, but I don't see it being used as you describe, but yes, there exist a preference of variant over template in https://github.com/OCA/stock-logistics-warehouse/blob/11.0/stock_putaway_product/models/product_putaway.py#L33.

**Comment by MiquelRForgeFlow** [comment]
I mean, in the queries, first are put the variant with the sequence of the variant, and later are put the templates with the sequence of the templates. As we avoid duplication, the sequence of the variant prevail. Then I don't see why we should modify the sequence.

**Comment by pedrobaeza** [comment]
Take this example:

Variant strategies with sequences 10, 11 and 12
Template strategies with sequences  1, 2 and 3

The template strategy will prevail now over the variant one if you don't modify the sequence for the templates when mixing both, changing the previous behavior.

**Comment by MiquelRForgeFlow** [comment]
Yeah, I know your point. But my point was that in stock_putaway_product, both variants and templates are mixed with the same sequence, and is responsibility of the user of stock_putaway_product module to check the sequence and choose priorities. Later, after migration and merge of that module into stock, my point was to respect that sequence and priority. But hey, that's not blocking for me, I will pump the sequence for templates.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
