### PR TITLE
[ADD] main coverage file

### PR DESCRIPTION
**Pull request by legalsylvain**
**FIX CI** 
- exclude noupdate_changes.xml
- doc : point to correct 130-140 file

**scripts**
- fill apriori.py file

**Doc**
- generate 140-150 coverage file, based on https://github.com/OCA/server-tools/pull/2206.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The sorting is important though

**Comment by StefanRijnhart** [comment]
Can we prevent `upgrade_analysis` and other non-core modules from showing up here?

**Comment by MiquelRForgeFlow** [comment]
> Can we prevent upgrade_analysis and other non-core modules from showing up here?

In [the excluded modules](https://github.com/OCA/server-tools/blob/15.0/upgrade_analysis/blacklist.py), you have to put all non core modules if you are running it with other OCA repos.

**Comment by StefanRijnhart** [comment]
> > Can we prevent upgrade_analysis and other non-core modules from showing up here?
> 
> In [the excluded modules](https://github.com/OCA/server-tools/blob/15.0/upgrade_analysis/blacklist.py), you have to put all non core modules if you are running it with other OCA repos.

Not really, because records are generated for all installed modules, including `upgrade_analysis` which is required to be installed to generate the analysis.
I was thinking along the lines to filter out any non-odoo module in this report because, well, that's the scope of the report.

**Comment by legalsylvain** [comment]
I propose to talk of the topic here. https://github.com/OCA/server-tools/pull/2206
as this PR is just a result.

**Comment by legalsylvain** [comment]
regarding the del modules, a **very quick** first analysis provides the following : 

- ``account_edi_extended``. merged into ``account_edi``
- ``adyen_platforms``. Not found.
- ``crm_iap_lead`` renamed into ``crm_iap_mine``
- ``crm_iap_lead_enrich`` renamed into ``crm_iap_enrich``
- ``l10n_be_invoice_bba`` merged into ``l10n_be``.
- ``l10n_ch_qr_iban`` merged into ``l10n_ch``
- ``l10n_eu_service`` renamed into ``l10n_eu_oss``
- ``l10n_se_ocr`` merged into ``l10n_se``
- ``mail_client_extension`` renamed into ``mail_plugin``
- ``odoo_referral`` : Not found.
- ``payment_fix_register_token`` : merged into ``payment``
- ``payment_ingenico`` renamed into ``payment_ogone``
- ``odoo_adyen_account_id`` : Not found.
- ``_action_launch_stock_rule`` : merged into ``sale_stock``
- ``sale_timesheet_edit`` : merged into ``sale_timesheet``
- ``sale_timesheet_purchase`` :  Not found.
- ``website_event_track_exhibitor`` merged into ``website_event_exhibitor``
- ``website_form`` merged into ``website``
- ``website_mail_channel`` : Not found.
- ``website_sale_management`` merged into ``website_sale``

@OCA/openupgrade-maintainers : could you take a look on that proposal ? 
If you confirm, I could update the apriori file to have a more precise analysis files.

kind regards.

**Comment by pedrobaeza** [comment]
Yes, I confirm, except `_action_launch_stock_rule` that I don't locate

**Comment by legalsylvain** [comment]
> Yes, I confirm, except _action_launch_stock_rule that I don't locate

My bad. Bad copy paste  i was talking about procurement_jit, merged into sale_stock.

_action_launch_stock_rule is a function i was looking for.

Thanks for the review.

**Comment by legalsylvain** [comment]
For me, this is ready to merge.

CC : @StefanRijnhart, @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]

**Comment by legalsylvain** [comment]
thanks for your reviews !

**Pull request merged**
