### PR TITLE
[MIG] hr_expense: migration scripts

### PR DESCRIPTION
**Pull request by cubells**
cc @Tecnativa

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Why don't you include the cherry-pick of https://github.com/OCA/OpenUpgrade/pull/1001?

**Comment by StefanRijnhart** [comment]
Thanks @cubells. Agree with @mreficent that it is not acceptible to commit someone else's code as your own. To force a resolution, I merged #1001 so that you can rebase on that. Please note, I **do** highly appreciate your continuation of the work on the migration of this module!

**Comment by cubells** [comment]
Thanks @StefanRijnhart @mreficent 

I was going to do cherry-pick but I'm too busy now.

I'll do the changes later.

**Comment by MiquelRForgeFlow** [comment]
Why Travis is red?

**Review by pedrobaeza — APPROVED** [review]
Fixed and green CI, so I merge.

**Pull request merged**
