### PR TITLE
[16.0][OU-ADD] auth_signup: Nothing to do

### PR DESCRIPTION
**Pull request by marielejeune**

### CODE REVIEW

**Review by remytms — CHANGES_REQUESTED** [review]
I think that the `noupdate_changes.xml` contains changes in some `mail.template` that should be loaded.

You can check the documentation here: https://github.com/OCA/OpenUpgrade/pull/3864/files

It helped me a lot. :) Also there is know bug with the method `delete_record_translations()` as Pedro spotted it here: https://github.com/OCA/OpenUpgrade/pull/3899#discussion_r1215541893

**Comment by remytms** [comment]
I think that this is not blocked by dependency anymore. `base_setup`, `mail` and `web` has been merged. :)

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Ouch, I didn't see the other comment about the noupdate_changes... Please add such migration script.

**Comment by marielejeune** [comment]
Sorry for the delay. See https://github.com/OCA/OpenUpgrade/pull/3917

**Pull request merged**
