### PR TITLE
[12.0][FIX] openupgrade_records: consider 'reference' type

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Should I backport it to previous versions?

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart do you know why now in all PRs appears this and how to solve it?

Selection_084

**Comment by StefanRijnhart** [comment]
Because there is now a branch 11.0-ocabot-merge-pr-2015-by-pedrobaeza-bump-no on the project, which matches the crude grep expression. 

Try replacing `git ls-remote | grep refs/heads/11.0 | awk '{print $1}'` with `git rev-parse origin/11.0`

**Comment by pedrobaeza** [comment]
Let's remove the branch any way. It's a fail bot merge operation

**Comment by StefanRijnhart** [comment]
I see you need to do a `git fetch origin 11.0` first, because otherwise you get `unknown revision or path not in the working tree.`

**Comment by MiquelRForgeFlow** [comment]
> I see you need to do a `git fetch origin 11.0` first, because otherwise you get `unknown revision or path not in the working tree.`

There is already a `git fetch --depth 2 origin 11.0`.

**Comment by pedrobaeza** [comment]
For me this is not useful, as explained directly to @mreficent by chat.

**Pull request closed without merging**
