### PR TITLE
[FIX] to be able to detect if migrate.py was successful

### PR DESCRIPTION
**Pull request by ap-wtioit**
add exit codes to migrate.py

Description of the issue/feature this PR addresses:
The migrate.py script currently gives no indication in the exit/return code whether it was successful or not.

Current behavior before PR:
migrate.py always exits with 0 (OK) return code

Desired behavior after PR is merged:
migrate.py should indicate if the script was executed successful in its return code

Info @wt-io-it

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This script is deprecated since 2 versions, so I'm not sure we should continue using it...

**Comment by pedrobaeza** [comment]
After talking, it seems that it's still working on v11, so let's update it, but you have to fix lint errors:
```
scripts/migrate.py:373:27: E128 continuation line under-indented for visual indent
scripts/migrate.py:374:27: E128 continuation line under-indented for visual indent
scripts/migrate.py:457:1: W391 blank line at end of file
```

**Comment by js-landoo** [comment]
Hi @ap-wtioit 
Could you please update @pedrobaeza requested changes, to fix lint errors?

Many thanks!

**Comment by ap-wtioit** [comment]
@js-landoo i already fixed the linting errors in https://github.com/OCA/OpenUpgrade/pull/1370/commits/d76fcbb929c6c722ddf3d2cf40f4ab3d9b55884b, the build is now ok

**Review by pedrobaeza — APPROVED** [review]

**Comment by js-landoo** [comment]
Hi Andreas and Pedro.
It's great to see the work done!!
Thanks.

**Pull request merged**
