### PR TITLE
[11.0][MIG] web

### PR DESCRIPTION
**Pull request by kaerdsar**
Rename some views existing before in report module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Merging before travis has run because the base module has not yet been migrated anyway so the build will fail.

**Review by MiquelRForgeFlow — CHANGES_REQUESTED** [review]
update documentation

**Review by MiquelRForgeFlow — CHANGES_REQUESTED** [review]
here https://github.com/OCA/OpenUpgrade/blob/11.0/odoo/openupgrade/doc/source/modules100-110.rst

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
thanks to @pedrobaeza for noting that the entries need to be moved from base to web because the module will be merged into base in an earlier stage.

**Comment by pedrobaeza** [comment]
As discussed, we block this until base module is merged.

**Comment by MiquelRForgeFlow** [comment]
base migration was added.
@kaerdsar, please rebase the PR

**Comment by kaerdsar** [comment]
@mreficent I already updated the branch.

**Comment by StefanRijnhart** [comment]
@kaerdsar thanks. I see you merged in the main branch instead of a rebase of your own branch against the main branch (`git rebase -i origin/11.0`) + forced push. I'll squash commits therefore.

**Pull request merged**
