### PR TITLE
[FIX] stock migration script

### PR DESCRIPTION
**Pull request by pedrobaeza**
Final attempt of fixing stock migration. Still in progress

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This can be considered now tested and ready to be reviewed

**Comment by sebalix** [comment]
I'm quite new to the new way to manage stock in v8.0, but is there any drawback to make the migration 7.0 -> 8.0 without this PR? Or is it only to preserve a consistent history?

**Comment by parthivgls** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Well, basic operation of creating quants is already covered, but stock.pack.operation isn't, which can lead to inconsistencies in pickings pre and post-migration. Also the serial number is now assigned in quant creation for this pickings, instead of needing to visit again all the created quants.

**Comment by sebalix** [comment]
Thank you, so I will do the migration with your branch while it's not merged (I'm not familiar enough with this subject to upvote this PR, others will do surely!)

**Comment by pedrobaeza** [comment]
You can do that, check that all was correct, and then put your thumb up here.

**Comment by sebalix** [comment]
Tested and all seems correct at a first glance, so :+1:

**Pull request merged**
