### PR TITLE
[13.0][OU-FIX] #2339, set noupdate of ir.model XMLIDs to FALSE

### LINKED ISSUE #2339: [13.0] duplicate key when renaming needaction_partner_ids to notified_partner_ids
Impacted versions: 13.0 (testing with all open 13.0 PR aggregated)

Steps to reproduce: Run openupgrade 8->9, 9->10, ..., 12-13.

Current behavior: 

In the 12->13 step:

```
bad query: 
            UPDATE ir_model_fields
            SET name = 'notified_partner_ids'
            WHERE name = 'needaction_partner_ids'
                AND model = 'mail.message'
            
ERROR: duplicate key value violates unique constraint "ir_model_fields_name_unique"
DETAIL:  Key (model, name)=(mail.message, notified_partner_ids) already exists.
```

This is apparently because `notified_partner_ids` was a thing in v8, then disappeared, then reappeared in v13.

Not sure if this is something I'm doing wrong (do I need to do some cleanup between steps?) or if it's something that has to / can be fixed. I can try to provide a fix if you think it's useful and give me a hint on how to approach this.

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Fixes #2339

Also
    
* Remove redundant update_fields_xmlid method and add tests
* fixes broken migration tests mechanism
* fix unreleased savepoint
* improve logging when deletion fails (should be rare now)
* reduce logging of deletions in CI

This PR is part of a set of PRs for OpenUpgrade 9.0 up to 13.0. Background:

While Odoo deletes obsolete field and model entries from the data model
metadata explicitely in their migration scripts, in OpenUpgrade I have
always meant to rely on the mechanism of purging 'untouched' XMLIDs that
takes care of the deletion of obsolete data records (e.g. views).

However, this mechanism was not applied to field and model entries because
their XMLIDs were created with noupdate NULL instead of FALSE and as such
excluded in the query to gather all obsolete data records.

Also missing was marking the XMLIDs of fields and models as `loaded` in the
first place.

All of this is working properly in Odoo 13 (introduced gradually across new
releases) so all of this is backported from newer versions one way or
another.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
> However, this mechanism was not applied to field and model entries because
> their XMLIDs were created with noupdate NULL instead of FALSE and as such
> excluded in the query to gather all obsolete data records.

That's not true in v13, because https://github.com/odoo/odoo/pull/32881 fixed that in v13 and newer.

**Comment by StefanRijnhart** [comment]
@MiquelRForgeFlow the commit message is largely the same for all 6 related branches. I mention version 13.0 explicitely further down as the release in which all of that is working indeed, and the scope of this particular PR is limited to setting noupdate to false where it is still null, plus testing.

**Comment by StefanRijnhart** [comment]
@MiquelRForgeFlow OK, I went all the way and described the actual list of changes per PR. I hope you like it better now!

**Comment by MiquelRForgeFlow** [comment]
Good! Very nice! :+1:

**Review by hbrunn — APPROVED** [review]

**Pull request merged**
