### PR TITLE
Create odoo-bin

### PR DESCRIPTION
**Pull request by mahmoudelsaka**

### CODE REVIEW

**Comment by mahmoudelsaka** [comment]
add odoo-bin file

**Comment by legalsylvain** [comment]
I don't get it. could you explain why you add this file. 
In theory, you just have to call the odoo-bin file of the regular odoo/odoo repository.

thanks.

**Comment by pedrobaeza** [comment]
This seems a hacktoberfest attempt to get t-shirt, so closing.

**Comment by mahmoudelsaka** [comment]
Hi,

I need to add this file because while upgrade database from V13 to V14 i
got this error
sh: 1: /var/tmp/openupgrade/14.0/server/odoo-bin: not found


*--Warm Regards,*

*Mahmoud Elsaka*
Mob: - (+2)01091426388   //(Call & WhatsApp)

**Comment by pedrobaeza** [comment]
You are not following correctly the steps for performing the migration: https://oca.github.io/OpenUpgrade/migration_details.html or your paths are not correct.

**Comment by mahmoudelsaka** [comment]
The OpenUpgrade repository includes both openupgrade_framework and
openupgrade_scripts:
The both files do not exist in Openupgrade for branch 13.0.


*--Warm Regards,*

*Mahmoud Elsaka*
Mob: - (+2)01091426388   //(Call & WhatsApp)

**Comment by pedrobaeza** [comment]
Since v14, you have to use odoo/odoo along with the framework. This way, we have lighted up a lot this repo.

**Pull request closed without merging**
