### PR TITLE
[10.0][product]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Adds migration scripts for the 'product' module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Preserve dropped fields (renaming them to None) if someone is using them on other modules:

* 'sequence' on product.category
* 'state' on product.template

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Thanks. As a general rule in all migrations we I will always preserve the fields that are dropped. This has certainly proven to be extremely useful.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza This is now done.

**Review by NL66278 — APPROVED** [review]
:+1:  Tested this in database with demo data and worked

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
