### PR TITLE
[ENH] Actually process module renames.

### PR DESCRIPTION
**Pull request by NL66278**
Description of the issue/feature this PR addresses:
https://github.com/OCA/OpenUpgrade/issues/646#issuecomment-254475025

Current behavior before PR: Modules not renamed

Desired behavior after PR is merged: Modules renamed
## This PR fixes the rename problem for me. I understood that for others the module rename functionality works. If so, I would like to know how. Creating this PR to hopefully get some answers. And maybe it will be usefull for others with similar problems to mine.

I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this code taken from 8.0? If so, I think the problem is that it's not marked with OpenUpgrade comment or similar to be detected, and it was forgotten in the migration.

**Comment by hbrunn** [comment]
this seems missing in the base migration, in 8, this happens here: https://github.com/OCA/OpenUpgrade/blob/8.0/openerp/addons/base/migrations/8.0.1.3/pre-migration.py#L39

**Comment by NL66278** [comment]
In 9.0 the code called in 8.0 is no longer present.

**Comment by hbrunn** [comment]
it lives in openupgradelib: https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L703

**Review by hbrunn — APPROVED** [review]

**Comment by NL66278** [comment]
@pedrobaeza @hbrunn I changed my PR to use the same logic as in 8.0. Tested this as well and it works (at least for me). Obvious difference is that there will be no longer a row in ir_module_module with the old module name and state 'uninstalled' (like before last commit in my PR). But renaming is much more thorough, because also other tables are updated from update_module_names that is called now.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
We should make the same for 10.0 in base module. @StefanRijnhart, please take into account if you're doing it.

**Comment by StefanRijnhart** [comment]
Thanks. Maybe we should put it in the core somewhere instead of having to put in the base scripts every edition.

**Comment by pedrobaeza** [comment]
Yeah, I have thought about that, but the problem is to not invoke the method each time you restart the migration process, which I don't see possible by now. Well, in fact, nothing will break, but executing a lot of update operations with 0 results each time doesn't seem to me the best method.

**Comment by NL66278** [comment]
If it would be possible to do when the server collects the names of available modules, it would be possible to do this only for modules not yet renamed. Then for each module to be renamed update_module_names could be called with just a single tuple with old name and new name.

**Comment by pedrobaeza** [comment]
Yeah, it can be a good solution.

**Comment by StefanRijnhart** [comment]
Yes, but it's not the names of available modules, but the names of installed modules instead.

**Pull request merged**
