### PR TITLE
[ADD] rename account_payment to account_payment_order

### PR DESCRIPTION
**Pull request by hbrunn**
I'm not so sure about this one, what do you think?

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
you are mapping a standard module to an OCA module. Does not sound 100% correct to me. Maybe we should make this dependent on the presence of another OCA payment related module?

**Comment by pedrobaeza** [comment]
I don't see a special problem with that while we have migration scripts in the _account_payment_order_. Both modules share most of the models, but the script is mandatory.

**Comment by hbrunn** [comment]
yes, the migration script will be necessary. Setting this to work in progress meanwhile

**Comment by hbrunn** [comment]
@StefanRijnhart it's a module that replaces lost functionality, so I don't think that's a big issue. Probably we'll encounter more of this the more vital stuff is moved from community to enterprise...

**Comment by pedrobaeza** [comment]
Yeah, we have the same with contract module for example, or account_followup...

**Comment by pedrobaeza** [comment]
FYI, we are working on this now.

**Comment by pedrobaeza** [comment]
OK, this is the map:

- [x] account_payment > account_payment_order: This one
- [x] account_payment_order: https://github.com/OCA/bank-payment/pull/325
- [x] account_payment_mode: https://github.com/OCA/bank-payment/pull/320
- [x] account_banking_mandate: https://github.com/OCA/bank-payment/pull/321
- [x] account_payment_partner: https://github.com/OCA/bank-payment/pull/322
- [x] account_banking_pain_base: https://github.com/OCA/bank-payment/pull/324

**Comment by hbrunn** [comment]
now that https://github.com/OCA/bank-payment/pull/320 is merged, we can merge this, right?

**Comment by pedrobaeza** [comment]
There is still one PR pending, that I'm checking right now (OCA/bank-payment#325). I'll merge when finish.

**Comment by pedrobaeza** [comment]
@hbrunn, we need to merge before https://github.com/OCA/openupgradelib/pull/63. Please check.

**Comment by pedrobaeza** [comment]
All merged, so merging this one also.

**Pull request merged**
