### PR TITLE
[16.0][OU-ADD] website_crm: Nothing to do

### PR DESCRIPTION
**Pull request by victoralmau**
Nothing to do

Depends on:
- [x] https://github.com/OCA/OpenUpgrade/pull/3949

@Tecnativa TT43628

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration website_crm

<dependency></dependency>

**Review by marielejeune — APPROVED** [review]
LGTM

**Review by robinkeunen — APPROVED** [review]
Nothing to do, LGTM 👌

**Comment by robinkeunen** [comment]
A rebase after the merge of https://github.com/OCA/OpenUpgrade/pull/3949 should fix the tests.

**Comment by victoralmau** [comment]
Rebase done.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
