### PR TITLE
[8.0][UPD] several merges

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This PR adds some modules in the merge script.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why is Travis failing?

**Comment by MiquelRForgeFlow** [comment]
I don't know, but it has nothing to do with this PR.

selection_019

**Comment by MiquelRForgeFlow** [comment]
Travis of branch v8 is failing due to https://github.com/OCA/OpenUpgrade/pull/730.

**Comment by pedrobaeza** [comment]
OK, I merge this now and investigate the problem with the other PR.

**Pull request merged**
