### PR TITLE
[FIX] hr_timesheet: Project filling fix

### PR DESCRIPTION
**Pull request by pedrobaeza**
There can be timesheet analytic lines that are not linked to a task nor an issue.
We need to link them to the associated project of the analytic account.

### CODE REVIEW

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

**Comment by JordiBForgeFlow** [comment]
I am concerned about timesheet lines entered against pure analytic accounts, not linked to projects. This was allowed in v9.

Perhaps in project module we need to create projects for those, or perhaps here, since it is the only place where there could be a break in consistency.

**Review by rafaelbn — APPROVED** [review]
👍 
In other case after migration from v9 to v10 you will not see in Timesheets -> Activities any activity which was not linked to a task or issue in v9

**Comment by pedrobaeza** [comment]
@jbeficent that's what this PR does: fill lines with the project for still being considered as "timesheet lines". Previously, we have created projects for those analytic lines that don't have it (https://github.com/OCA/OpenUpgrade/pull/1055/files#diff-87d2c9f7c3a0d64a5388d7dd4daf3dacL21)

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
Oh, you're right. :+1:

**Pull request merged**
