### PR TITLE
[ADD] rename website_mail_group to website_mail_channel

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please update also documentation

**Comment by pedrobaeza** [comment]
Any news on this, Holger?

**Comment by hbrunn** [comment]
done

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request merged**
