### PR TITLE
[12.0][DOC] account: explain why disabling a rule

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Attends https://github.com/OCA/OpenUpgrade/issues/1859.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What do you think about reverting my original idea of emptying `company_id` in all existing payment terms? This is for making use of the new feature from now on.

**Comment by MiquelRForgeFlow** [comment]
The problem I see is that the `company_id` in payment terms is **required**.

**Comment by MiquelRForgeFlow** [comment]
@jbeficent could you approve?

**Review by pedrobaeza — APPROVED** [review]
Let's move on on this

**Pull request merged**
