### PR TITLE
[9.0][IMP] re-enable used currencies

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I think the criteria is very partial, as you can use currencies in invoices without being assigned in an account. Maybe it's better to not include the noupdate data?

**Comment by hbrunn** [comment]
why not add the invoice currency to the union too? I think it's a good thing that Odoo deactivates most currencies there, we just don't want used ones to be deactivated

**Comment by pedrobaeza** [comment]
OK then.

**Comment by hbrunn** [comment]
added the union over invoices

**Review by pedrobaeza — COMMENTED** [review]
This will update as much times as records for each table, isn't it? Shouldn't you need to use `DISTINCT(currency_id)`?

**Comment by hbrunn** [comment]
no, union (without all) takes care of duplicates

**Comment by pedrobaeza** [comment]
Good to know, thanks.

**Pull request merged**
