### PR TITLE
[15.0][IMP] base: update uninstallable modules state from installed to uninstallable  to avoid warning

### PR DESCRIPTION
**Pull request by royle-vietnam**
Example:
`module adyen_platforms: not installable, skipped`

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't get the exact use case, but I would say that this is not correct. If `adyen_platforms` disappears, there should be an specific instruction merging it with other module or you should manually uninstall it on target, but not to magically do it disappear.

**Comment by royle-vietnam** [comment]
> I don't get the exact use case, but I would say that this is not correct. If `adyen_platforms` disappears, there should be an specific instruction merging it with other module or you should manually uninstall it on target, but not to magically do it disappear.

When I have module that is not available on target (e.g. not upgraded)

**Comment by pedrobaeza** [comment]
I still don't understand.

**Comment by royle-vietnam** [comment]
In a cross version migration, I have module X in version 13, but I don't have module X in version 14, but target is version 15, and I have such module in version 15

**Comment by pedrobaeza** [comment]
For that use case, you don't have to do anything, simply let the warning in version 14. If you do this, you won't have in version 15 the module marked as installed and no migration will be done.

**Comment by royle-vietnam** [comment]
Closed because it is not necessary

**Pull request closed without merging**
