### PR TITLE
5.0 port

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Port of lp:openupgrade-server/5.0 onto GH odoo/odoo 5.0.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What a huge diff! I have made a brief sight, and looks correct.

:+1:

**Comment by StefanRijnhart** [comment]
Thanks for the review! Yes it is a big diff, but the changes are verbatim to lp:openupgrade-server/5.0. That means you can verify that the openupgrade_records module and the openupgrade directory are the same using diff for instance. I will be proposing real changes in additional PRs.

**Comment by pedrobaeza** [comment]
Yeah, I see. Waiting for next PRs!

P.S.: Anyone still in 5.0?!

**Comment by StefanRijnhart** [comment]
No, even better: we've a lead to migrate a 4.2 database to 8.0

**Comment by pedrobaeza** [comment]
:astonished: It's like a migration from another system!

**Comment by legalsylvain** [comment]
@StefanRijnhart ! What a big migration !

**Comment by hbrunn** [comment]
I'm not going to try that out, but the code looks fine to me :+1:

**Comment by bwrsandman** [comment]
So, there's a github 5.0 branch and a 8.0 branch now.
Any plans to bring 6.0 - 6.1 - 7.0 here?
This would help out greatly for our buildout recipes.

**Comment by pedrobaeza** [comment]
I have opened #137 for that purpose.

**Comment by bwrsandman** [comment]
@pedrobaeza thank you

**Pull request merged**
