### PR TITLE
[11.0][ADD] website_project_issue: Merged in project

### PR DESCRIPTION
**Pull request by pedrobaeza**
Depends on:

- [x] OCA/openupgradelib#114

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@mreficent you have this PR ready to merge after merging the library function.

**Review by MiquelRForgeFlow — APPROVED** [review]
Low coverage :(

**Comment by pedrobaeza** [comment]
It's not my fault. It has lowed down because the removal of some lines for the added feature, and then the uncovered part have more weight in the total.

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request merged**
