### PR TITLE
[12.0][MIG] event

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Migration scripts for `event` module.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
hahaha it's green despite a lot of its dependencies don't have the migration scripts

**Comment by pedrobaeza** [comment]
Yes, that can happen if the depending modules doesn't break normal update process, although data are not correct (or maybe yes...). Any way, it should be checked in the hierarchy order.

**Comment by MiquelRForgeFlow** [comment]
I see it as a minus minus = plus case :dancer:

**Comment by pedrobaeza** [comment]
I have mixed PRs and merge this one accidentally. There's missing the mail template translation reset. I'll do it directly in a commit.

**Comment by pedrobaeza** [comment]
Done in 235b2acfeb259d8008db272c8a66608814ac8f0d

I have to check if translations way of being stored have been changed in this version so `delete_record_translations` might not work correctly.

**Pull request merged**
