### PR TITLE
[9.0] update from upstream 7cf29f04be

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Merging upstream Odoo up until commit 7cf29f04be352c212ce445dd9753455619d0ac1a, mainly to include the new modules (https://github.com/OCA/OpenUpgrade/commit/f1896c388ff2e470971384c980ee75617b41adc7).

There were three conflicts:

* requirements.txt file:
https://github.com/OCA/OpenUpgrade/commit/6d311f9c477d0420f7912e4b0124e38a0ffe1b17 vs https://github.com/odoo/odoo/commit/6f8efea28cd29fd973ac6a50d7b93f0d73a725c6

```rst
<<<<<<< HEAD
psycopg2==2.7.3.1
=======
psycopg2==2.7.1
>>>>>>> odoo/9.0
```
solved as:
```rst
psycopg2==2.7.3.1
```

* loading.py file:
https://github.com/OCA/OpenUpgrade/commit/3426b638e3970102e0752f7fef053a56b888286f vs https://github.com/odoo/odoo/commit/c2f4e7833931f1c9f1c79187d2ba9f3b2c1c96c7

```rst
<<<<<<< HEAD
def load_module_graph(cr, graph, status=None, perform_checks=True, skip_modules=None, report=None, upg_registry=None):
=======
def load_module_graph(cr, graph, status=None, perform_checks=True, skip_modules=None, report=None,
                      models_to_check=None):
>>>>>>> odoo/9.0
```
and similar in `load_marked_modules` method.

solved as:
```rst
def load_module_graph(cr, graph, status=None, perform_checks=True, skip_modules=None, report=None,
                      models_to_check=None, upg_registry=None):
```

* migration.py file:
https://github.com/OCA/OpenUpgrade/commit/3426b638e3970102e0752f7fef053a56b888286f vs https://github.com/odoo/odoo/commit/b7b82f12670edffc5541c313e1b392fe9ac61465

```rst
                        if hasattr(mod, 'migrate'):
                            mod.migrate(self.cr, pkg.installed_version)
                        else:
<<<<<<< HEAD
                            _logger.error('module %(addon)s: Each %(stage)s-migration file must have a "migrate(cr, installed_version)" function',
                                          strfmt)
=======
                            migrate(self.cr, installed_version)
>>>>>>> odoo/9.0
```
and similar in `load_marked_modules` method.

solved as:
```rst
                        if hasattr(mod, 'migrate'):
                            mod.migrate(self.cr, installed_version)
                        else:
                            _logger.error('module %(addon)s: Each %(stage)s-migration file must have a "migrate(cr, installed_version)" function',
                                          strfmt)
```

I hope I solved them correctly.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you put here and in the commit message of the merge the diff for solving the conflicts? I'm not able to see it through GitHub UI

**Comment by MiquelRForgeFlow** [comment]
Shit, it was green before 😥

**Comment by pedrobaeza** [comment]
It sometimes happens with the checkout to $TRAVIS_COMMIT. I have closed and opened again to trigger a new check.

**Comment by MiquelRForgeFlow** [comment]
:green_apple: :green_apple:

**Comment by StefanRijnhart** [comment]
Looks good, but can you make `upg_registry` always come last in the `load_module_graph` and `load_marked_modules` signatures and calls because that one is ours. Make it a keyword argument if you need to.

**Comment by MiquelRForgeFlow** [comment]
I tried that in the beginning but the problem is that `upg_registry` doesn't have a default in `load_marked_modules` method, and thus, it cannot go after the `models_to_check` that have a default.

**Comment by StefanRijnhart** [comment]
Make it None like we did when we encountered the same change in 10.0: https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/modules/loading.py#L32

**Comment by MiquelRForgeFlow** [comment]
Ok

**Comment by StefanRijnhart** [comment]
Sorry, that does not include the new parameter from Odoo, but you get the idea ;-)

**Comment by StefanRijnhart** [comment]
The new parameter is in OpenUpgrade 11.0: https://github.com/OCA/OpenUpgrade/blob/11.0/odoo/modules/loading.py#L32

**Comment by MiquelRForgeFlow** [comment]
:green_apple: :green_apple:

**Comment by MiquelRForgeFlow** [comment]
Anything else?  😏

**Review by StefanRijnhart — APPROVED** [review]
Perfect, thanks!

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza I let you do the honor of merge.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
