### PR TITLE
[13.0][ADD] website_megamenu: Merged on website

### PR DESCRIPTION
**Pull request by CarlosRoca13**
@Tecnativa TT26952

ping @pedrobaeza @Tardo

### CODE REVIEW

**Review by rconjour — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is there anything more to do or the resulting HTML is the same parsed as block on v13?

**Comment by CarlosRoca13** [comment]
@pedrobaeza The only difference is that in v13 the class o_default_snippet_text is added to all texts. But without this they will be working fine

**Comment by pedrobaeza** [comment]
Uhm, not sure it won't have side effects. I think that class is used for auto-selecting text when selecting the block. @Yajo can you confirm?

**Comment by pedrobaeza** [comment]
@Yajo can you please confirm?

**Comment by Tardo** [comment]
As far as I could see in the code, the 'o_default_snippet_text' class is added by the editor.

**Review by yajo — APPROVED** [review]
Indeed, that's its use.

**Pull request merged**
