### PR TITLE
[IMP] sale: Faster workflow deletion

### PR DESCRIPTION
**Pull request by yajo**
This makes use of the optimized workflow deletion from openupgradelib, saving several hours in the end-migration stage.

@Tecnativa TT18838

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Ouch, you have added this in purchase instead of sale!! I will fix it directly.

**Comment by pedrobaeza** [comment]
Fixed in 075cfa226b29819cae3ba1558fd8b3954c31aff0

**Comment by yajo** [comment]
oops :man_facepalming:

**Pull request merged**
