### PR TITLE
[12.0] update upstream 0662a1948b

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Merging upstream Odoo up until commit https://github.com/odoo/odoo/commit/0662a1948b71ebd46313cbe40774553594f1c9e0.

There were no conflicts.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart Could we merge this PR and then in https://github.com/OCA/OpenUpgrade/pull/1531 could you do a rebase and redo a new analysis?

**Review by rvalyi — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please check Travis result

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza But it's obvious the CI will be red. Until the https://github.com/OCA/OpenUpgrade/pull/1531 gets merged, it will be red.

**Comment by pedrobaeza** [comment]
Oh, sorry, I didn't see that. Merging, please update analysis.

**Pull request merged**
