### PR TITLE
[16.0][OU-ADD] rating: Nothing to do

### PR DESCRIPTION
**Pull request by remytms**
I checked the `upgrade_analysis.txt` file, and as far as I know there is nothing to do.

### CODE REVIEW

**Comment by remytms** [comment]
@pedrobaeza Can you reference this PR with `ocabot migration rating` ? Thanks a lot. :)

**Comment by remytms** [comment]
This is not blocked by dependency anymore, since `mail` has been merged.

**Review by legalsylvain — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
