### PR TITLE
[13.0][FIX] stock_account: wrong sign for svl value of out moves

### PR DESCRIPTION
**Pull request by kos94ok-3D**
image

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kos94ok-3D** [comment]
@AaronHForgeFlow Can you check this?

**Comment by kos94ok-3D** [comment]
https://github.com/OCA/OpenUpgrade/pull/2376

**Comment by AaronHForgeFlow** [comment]
@kos94ok-3D I see, I am checking. Is that the Unit Value or the Total Value?

**Comment by AaronHForgeFlow** [comment]
I think you are correct and I am making a PR to fix that. Still checking.

**Comment by kos94ok-3D** [comment]
@AaronHForgeFlow screen from runbot Odoo13
There are we see that price unit price is always positive, but in stock_move we can have negative
image
image

**Pull request closed without merging**
