### PR TITLE
[12][MIG] product_expiry: Migration script (nothing todo)

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT20173
@Yajo @Tardo review please.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I proceed to merge as it's very straight-forward and OpenUgrade doesn't follow strict OCA review rule (due to the low number of contributors).

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Oh, wait!! You have to update https://github.com/OCA/OpenUpgrade/blob/12.0/odoo/openupgrade/doc/source/modules110-120.rst file with the sentence "Nothing to do" for being recognized by the CI.

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sergio-teruel please remember to add the line in the documentation

**Comment by sergio-teruel** [comment]
Changes done!!

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
