### PR TITLE
[11.0][STOCK] Fix missing serial numbers in stock.move.line

### PR DESCRIPTION
**Pull request by OthmaneGhandi**
Description of the issue/feature this PR addresses:

This PR try to fix my reported issue here #2000 about missing serial numbers in stock.move.line
@pedrobaeza what do you think about this PR 

Is my approach correct or I'm missing something ?

Thanks

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But the problem seems to be in your DB as stated. It's not a general problem. Or is it? If so, please explain the steps to reproduce the problem in regular DB for not having stock_move_operation_link populated.

**Comment by OthmaneGhandi** [comment]
I reproduced these steps : **create a delivery order** (using a product that is tracked by serial number)
**I clicked on Mark as do** -> **reserve** and after that I clicked on the button (see picture) (specified inside which serial numbers to use: 3 serial numbers in my example)

serial numbers

**After that I validated the transfer => done state**

Current result : 
In `stock.pack.operation.lot` : I have the 3 serial numbers (3 records)
In `stock.pack.operation.link`: I have ONE record with qty 3
NB: In `stock.pack.operation.link`  the field `reserved_quant_id` is empty (it was filled before arriving to the done state)
=> That's why I will not get my 3 records with serial numbers with just checking `stock.pack.operation.link `and its connection with `stock.quant`

@pedrobaeza

**Comment by pedrobaeza** [comment]
Oh, well, so the picking is in state reserved? Yeah, in that case you lose that reservation. There's no other way.

**Comment by pedrobaeza** [comment]
Closing this as no further answer and no easy solution (this PR will have several side effects) and it's not the usual thing that you keep serial numbers put but not transferred.

**Pull request closed without merging**
