### PR TITLE
[13.0][IMP] apriori: edi_oca -> edi

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Was done in https://github.com/OCA/edi/pull/877.

It was commented in https://github.com/OCA/OpenUpgrade/pull/4384:
Selection_3378

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't know the history about this, so others are more suitable to judge this move. I see it weird, as AFAIK everything was moved to `_oca` suffix.

**Comment by MiquelRForgeFlow** [comment]
Yeah, in v14 was done the rename from edi to edi_oca. But later, when we made the backport to v12 we used v14 as reference, and we didn't change the module name.

**Comment by pedrobaeza** [comment]
Please @hbrunn can you confirm this is OK?

**Review by hbrunn — APPROVED** [review]
I think we need this indeed for migrating to v13, and then we'll have to rename it back for migrating to v14:

https://github.com/OCA/edi/tree/12.0/edi_oca
https://github.com/OCA/edi/tree/13.0/edi
https://github.com/OCA/edi/tree/14.0/edi_oca

**Pull request merged**
