### PR TITLE
Fix/10.0 malformed table

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Fix malformed table error when building Sphinx documentation, and a warning about an obsolete paper size option.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Thanks for fixing this

**Comment by StefanRijnhart** [comment]
@pedrobaeza thanks for the review but it was still work-in-progress according to the label! Continued here: https://github.com/OCA/OpenUpgrade/pull/1136

**Comment by pedrobaeza** [comment]
Sorry, I didn't see it, but hey a green build is always appreciated :wink:

**Comment by StefanRijnhart** [comment]
Sure ;-)

**Pull request merged**
