### PR TITLE
[15.0][OU-ADD] website_sale_comparison: Nothing to do

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT36599

Depends on:

- [x] https://github.com/OCA/OpenUpgrade/pull/3347

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
Selection_724

**Comment by pedrobaeza** [comment]
Yes, because there's no rebase, but everything is correct in the main branch.

**Comment by pedrobaeza** [comment]
I'm not going to waste a build for something that is green anyway.

**Comment by MiquelRForgeFlow** [comment]
Ah, sorry, I thought it was not merged yet.

**Pull request merged**
