### PR TITLE
[14][IMP] apriori:sale_order_pricelist_tracking to sale 

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc@Tecnativa TT41651

@chienandalu  @pilarvargas-tecnativa please review!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please put it under the `# OCA/whatever` section inside the dictionary (or create it alphabetically if not exists), and also in alphabetical order inside the section.

**Review by legalsylvain — COMMENTED** [review]
should be put in the #OCA/sale-workflow section, after the `sale_order_price_recalculation` line.

**Comment by pedrobaeza** [comment]
`OCA/whatever` shouldn't be literal. I put that because I don't know its source repo. I suppose it's `OCA/sale-workflow`, so that's the section to locate/add.

**Review by chienandalu — APPROVED** [review]

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Pull request merged**
