### PR TITLE
[ADD] hr_holidays migration

### PR DESCRIPTION
**Pull request by hbrunn**
This depends on #112

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please include analysis work file?

**Comment by hbrunn** [comment]
done

**Comment by legalsylvain** [comment]
LGTM. Thanks. :+1:

**Comment by pedrobaeza** [comment]
This one depends on #112, but :+1: when this one is merged.

**Comment by hbrunn** [comment]
this could be merged now as #112 is merged

**Pull request merged**
