### PR TITLE
[13.0][FIX] account: Added extra queries to migrate tags from non-invoice move lines wherever possible.

### PR DESCRIPTION
**Pull request by ddejong-therp**
Sometimes the tags of a move line don't get migrated properly. Currently it only migrates them if the move line belongs to an invoice. However, almost all other cases are forgotten. I've wrote a query that fixes it for move lines that are the result of an hr.expense in https://github.com/OCA/OpenUpgrade/pull/3152 . However, that still doesn't account for all move lines.

I've added queries so that the tax tags of any move lines that have tax_line_id set, can now also migrate. I've left the previous queries in there, as they use the tax tags info of their corresponding invoice, which I guess is still nice to do. However, for those lines which do not have an corresponding invoice, they'll have their tags migrated now too.

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM (not tested, but makes sense)

**Comment by pedrobaeza** [comment]
I think this should be restricted to those lines that don't have the field filled, isn't it?

**Comment by ddejong-therp** [comment]
> I think this should be restricted to those lines that don't have the field filled, isn't it?

You mean the tax_line_id field? The problem is that tax_repartition_line_id field does not get set for some move lines. I use tax_line_id to find an appropriate repartition line id.

**Comment by ddejong-therp** [comment]
Or do you mean the lines which don't have tax_repartition_line_id set?

**Comment by MiquelRForgeFlow** [comment]
I think he refers to type = 'entry'? :S

**Comment by MiquelRForgeFlow** [comment]
> I think this should be restricted to those lines that don't have the field filled, isn't it?

Prior to this method, the field tax_repartition_line_id is empty, so don't need that restriction. About putting it in the following queries beside the first one, I think it's superfluous, as the JOINs already do the filter. Each query handle different move lines.

**Pull request merged**
