### PR TITLE
[12.0] update upstream cd21c016b06

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Merge remote-tracking branch 'odoo/12.0' into 12.0-update-upstream-cd21c016b06

Without conflicts

**Desired behavior after PR is merged:**

Adds support for 0.0.0 versions migration scripts (https://github.com/odoo/odoo/commit/7b16abbae1d3af0e57730be872cef6b1f7d7a244)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Same problem here...

**Comment by MiquelRForgeFlow** [comment]
The conflict happens in the method of how ocabot does the merge. The PR is correct. If you click on "create a merge commit", you will not have this kind of conflict.

**Comment by sbidoul** [comment]
@mreficent @pedrobaeza It's worth understanding why a simple `git rebase --autosquash` fails. Is it due to the autosquash? Or something else?

**Comment by pedrobaeza** [comment]
I think it's due to the rebase plains commit structure, and when there has been conflict resolution in the merge commit (in the past), this happens. I have found similar things recreating commit history when migrating modules.

**Comment by sbidoul** [comment]
That's plausible indeed. Thanks @pedrobaeza

**Pull request merged**
