### PR TITLE
[16.0][OU-ADD] sale_expense: Nothing to do

### PR DESCRIPTION
**Pull request by diamondnguyenkc**
Nothing to do

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration sale_expense

<dependency></dependency>

**Comment by remi-filament** [comment]
Hi @diamondnguyenkc don't you think that [noupdate_changes](https://github.com/OCA/OpenUpgrade/blob/16.0/openupgrade_scripts/scripts/sale_expense/16.0.1.0/noupdate_changes.xml) should be enforced during migration ?

**Review by victoralmau — CHANGES_REQUESTED** [review]
Please add the `upgrade_analysis_work.txt` file and don't forget to take into account the changes in the `noupdate_changes.xml` file.

**Comment by remytms** [comment]
@victoralmau [This PR](https://github.com/OCA/OpenUpgrade/pull/4292) superseeds this one. Can you give it a look? :)

**Comment by pedrobaeza** [comment]
Superseded by #4292

**Pull request closed without merging**
