### PR TITLE
[17.0][OU-ADD] rating: Nothing to do

### PR DESCRIPTION
**Pull request by acpMicrocom**

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration rating

<dependency></dependency>

**Review by rvalyi — APPROVED** [review]
seems OK

important commit to check though https://github.com/akretion/odoo-module-diff-analysis/blob/main/17.0/rating/c000_________%2B-%23_103966_imp-mail-rating-various-support-base-rating-feature-in-mail-thread.patch

**Comment by legalsylvain** [comment]
@acpMicrocom : could you rebase ?

**Comment by pedrobaeza** [comment]
You have pulled instead of rebasing. Please rebase it properly.

**Comment by acpMicrocom** [comment]
Re-opened as #4643

**Pull request closed without merging**
