### PR TITLE
[12.0] [IMP] website_partner: Convert field BS3 > BS4

### PR DESCRIPTION
**Pull request by pedrobaeza**
Depends on:

- [x] https://github.com/OCA/openupgradelib/pull/148

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Yajo, please check the error in this simple conversion (that should be "no conversion):
```
Conversion of field 'website_description' for record with ID 9 for model 'res.partner' to BS4 failed.
Exception: XMLSyntaxError('Extra content at the end of the document, line 5, column 21',)
Original HTML content:
<p>
                Agrolait designs, develops, integrates and supports HR and Supply
                Chain processes in order to make our customers more productive,
                responsive and profitable.
                </p><p>
                Our experts invent, imagine and develop solutions which meet
                your business requirements. They build a new technical
                environment for your company, but they always take the already
                installed IT software into account. That is why Idealis
                Consulting delivers excellence in HR and SC Management.
                </p><p>
                Agrolait integrates ERP for Global Companies and supports PME
                with Open Sources software to manage their businesses. Our
                consultants are experts in the following areas:
                </p>
                <ul>
                    <li>Sales and Distribution</li>
                    <li>Materials Management</li>
                    <li>Inventory and Warehouse management</li>
                    <li>Customer Relationship Management</li>
                    <li>Personnel Administration</li>
                    <li>Talent Management</li>
                    <li>Reporting</li>
                </ul>
```

**Comment by yajo** [comment]
Don't you have a traceback?

**Comment by pedrobaeza** [comment]
See website_partner PR Travis log for that

**Comment by yajo** [comment]
Update it with new signature, it should work fine.

**Comment by pedrobaeza** [comment]
Which new signature? Please don't modify the API I have put.

**Comment by yajo** [comment]
I simplified it

**Comment by pedrobaeza** [comment]
Comment on the other PR. As said, you must keep the same API.

**Comment by yajo** [comment]
I have restored it, changed the call here.

**Comment by yajo** [comment]
Please remove my commit.

**Pull request merged**
