### PR TITLE
[12.0] update upstream abc0ecd6965

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Merge remote-tracking branch 'odoo/12.0' into 12.0-update-upstream-abc0ecd6965

Without conflicts

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
`The job exceeded the maximum log length, and has been terminated.` 🙄

**Comment by pedrobaeza** [comment]
And it's because 2 errors that Odoo has introduced:
```
2019-09-12 15:24:38,474 5664 INFO openupgrade odoo.fields: Field stock.picking.move_ids_without_package depends on non-stored field stock.move.picking_type_entire_packs 

2019-09-12 15:24:38,477 5664 INFO openupgrade odoo.fields: Field stock.picking.move_line_ids_without_package depends on non-stored field stock.move.line.picking_type_entire_packs
```

**Comment by MiquelRForgeFlow** [comment]
I don't think these are errors, because they appear as INFO.

**Comment by pedrobaeza** [comment]
Well, technically they aren't, as it's only information (but denotes something bad, as that depends won't be recomputed correctly), and that's why it appear. The problem is that this message floods totally the log. Look the number of appearances...

**Comment by MiquelRForgeFlow** [comment]
But without this PR, the branch 12.0 also has that information. It's not something new from this PR.

**Comment by pedrobaeza** [comment]
And why it's now so frequent?

**Comment by MiquelRForgeFlow** [comment]
I see as equal frequent. It appears for first time when loading `stock`. And then, it repeats at the same places in the log. It's not something new from this PR.

**Comment by pedrobaeza** [comment]
Yeah, but the problem with Travis is that in this occasion, the number of lines of the log has been exceeded, and it's due to that message.

**Comment by MiquelRForgeFlow** [comment]
I just compared. It's as you say, these two lines over repeated, like spamming.

**Comment by MiquelRForgeFlow** [comment]
Issue done in odoo. Waiting feedback.

**Comment by pedrobaeza** [comment]
Is this working now?

**Comment by MiquelRForgeFlow** [comment]
> Is this working now?

Still same problem.

**Comment by pedrobaeza** [comment]
Where is the line error?

**Comment by MiquelRForgeFlow** [comment]
> Where is the line error?

> `The job exceeded the maximum log length, and has been terminated.`

**Comment by pedrobaeza** [comment]
Ah, OK, so it's the verbose logging thing. Isn't you going to revert those commits?

**Comment by sswapnesh** [comment]
> Ah, OK, so it's the verbose logging thing. Isn't you going to revert those commits?

In https://github.com/odoo/odoo/pull/36885

**Comment by pedrobaeza** [comment]
@sswapnesh are you sure that commit fixes this? I don't think so.

**Comment by sswapnesh** [comment]
My bad, No It not this one

**Comment by MiquelRForgeFlow** [comment]
Replaced by https://github.com/OCA/OpenUpgrade/pull/2044.

**Pull request closed without merging**
