### PR TITLE
[IMP] use git urls for all projects

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
:no_entry_sign: don't merge this before we have resolved #137

**Comment by pedrobaeza** [comment]
This can be review and merge now.

**Comment by pedrobaeza** [comment]
Anyone can review?

**Comment by StefanRijnhart** [comment]
As I wrote on #137, 6.1 had some issues (but they don't impact migrations I think) but 6.0 still needs validation.

**Comment by pedrobaeza** [comment]
Tomorrow I'm going to make a 5.0 > 6.0 migration, so I can validate it as well.

**Comment by StefanRijnhart** [comment]
As I tried to indicate, it is not just if some migration succeeds but we need close file inspection. In line with review on PRs, it should be done by someone other than you because you migrated the branch in the first place.

**Comment by pedrobaeza** [comment]
OK, no problem, but I will inform about any possible issue I find.

Happy new year!

**Comment by legalsylvain** [comment]
:+1: Thanks.

**Comment by pedrobaeza** [comment]
Do you think this can be put now safely?

**Comment by pedrobaeza** [comment]
Can we move with this PR or we should still wait?

**Comment by StefanRijnhart** [comment]
Well, that is crap. I merged a PR that contained an update from upstream which contained the dreaded 'Fixes #139' somewhere in a commit msg, referring to issue 139 on Odoo itself of course...

Merging this now anyway.

**Pull request merged**
