### PR TITLE
[FIX] don't write implied groups on all users

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Today was merged the same fix in v10 of Odoo

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
They added also non regresion tests in https://github.com/odoo/odoo/commit/65ad60665e54a7e61d3d064df63457d0097587bd

**Comment by StefanRijnhart** [comment]
@pedrobaeza do you know how long it takes until the commit ends up in upstream 11.0? May as well take this version, right?

**Comment by pedrobaeza** [comment]
They usually do it once a week.

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart it is already ported in v11

**Comment by pedrobaeza** [comment]
It's seems the forward port has been done 42 minutes ago :smiley:

**Comment by StefanRijnhart** [comment]
Great!

**Comment by StefanRijnhart** [comment]
Do you want me to prepare the upstream merge?

**Comment by pedrobaeza** [comment]
Yes, please

**Comment by StefanRijnhart** [comment]
Here you go: https://github.com/OCA/OpenUpgrade/pull/1463

**Pull request closed without merging**
