### PR TITLE
[10.0][MIG] survey + survey_crm

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Did <code>survey</code> and <code>survey_crm</code> together: <code>#NothingToDo</code>

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This migration is incorrectly set as "Nothing to do". These lines should be attended renaming groups:
```
NEW res.groups: survey.group_survey_manager
NEW res.groups: survey.group_survey_user
DEL res.groups: base.group_survey_manager
DEL res.groups: base.group_survey_user
```

**Comment by pedrobaeza** [comment]
@hbrunn please don't go too fast before checking these things.

**Comment by pedrobaeza** [comment]
@mreficent please make another PR amending this.

**Comment by hbrunn** [comment]
thanks @pedrobaeza, didn't pay attention to this indeed

**Comment by MiquelRForgeFlow** [comment]
ok @pedrobaeza, I will do a fix.

**Pull request merged**
