### PR TITLE
[10.0] binary fields to attachment deferred

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Port of https://github.com/OCA/OpenUpgrade/pull/1009

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
I confirm this works, and it seems that only `datas` field of `slide.slide` model have changed to `attachment=True`.

**Comment by StefanRijnhart** [comment]
There is also field cache from model pos.cache. Anyway, green now.

**Comment by StefanRijnhart** [comment]
Let me add a protection to allow tests_deferred not to break tests in which website_slides is not installed.

**Comment by pedrobaeza** [comment]
Right, in my test DB I hadn't installed that module.  Merging when Travis finishes.

**Pull request merged**
