### PR TITLE
[14.0][OU-FIX] account: map old payment's state to move's state when filling account payment with no move

### PR DESCRIPTION
**Pull request by royle-vietnam**
Steps:
1. Payment is in cancel state and with no move
2. Run migration
3. Payment is in draft state

=> Expected: Payment is in cancel state

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
For other times, remember that this should be `[OU-FIX]` as commit code.

**Comment by MiquelRForgeFlow** [comment]
> For other times, remember that this should be [OU-FIX] as commit code.

Here is v14, all commits will be OU, so no need to put OU, IMO.

**Comment by pedrobaeza** [comment]
Well, not really. There are commits for the framework, analysis files, etc. I think it's good to keep the same nomenclature on that part.

**Pull request merged**
