### PR TITLE
[ADD] rename of web_widget_classes

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this something that you carry from 6.1 or from 7.0?

**Comment by hbrunn** [comment]
The module exists for 6.1 as web_widget_classes, and in my PR for 8.0 you asked for the rename. If ever there's a 7.0 version, it will also be called by the new name, so I think we should do the rename when going from 6.1 to 7

**Comment by StefanRijnhart** [comment]
Trivial ;-) :+1:

**Comment by pedrobaeza** [comment]
:+1: I merge then

**Pull request merged**
