### PR TITLE
[13.0] merge upstream 60d818f8b9e6b

### PR DESCRIPTION
**Pull request by StefanRijnhart**
plus updated analysis, noupdate changes, module coverage list.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
I think we need to update also the `noupdate_changes.xml` files and also update the module list in the source doc. Will you do it? I can do it if you prefer, no problem.

**Comment by MiquelRForgeFlow** [comment]
Also, do you plan on doing something else?

**Comment by StefanRijnhart** [comment]
Can you share your script to regenerate noupdate_changes? I'll check the module list.

I was looking at the base module, but just for fun.

**Comment by StefanRijnhart** [comment]
Module coverage doc updated. Also noticed `module/repository` mode in compare_noupdate_xml_records.py. One sec.

**Comment by StefanRijnhart** [comment]
All done. Thanks for the hints!

**Comment by MiquelRForgeFlow** [comment]
> Can you share your script to regenerate noupdate_changes?

Just run it with:
```yml
--mode repository [...]/12.0/OpenUpgrade/addons [...]/13.0/OpenUpgrade/addons --write 13.0
```

**Comment by StefanRijnhart** [comment]
Yes, I had already discovered that and committed its results.

**Comment by StefanRijnhart** [comment]
@MiquelRForgeFlow what are you waiting for exactly?

**Comment by StefanRijnhart** [comment]
Oh, I see I've been pushing to the wrong branch. One sec.

**Comment by StefanRijnhart** [comment]
There now, see the two additional commits.

**Comment by MiquelRForgeFlow** [comment]
I see. The `compare_noupdate_xml_records.py` script needs a `sorted()` in some place. I will check.

**Comment by MiquelRForgeFlow** [comment]
I think I fixed it in https://github.com/OCA/OpenUpgrade/pull/2193. Could you update last commit using my fix?

**Comment by StefanRijnhart** [comment]
@MiquelRForgeFlow last commit now contains the noupdate comparison sorted according to your last improvement

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart Yeah, thanks. But during this last days odoo did some changes in `base_automation` and included new `account_debit_note` module, so this PR is a "bit" obsolete. Do you mean if I do a force push putting it up to day and with a new analysis and such? I know this is a bit time consuming, that's why I am proposing myself instead of asking you to do it again, hehe sorry.

**Comment by StefanRijnhart** [comment]
Can we just merge this and then you or me can do another run. This PR still has value as some (simple) conflicts were solved.

**Review by MiquelRForgeFlow — APPROVED** [review]
Oh, ok, no problem :+1:

**Pull request merged**
