### PR TITLE
[15.0][OU-ADD] hr_timesheet_begin_end: Rename hr_timesheet_activity_begin_end to hr_timesheet_begin_end

### PR DESCRIPTION
**Pull request by EmilioPascual**
Rename hr_timesheet_activity_begin_end to hr_timesheet_begin_end. This was forgotten when this PR: https://github.com/OCA/timesheet/pull/517 was merged.

MT-1700 @moduon

### CODE REVIEW

**Review by edlopen — APPROVED** [review]
LGTM! Thank you for noticing this!

**Comment by pedrobaeza** [comment]
@legalsylvain this module is not an Odoo one, but OCA, so it should be included in the migration issue.

**Comment by legalsylvain** [comment]
> @legalsylvain this module is not an Odoo one, but OCA, so it should be included in the migration issue.

sorry. I hadn't been paying attention !

**Pull request merged**
