### PR TITLE
[ADD] 'sale_crm' migration.

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As in previous PR, :+1:

**Comment by legalsylvain** [comment]
@StefanRijnhart Are you OK with this migration script ?
Regards.

**Comment by thomaspaulb** [comment]
This PR contains much less data than the previous one [https://github.com/OpenUpgrade/OpenUpgrade/pull/246].... is this meant as additional changes or to replace 246?

**Comment by legalsylvain** [comment]
@antiflu I did a mistake on the other PR, (including bad commit into it)
this is why I create a new one, and closed #246.
 #IHaveToLearnGitCommand

**Comment by thomaspaulb** [comment]
Ok yeah but, if I apply [this patch](https://patch-diff.githubusercontent.com/raw/OpenUpgrade/OpenUpgrade/pull/265.patch) to my OpenUpgrade, afterwards there is exactly one post migration query for sale_crm, and I can remember there being much more. OpenUpgrade now also fails on sale_crm. Was there more then contained within this patch, and if yes, where can I find it?

**Comment by legalsylvain** [comment]
Hi again, 
you can find the original PR I did here : https://github.com/grap/OpenUpgrade/commit/ff520cd9f91d70ad7b8ac2a264db44bfcd51a2fd
If OpenUpgrade fails, could you indicate more information ...
regards.

**Comment by thomaspaulb** [comment]
There is more code in that original PR... from this PR i just get:

```
def migrate_crm_lead_sale_order(cr):
    """Set new sale_order fields with value found in crm_lead, if
    sale_order.origin field mentions the crm_lead;
    - retrieve crm_lead.type_id to set sale_order.campaign_id;
    - retrieve crm_lead.channel_id to set sale_order.medium_id;
    """
    openupgrade.logged_query(cr, """
        UPDATE sale_order sale
        SET campaign_id = lead.campaign_id, medium_id = lead.medium_id
        FROM crm_lead lead
        WHERE sale.partner_id = lead.partner_id
        AND sale.origin like '% '||lead.id;
        """)
```

Failing with

```
File "/var/tmp/openupgrade/8.0/addons/sale_crm/migrations/8.0.1.0/post-migration.py", line 42, in migrate_crm_lead_sale_order
File "/var/tmp/openupgrade/8.0/server/openerp/openupgrade/openupgrade.py", line 512, in logged_query
logger.debug('Running %s', query % args)
TypeError: not enough arguments for format string
```

**Comment by legalsylvain** [comment]
> There is more code in that original PR... from this PR i just get:

This is refactoring. Theoreticaly, this code do the same things. If there is a problem, please mention it.

> Failing with

I'll fix that.
Regards.

**Comment by legalsylvain** [comment]
@antiflu : Fixed.

**Comment by hbrunn** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Pull request merged**
