### PR TITLE
[11.0][FIX] resource & project

### LINKED ISSUE #1363: [11.0] migration error in project when project_issue was not previously installed
Impacted versions:
11
Steps to reproduce:
Migrate a v10 database without project_issue installed.

Current behavior:
Traceback regarding missing relation project_issue, pretty much identical to #1000 but I lost it.

Traced it to  https://github.com/OCA/OpenUpgrade/blob/11.0/addons/project/migrations/11.0.1.1/post-migration.py#L38 and just added a return to get past and rest worked fine but obviously not the fix for all.

Expected behavior:

Video/Screenshot link (optional):

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Some bugs I found.

Fixes #1363

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Can you explain the rationale behind the dummy calendar?

**Comment by MiquelRForgeFlow** [comment]
I don't understand why really, but when I was doing a migration, the resource crashed with an integrity error. There was some query executed after pre-migration and before post-migration that checks if the required column had null values and if it had then crashes.

**Comment by pedrobaeza** [comment]
Please dig a bit more and further if you can assign other calendar that is not a dummy (maybe the default one).

**Comment by MiquelRForgeFlow** [comment]
Ok, I will dig a bit more 🙄

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza this is the traceback that I receive between the premigration and postmigration of the resource:
selection_022

**Comment by pedrobaeza** [comment]
That's only a warning, not an error.

**Comment by MiquelRForgeFlow** [comment]
Ok, but is there a way to fix this warning?

**Comment by pedrobaeza** [comment]
Well, I haven't analyze it. Don't you have any clue?

**Comment by MiquelRForgeFlow** [comment]
When a field is declared as `required`, it seems this `set_not_null` method is called. It adds a not_null_constrain to this column in the table. So that's why I thought that filling the null values with an unused value easy to find in post-migration would do the trick.

**Comment by pedrobaeza** [comment]
That's not the question here on migrations. You should wonder why a field is now required and before don't (or it even doesn't exist), and which is the normal expected value (maybe there's a sane default defined in the model and you only need to call set_default method of openupgradelib?)

**Comment by MiquelRForgeFlow** [comment]
Well, I give up. I will merge at least the project fix.

**Comment by pedrobaeza** [comment]
OK, merging this as is. I will investigate about the resource thing.

**Pull request merged**
