### PR TITLE
[ADD] product_images was renamed for 8

### PR DESCRIPTION
**Pull request by hbrunn**
cf https://github.com/OCA/product-attribute/tree/8.0/product_multi_image and https://github.com/OCA/product-attribute/tree/7.0/product_images

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Well, it's not exactly a rename, but a new module for the same feature, so I'm not sure of this one. The new module also depends on server-tools/base_multi_image.

**Comment by hbrunn** [comment]
yes, exactly. I'm busy writing an init hook for `base_multi_image` that will move the `product_images` table with the necessary adjustments if it exists on installation time. With the hook and this identity, an upgrade from 7 to 8 should go automatically.

**Comment by pedrobaeza** [comment]
OK then

:+1:

**Comment by legalsylvain** [comment]
thanks. :+1:

**Pull request merged**
