### PR TITLE
[ADD] l10n_es migration script.

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Deletes old account chart template data to allow a clean installation of new account chart template structure
- Map removed account types to new ones

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Looks good, even though I keep doubting about the need to remove update data. Should be harmless though. Only thing left is the two default values (model: ir.values) which are defined in the 7.0 version. Do they need removal as well? You do remove the records they point to.

**Comment by pedrobaeza** [comment]
Which ir.values do you refer? There's only new ones.

**Comment by StefanRijnhart** [comment]
In 7.0:

account_chart_assoc.xml:        &lt;record id="l10nES_chart_template_assoc_value" model="ir.values">
account_chart_pymes.xml:        &lt;record id="l10nES_chart_template_pymes_value" model="ir.values">
account_chart.xml:        &lt;record id="l10nES_chart_template_value" model="ir.values">

**Comment by pedrobaeza** [comment]
Ah, OK, that's old references, and they are harmless. I don't think it deserves to be treated here. databe_cleanup can do the job.

**Comment by StefanRijnhart** [comment]
OK, fine. :+1:

**Comment by pedrobaeza** [comment]
Please proceed then with the merge.

**Pull request merged**
