### PR TITLE
[IMP][14.0] base: remove all modules that have been deleted on target version to avoid warning module: not installable, skipped

### PR DESCRIPTION
**Pull request by hoangtiendung070797**
Perform the various steps required to uninstall all modules completelyincluding the deletion of all database structures created by the module: tables, columns, constraints, etc. and remove all modules

### CODE REVIEW

**Review by royle-vietnam — APPROVED** [review]
LGTM

**Review by hieu1211 — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I don't think the uninstallation should be done automatically, as it's a very hard and dangerous step, and also you can't recover from that step. For example, you forget to add a module to your addons path, and perform the migration, and get such module (and its dependants) uninstalled. That's too much IMO.

**Comment by royle-vietnam** [comment]
> I don't think the uninstallation should be done automatically, as it's a very hard and dangerous step, and also you can't recover from that step. For example, you forget to add a module to your addons path, and perform the migration, and get such module (and its dependants) uninstalled. That's too much IMO.

I think deleting junk data will bring more benefits than forgetting to add a module to your addons path
Also, when we do it wrong, we will need to do it again with backup database another

**Comment by pedrobaeza** [comment]
They are not junk, and you have to think in a cross version migration: you don't have module X in version 14, but your target is version 15, and you have such module in version 15. With this, you are uninstalling it in version 14 with no possibility of continuing. Besides, you have database_cleanup module for such cleaning (or later manual uninstallation).

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. Uninstalling unavailable modules is not possible because in a migration of various versions, modules can be anavailable in intermediate steps.

The objective of openupgrade is just to migrate.
You should use database_cleanup at the end, when your migration is ok.

Edit : sorry duplicate with pedro.

**Comment by hoangtiendung070797** [comment]
Thanks, i understand

**Pull request closed without merging**
