### PR TITLE
[11.0] Merged upstream up to 6edf49e

### PR DESCRIPTION
**Pull request by pedrobaeza**
6edf49e

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There has been several conflicts due to an extra argument on modules loading, but without too much impact.

@StefanRijnhart can you please kindly check this for starting the migration with this?

The main thing I need is to include this commit https://github.com/odoo/odoo/commit/73e213edef053c2e08d7791efe0b1a399da0eed7#diff-807e5ce512b0669468b040be7a9c470fL82 that removes a constraint that is preventing a proper merge of the quants.

**Comment by StefanRijnhart** [comment]
Small glitch here where you left out upg_registry:
https://github.com/Tecnativa/OpenUpgrade/blob/8bcde622f8b099ac529702245e1e4e6e19fe5dca/odoo/modules/loading.py#L442 (cf. https://github.com/OCA/OpenUpgrade/blob/11.0/odoo/modules/loading.py#L416)

Can you make upg_registry a keyword argument as well and put it last here:
https://github.com/Tecnativa/OpenUpgrade/blob/8bcde622f8b099ac529702245e1e4e6e19fe5dca/odoo/modules/loading.py#L309
You would have to adapt https://github.com/Tecnativa/OpenUpgrade/blob/8bcde622f8b099ac529702245e1e4e6e19fe5dca/odoo/modules/loading.py#L446 as well.

**Comment by pedrobaeza** [comment]
@StefanRijnhart changed according your comments.

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Pull request merged**
