### PR TITLE
[FIX] remove global bzrlib dependencies

### PR DESCRIPTION
**Pull request by coleste**
Since I don't have bzrlib installed, could someone validate from that side please?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Another option is to protect the import.

**Comment by coleste** [comment]
You mean making the calls right after import bzrlib.builtins?

**Comment by pedrobaeza** [comment]
No, putting `try:` ... `except ImportError:` block: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#importerror

**Comment by coleste** [comment]
Ok, but we don't want it to fail since it also can work with git. Bzr is not necessary.

Wait, ok - protect when we get in the bzr case itself...

**Comment by pedrobaeza** [comment]
With that, the script doesn't fail. As bzr is marginally, the solution you provide is good enough also.

**Comment by coleste** [comment]
yeah, all the migrations use git, so addon_config_type 'bzr' is a dead case now.

**Comment by legalsylvain** [comment]
:+1: thanks.

**Comment by mmalorni** [comment]
:+1:

**Pull request merged**
