### PR TITLE
[14.0][MIG] website_sale

### PR DESCRIPTION
**Pull request by Murtaza-OSI**

### CODE REVIEW

**Comment by flotho** [comment]
Does this PR need to be reviewed ?

**Comment by pedrobaeza** [comment]
Yes, all of them if you want. The more eyes on this, more possible bugs can be discovered.

**Comment by flotho** [comment]
@gaelTorrecillas @MAG-Florian-Chevalier , thanks for your review and share your latest tests please.

**Comment by mgielissen** [comment]
LGTM

**Comment by MiquelRForgeFlow** [comment]
Superseded by https://github.com/OCA/OpenUpgrade/pull/2994.

**Pull request closed without merging**
