### PR TITLE
[ADD] Migration of crm module

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Modifying set_message_last_post from api8.0 to write sql instead of orm to prevent some crm.lead write trigger from instantiating sale orders (while the sale order model has not yet been loaded).

### CODE REVIEW

**Comment by christophlsa** [comment]
Thanks for your work.

I got an error (I didn't looked in this. When I have time I try to fix this if you or someone else didn't):

```
2014-12-23 10:18:10,157 21355 INFO testdb openerp.modules.migration: module crm: Running migration [>8.0.1.0] pre-migration
2014-12-23 10:18:10,157 21355 INFO testdb openerp.modules.migration: module crm: Running migration [>8.0.1.0] pre-migration
2014-12-23 10:18:10,158 21355 INFO testdb OpenUpgrade: crm: pre-migration script called with version 7.0.1.0
2014-12-23 10:18:10,158 21355 INFO testdb OpenUpgrade: model crm.case.channel: renaming to crm.tracking.medium
2014-12-23 10:18:10,171 21355 INFO testdb OpenUpgrade: model crm.case.resource.type: renaming to crm.tracking.campaign
2014-12-23 10:18:10,173 21355 INFO testdb OpenUpgrade: table crm_lead, column channel_id: renaming to medium_id
2014-12-23 10:18:10,174 21355 INFO testdb OpenUpgrade: table crm_lead, column type_id: renaming to campaign_id
2014-12-23 10:18:10,174 21355 INFO testdb OpenUpgrade: table crm_lead, column priority: renaming to openupgrade_legacy_8_0_priority
2014-12-23 10:18:10,175 21355 INFO testdb OpenUpgrade: table crm_phonecall, column priority: renaming to openupgrade_legacy_8_0_priority
2014-12-23 10:18:10,178 21355 DEBUG testdb OpenUpgrade: Running UPDATE ir_model_data SET module = crm, name = crm_medium_direct WHERE module = crm and name = crm_case_channel_direct
2014-12-23 10:18:10,178 21355 DEBUG testdb OpenUpgrade: 1 rows affected
2014-12-23 10:18:10,179 21355 DEBUG testdb OpenUpgrade: Running UPDATE ir_model_data SET module = crm, name = crm_medium_email WHERE module = crm and name = crm_case_channel_email
2014-12-23 10:18:10,179 21355 DEBUG testdb OpenUpgrade: 1 rows affected
2014-12-23 10:18:10,179 21355 DEBUG testdb OpenUpgrade: Running UPDATE ir_model_data SET module = crm, name = crm_medium_phone WHERE module = crm and name = crm_case_channel_phone
2014-12-23 10:18:10,179 21355 DEBUG testdb OpenUpgrade: 1 rows affected
2014-12-23 10:18:10,181 21355 DEBUG testdb OpenUpgrade: Running UPDATE ir_model_data SET module = crm, name = crm_medium_website WHERE module = crm and name = crm_case_channel_website
2014-12-23 10:18:10,181 21355 DEBUG testdb OpenUpgrade: 1 rows affected
2014-12-23 10:18:10,182 21355 DEBUG testdb OpenUpgrade: Running UPDATE ir_model_data SET module = crm, name = mail_alias_lead_info WHERE module = crm and name = default_sales_alias
2014-12-23 10:18:10,182 21355 DEBUG testdb OpenUpgrade: 1 rows affected
2014-12-23 10:18:10,319 21355 INFO testdb openerp.modules.module: module crm: creating or updating database tables
2014-12-23 10:18:15,610 21355 ERROR testdb openerp.sql_db: bad query: ALTER TABLE "crm_lead" ADD FOREIGN KEY ("medium_id") REFERENCES "crm_tracking_medium" ON DELETE set null
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "crm_lead" violates foreign key constraint "crm_lead_medium_id_fkey"
DETAIL:  Key (medium_id)=(7) is not present in table "crm_tracking_medium".

2014-12-23 10:18:15,618 21355 CRITICAL testdb openerp.service.server: Failed to initialize database `2014-12-04-leaserad_migrated`.
Traceback (most recent call last):
  File "/var/tmp/openupgrade/8.0/server/openerp/service/server.py", line 901, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 398, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 295, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/loading.py", line 186, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/8.0/server/openerp/modules/module.py", line 290, in init_module_models
    obj._auto_end(cr, {'module': module_name})
  File "/var/tmp/openupgrade/8.0/server/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/models.py", line 2749, in _auto_end
    cr.execute('ALTER TABLE "%s" ADD FOREIGN KEY ("%s") REFERENCES "%s" ON DELETE %s' % (t, k, r, d))
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/var/tmp/openupgrade/8.0/server/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: insert or update on table "crm_lead" violates foreign key constraint "crm_lead_medium_id_fkey"
DETAIL:  Key (medium_id)=(7) is not present in table "crm_tracking_medium".
```

**Comment by StefanRijnhart** [comment]
Thanks for testing! Can you tell me
- if this lead indeed has channel_id 7 in your 7.0 database, and
- if you have such an entry in crm_case_channel with id 7 in your 7.0 database, and then
- if you have the following foreign key in your 7.0 database (use '\d crm_lead' in a psql session)
  "crm_lead_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES crm_case_channel(id) ON DELETE SET NULL
- does this entry exist

**Comment by christophlsa** [comment]
Old database:

```
# SELECT count(id) FROM crm_lead WHERE channel_id=7;
 count 
-------
    83
(1 row)

2014-12-04-leaserad=# SELECT count(id) FROM crm_case_channel WHERE id=7;
 count 
-------
     1
(1 row)

...
Foreign-key constraints:
    "crm_lead_channel_id_fkey" FOREIGN KEY (channel_id) REFERENCES crm_case_channel(id) ON DELETE SET NULL
...
```

The problem is that the table "crm_tracking_medium" does not exists in the new database at this point:

```
# \d crm_tracking_medium
Did not find any relation named "crm_tracking_medium".
```

Odoo creates/changes the tables in the wrong order I guess. But I don't know how to fix this (aside from creating the tables manually in the pre-migration).

**Comment by StefanRijnhart** [comment]
This seemed to work for me but it turns out I forgot to rename the table. Please check the latest revision.

**Comment by christophlsa** [comment]
the migration works now (not tested in backend or something else), thanks :+1:

**Comment by pedrobaeza** [comment]
Everything seems fine. Thanks for the work.

:+1:

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
