### PR TITLE
[13.0] apriori: merge several modules in account_menu

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Was done in https://github.com/OCA/account-financial-tools/pull/889.

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Should not be the following ? 

        'account_coa_menu' : 'account_menu',
        'account_group_menu': 'account_menu',
        'account_tag_menu': 'account_menu',
        'account_type_menu': 'account_menu',

?

See : https://github.com/OCA/account-financial-tools/pull/889/commits/b43721e3693508dbff8bf722b87385ff2ea8e0f0#diff-65742a0ecfa18244c1f46891e029565923c17b582d3f8d040c03f46a01b1dfe9L6

otherwise, LGTM.

**Comment by MiquelRForgeFlow** [comment]
Thanks @legalsylvain :)

**Review by legalsylvain — APPROVED** [review]
thanks !

**Comment by legalsylvain** [comment]
trivial patch.

/ocabot merge nobump

**Pull request merged**
