### PR TITLE
[MIG][15.0] auth_oauth: nothing to do

### PR DESCRIPTION
**Pull request by sang250399**
This PR
======
Nothing to do

### CODE REVIEW

**Review by jcdrubay — APPROVED** [review]

**Review by TeoGoddet — APPROVED** [review]
Thanks !

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Now that web and base_setup are merged, only pending the migration of auth_signup.

**Comment by sang250399** [comment]
> Now that web and base_setup are merged, only pending the migration of auth_signup.



> auth_signup

I will have PR migration module auth_signup soon

**Comment by StefanRijnhart** [comment]
@sang250399 you're doing amazing work, thank you!

**Comment by tranngocson1996** [comment]
@StefanRijnhart I see he has a lot of PR merged, but the 'contribute' tag is still missing? Or, wait a minute, what a terrible flaw! 😢

**Comment by pedrobaeza** [comment]
I don't get you, Tran

**Comment by tranngocson1996** [comment]
SR, I miss writing. It's Github fault?
This is what i mean 😄 
aâaaaa

**Comment by MiquelRForgeFlow** [comment]
Merged in https://github.com/OCA/OpenUpgrade/pull/3467.

**Pull request closed without merging**
