### PR TITLE
[15.0][OU-ADD] pos_order_mgmt: Merged in point_of_sale

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
@Tecnativa TT45178

This module offers the option to see past orders in the fronted, so it is possible to operate with them for re-printing them or performing a return . This is already accomplished in odoo 15 core, with extra functionallities. To acces them you must select you're desired order in the "Orders" tab of the frontend, and on the panel there will be the buttons that allows you to perform this actions. 
There is one function that is not present in core, which is the option of "duplicate/copy" an order. By using this function, when it's button is pressed the exact products and quantities of the order are setted in order to be used for another order. This could justify the creation of a specific module for preserving this feature.

@chienandalu please review!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And the commit history?

**Comment by pedrobaeza** [comment]
Oh, sorry, I have been confused by the commit name. Please don't put something as migration. See other PRs doing similar things for the proper commit message, starting with `[OU-ADD]`.

**Comment by stefan-tecnativa** [comment]
> Oh, sorry, I have been confused by the commit name. Please don't put something as migration. See other PRs doing similar things for the proper commit message, starting with `[OU-ADD]`.

Understood, I looked for an old example that I've done, not recent ones. Changed commit and title message.

**Comment by pedrobaeza** [comment]
It should be `[OU-ADD] pos_order_mgmt: Merged in point_of_sale`.

**Review by chienandalu — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Don't be afraid of writing too much... You are now saying that the module is been merged, but not why. Which features this module contains that can be done now in standard? You can add that on the extended message of the commit (and also on the first PR comment).

**Comment by pedrobaeza** [comment]
@stefan-tecnativa please fill the commit message with the requested explanation.

**Comment by stefan-tecnativa** [comment]
I think this is ready now @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
