### PR TITLE
Add/11.0/merge upstream 06de947b6b

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Merging upstream Odoo up until commit 06de947b6b, mainly to include @hbrunn's https://github.com/odoo/odoo/commit/65ad60665e54a7.

Only conflict:

```
--- a/odoo/modules/migration.py
+++ b/odoo/modules/migration.py
@@@ -18,12 -18,19 +18,25 @@@ from odoo.tools import pycompa
  if pycompat.PY2:
      import imp
      def load_script(path, module_name):
 +        # OpenUpgrade edit start:
 +        # Removed a copy of migration script to temp directory
 +        # Replaced call to load_source with load_module so frame isn't lost and breakpoints can be set
          fp, fname = tools.file_open(path, pathinfo=True)
++<<<<<<< HEAD
++=======
+         fp2 = None
+ 
+         # pylint: disable=file-builtin,undefined-variable
+         if not isinstance(fp, file):
+             # imp.load_source need a real file object, so we create
+             # one from the file-like object we get from file_open
+             fp2 = os.tmpfile()
+             fp2.write(fp.read())
+             fp2.seek(0)
+ 
++>>>>>>> 06de947b6b
          try:
 -            return imp.load_source(module_name, fname, fp2 or fp)
 +            return imp.load_module(module_name, fp, fname, ('.py', 'r', imp.PY_SOURCE))
          finally:
              if fp:
                  fp.close()
```

Conflict caused by https://github.com/odoo/odoo/commit/9f8eae34d1d8#diff-6d3fdea7af4358946ee202d25095b776

I took the opportunity to readd the lines that were removed in OpenUpgrade, but in a disabled way. Hope that this leads to less conflicts in this section in the future.

Diff after resolving conflict:

```
--- a/odoo/modules/migration.py
+++ b/odoo/modules/migration.py
@@ -18,15 +18,28 @@ from odoo.tools import pycompat
 if pycompat.PY2:
     import imp
     def load_script(path, module_name):
-        # OpenUpgrade edit start:
-        # Removed a copy of migration script to temp directory
-        # Replaced call to load_source with load_module so frame isn't lost and breakpoints can be set
         fp, fname = tools.file_open(path, pathinfo=True)
+        fp2 = None
+
+        # OpenUpgrade edit start:
+        # Don't copy the migration script into a temp directory. Instead,
+        # replace the call to load_source with a call to load_module so  that
+        # the frame isn't lost and breakpoints can be set
+        # pylint: disable=file-builtin,undefined-variable
+        if False and not isinstance(fp, file):
+            # imp.load_source need a real file object, so we create
+            # one from the file-like object we get from file_open
+            fp2 = os.tmpfile()
+            fp2.write(fp.read())
+            fp2.seek(0)
+
         try:
             return imp.load_module(module_name, fp, fname, ('.py', 'r', imp.PY_SOURCE))
         finally:
             if fp:
                 fp.close()
+            if fp2:
+                fp2.close()
``` 

The full diff of this section with core Odoo 11.0 is now:

```
>         # OpenUpgrade edit start:
>         # Don't copy the migration script into a temp directory. Instead,
>         # replace the call to load_source with a call to load_module so  that
>         # the frame isn't lost and breakpoints can be set
29c25
>         if False and not isinstance(fp, file):
---
<         if not isinstance(fp, file):
37c33
>             return imp.load_module(module_name, fp, fname, ('.py', 'r', imp.PY_SOURCE))
---
<             return imp.load_source(module_name, fname, fp2 or fp)
```

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the work and the detailed info about the conflicts. Maybe you can add such information on the merge commit for self-documenting this.

There's seems there have been changes on some l10n_de* that leads to the error on Travis.

**Comment by MiquelRForgeFlow** [comment]
And also the odoo v11 branch now is red. When it gets green again, this PR should be updated again.

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart you can now update the PR. odoo v11 branch is now green

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart could you put also the conflicts in the commit message?

**Comment by pedrobaeza** [comment]
Can you re-check the noupdate_changes.xml file for l10n_de_skr04 after the update for avoiding the error?

**Comment by StefanRijnhart** [comment]
Thanks for the pointers! Superseded by https://github.com/OCA/OpenUpgrade/pull/1466

**Pull request closed without merging**
