### PR TITLE
[FIX] Get migration tests from module/migration/tests

### PR DESCRIPTION
**Pull request by kos94ok-3D**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by kos94ok-3D** [comment]
@StefanRijnhart
Can you review it?

**Comment by StefanRijnhart** [comment]
Oh, but I like having the tests in migrations/\<version\>. Why does it need to change?

**Comment by kos94ok-3D** [comment]
importlib.import_module can not correctly interpret the version folder, so we can not have a structure:
<pre>
Module
    | migration
        | 13.0.1.3
            | tests
</pre>
But we can have:
<pre>
Module
    | migration
        | tests
</pre>
and use tags in order to filtered tests
Rewrite for migration folder?

**Comment by StefanRijnhart** [comment]
Thanks for the explanation! But in order to be able to put tests in module/migration/tests, don't you need to keep at least `.migrations` as the prefix instead of dropping the prefix at all?

**Comment by kos94ok-3D** [comment]
Is it ok?

**Comment by StefanRijnhart** [comment]
Ah thanks for the update. If we have tests in <module>/migrations, then I don't think we need specific tags. Or do you think that will be useful someway?

**Comment by kos94ok-3D** [comment]
Just try to do something new.
I don't need in it.

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
