### PR TITLE
[10.0] [ADD] mrp_byproduct migration scripts

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Migration scripts.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
:)

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
Please remember to link and update proper migration issue.

**Comment by MiquelRForgeFlow** [comment]
Done

**Pull request merged**
