### PR TITLE
[11.0] update upstream d9b2605eadc

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Updated.

No conflicts.

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why so many changes in noupdate file? Have you modified something on the script that gets the file? Maybe you can use old one in this case for keeping a minimal diff?

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza I don't want to compare record by record. Don't care the amount diff, just changing `res.country` and `res.currency` things up to day. The no_update_changes generator script was changed a bit, yes, in order to have always a unique sorted output.

**Comment by pedrobaeza** [comment]
As said, I prefer that you keep the old version for 11.0 and 12.0. The new sorted one must be used in >=13.0 only.

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza done!

**Pull request merged**
