### PR TITLE
[FIX] project: Deal with forcecreate=False records

### PR DESCRIPTION
**Pull request by pedrobaeza**
Let's see if we have all the cases covered. I have included a test for that.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@mreficent this is what I was talking about on the other PR, but I decided to do it myself as I don't have it clear that everything is going to be correct.

@hbrunn my fear with `mode='update'` is that we don't get updated the rest of the existing records.

**Comment by hbrunn** [comment]
I tried this yesterday but `mode=update` didn't work, because of https://github.com/OCA/OCB/blob/10.0/odoo/addons/base/ir/ir_model.py#L1212 - we have an xmlid, so this will act just the same. Haven't found a good solution yet.

**Comment by pedrobaeza** [comment]
I think we need to modify the core..

**Comment by hbrunn** [comment]
I'd rather not do anything at all with those records as far as xml files are concerned, and do conditional writes in python code where necessary. We're talking about a couple of records per release, right?

**Comment by pedrobaeza** [comment]
Well the pity is to not have an standard way to do it. Maybe what we can do is to filter out the non existing records in openupgradelib method.

**Comment by pedrobaeza** [comment]
You know: if you don't have it automated, for sure we will have problems in the future when we forget to do the specific thing.

**Comment by hbrunn** [comment]
sure, standard ways are better. If you want to commit time to this, perfect. Otherwise, we'll better revert the commit loading this for the project migration, as I believe real world databases tend to have the record deleted

**Comment by hbrunn** [comment]
@pedrobaeza  this PR works with https://github.com/OCA/openupgradelib/pull/80

**Comment by hbrunn** [comment]
@pedrobaeza as of https://github.com/OCA/openupgradelib/pull/80, you'll have to pass `mode='init_no_create'`

**Comment by StefanRijnhart** [comment]
Did you consider leaving out the noupdate entries from the project module in 10 that only disable the earlier forcecreate=False items from 9.0? If the migrated database is from Odoo 8.0 the entries won't exist (which causes the problem you are trying to solve here) and if the database was installed from version 9.0 the entries will have been cleaned up or reused(!) during the 9.0 lifecycle by the customer.

**Comment by StefanRijnhart** [comment]
As per my previous comment I am proposing https://github.com/OCA/OpenUpgrade/pull/1124

**Comment by StefanRijnhart** [comment]
After the merge of #1124, this is no longer needed I believe.

**Comment by pedrobaeza** [comment]
Well, yes, but I still want to try the test.

**Comment by pedrobaeza** [comment]
Uhm, strange error, but anyway tests are correct. I close this PR then.

**Pull request closed without merging**
