### PR TITLE
[10.0] res.country.state migration now works on manually-created records that don't have XMLID

### PR DESCRIPTION
**Pull request by alexis-via**
--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why do you want to do this?

**Comment by alexis-via** [comment]
Well... I want to do this to make the migration work... it's as simple as that :) Without this, it just doesn't work when the res.country.states have been created manually (so they don't have an XMLID).

**Comment by pedrobaeza** [comment]
I still don't have the problem. What is the error?

**Comment by StefanRijnhart** [comment]
Reading through the code, it looks like the original code only worked if state records already had an XML id (either from a custom or a localization module, or an __export__ id). This change then adds an XMLID if necessary (and not just update an existing XMLID). Looks good to me!

**Review by StefanRijnhart — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Yeah, but my question is in which part later the XML-ID is needed? This is only for avoid duplications when loading later core states AFAIK, so there's no added value on adding XML-IDs for non existing states.

**Comment by alexis-via** [comment]
Yes, without this PR, Odoo will generate new res.country.state upon upgrade, so the upgrade will fail on the sql constraint unique(country_id, code), cf https://github.com/odoo/odoo/blob/10.0/odoo/addons/base/res/res_country.py#L101

**Comment by pedrobaeza** [comment]
Where in the code Odoo generates that states?

**Comment by StefanRijnhart** [comment]
Here: https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/addons/base/migrations/10.0.1.3/openupgrade_analysis_work.txt#L73-L658

**Review by pedrobaeza — APPROVED** [review]
OK, now I see the workflow. Thanks for the improvement.

**Pull request merged**
