### PR TITLE
[10.0] Update from upstream up to b144e09a10e7084cb96c2b420e6b7713834f7866

### PR DESCRIPTION
**Pull request by mvaled**
In the same accord as PR #895 it can be beneficial to have a updated 10.0 branch.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Closing and reopening for triggering a Travis build with the correct $TRAVIS_COMMIT variable

**Comment by MiquelRForgeFlow** [comment]
Should'nt the merging conflict be resolved first?

**Comment by pedrobaeza** [comment]
I don't see any conflict, Miquel.

**Comment by MiquelRForgeFlow** [comment]
Oh, sorry, forget my comment 😅

**Comment by pedrobaeza** [comment]
Uhm, again the same problem with the checkout operation. @mvaled have you worked with the latest 10.0 branch?

**Comment by mvaled** [comment]
@pedrobaeza I was able to do a "full" migration of an Odoo 9 demo DB with several modules installed using this branch.

**Comment by mvaled** [comment]
I see that `.travis.yml` has these steps:

```
    - git fetch --depth 2 origin 9.0
    - git reset --hard `git ls-remote |grep refs/heads/9.0 |awk '{print $1}'`
```

Are those correct for the 10.0 branch?

**Comment by pedrobaeza** [comment]
That steps are needed or loading demo data in a 9.0 database that is later migrated and tested on the CI. I have tried to make a rebase on your branch and there are conflicts, so you haven't applied correctly the update on latest 10.0 branch. I advise you to start again the process with a fresh 10.0 branch.

**Comment by mvaled** [comment]
Ok... trying again:  the 10.0 branch of OpenUpgrade points to 4436f7aa568.  I did a hard reset of this PR's branch onto the current 10.0, and redid the merge from Odoo's 10.0 brach at commit odoo/odoo@b144e09a10e7084cb96c2b420e6b7713834f7866

The only conflict was again `odoo/tools/convert.py` and the same solution was applied.

**Comment by mvaled** [comment]
It's seems that when I pushed the reset Github closed this PR.  Reopening.

**Comment by pedrobaeza** [comment]
There's still something incorrect that prevent Travis to check this PR. What you need to do is over an update 10.0 branch of OpenUpgrade, run `git pull odoo 10.0`, being `odoo` the remote for github.com/odoo/odoo.

**Comment by mvaled** [comment]
Trying again:

```bash
$  git checkout 10.0
Checking out files: 100% (29423/29423), done.
Switched to branch '10.0'
Your branch is up-to-date with 'upstream/10.0'.

$ git remote -v | grep upstream
upstream	git@github.com:OCA/OpenUpgrade.git (fetch)
upstream	git@github.com:OCA/OpenUpgrade.git (push)

$ git fetch -v upstream
remote: Counting objects: 57, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 57 (delta 39), reused 42 (delta 25), pack-reused 0
Unpacking objects: 100% (57/57), done.
From github.com:OCA/OpenUpgrade
   4436f7aa568..d18d3a39c6e  10.0       -> upstream/10.0
 = [up to date]              5.0        -> upstream/5.0
 = [up to date]              6.0        -> upstream/6.0
 = [up to date]              6.1        -> upstream/6.1
 = [up to date]              7.0        -> upstream/7.0
 = [up to date]              8.0        -> upstream/8.0
   b1171fdd679..882552b56ab  9.0        -> upstream/9.0
 = [up to date]              test       -> upstream/test

$ git merge upstream/10.0 --quiet 

$ git checkout 10.0-upstream-b144e09a10e7084cb96c2b420e6b7713834f7866 --quiet 

$ git reset --hard 10.0
HEAD is now at d18d3a39c6e Merge pull request #902 from reinka/10.0-website_sale_digital

$ git remote -v | grep odoo-upstream
odoo-upstream	git@github.com:odoo/odoo.git (fetch)
odoo-upstream	git@github.com:odoo/odoo.git (push)

$ git fetch odoo-upstream --quiet

$ git merge odoo-upstream/10.0 
Auto-merging requirements.txt
Auto-merging odoo/tools/convert.py
CONFLICT (content): Merge conflict in odoo/tools/convert.py
Auto-merging odoo/modules/registry.py
Auto-merging odoo/modules/graph.py
Auto-merging odoo/models.py
Auto-merging odoo/addons/base/ir/ir_ui_view.py
Auto-merging odoo/addons/base/ir/ir_model.py
Removing doc/business.rst
Removing doc/_static/banners/m_accounting.jpg
Removing doc/_static/banners/m_2.jpg
Removing doc/_static/banners/m_1.jpg
Auto-merging addons/account/models/account_invoice.py
Resolved 'odoo/tools/convert.py' using previous resolution.
Automatic merge failed; fix conflicts and then commit the result.

[ ... reviewing the resolution and changing ...]

$ git commit -m "Merge from upstream up to `git rev-parse --short odoo-upstream/10.0`"
[10.0-upstream-b144e09a10e7084cb96c2b420e6b7713834f7866 b3098d7b438] Merge from upstream up to 10c6908c63c

$ git push -f github   # my fork in github
```

**Comment by mvaled** [comment]
I don't know why $TRAVIS_COMMIT is pointing to 7dd0c0c069a98bdb0aec0d6bf3d91a8d593bfe18 when:
```
$ git rev-parse 10.0-upstream-b144e09a10e7084cb96c2b420e6b7713834f7866
b3098d7b43895530cb0a4db42bde2479066259b8

```

**Comment by mvaled** [comment]
Another try with 9d8746e3a7ff906703fcb0656aa8aab52a4cfcbe.

**Comment by mvaled** [comment]
Hi @pedrobaeza, Finally travis went green on this.

**Comment by pedrobaeza** [comment]
Can you please specify the conflict resolution you have made?

**Comment by mvaled** [comment]
The only conflict was `openerp/tools/convert.py`:

```patch
$ git diff --cached -- odoo/tools/convert.py
diff --git a/odoo/tools/convert.py b/odoo/tools/convert.py
index 368fcc34f56..82cc1084445 100644
--- a/odoo/tools/convert.py
+++ b/odoo/tools/convert.py
@@ -252,8 +252,6 @@ form: module.record_id""" % (xml_id,)
                 modcnt = self.env['ir.module.module'].search_count([('name', '=', module), ('state', '=', 'installed')])
                 assert modcnt == 1, """The ID "%s" refers to an uninstalled module""" % (xml_id,)
 
-        if len(id) > 64:
-            _logger.error('id: %s is to long (max: 64)', id)
         openupgrade_log.log_xml_id(self.cr, self.module, xml_id)
 
     def _tag_delete(self, rec, data_node=None, mode=None):
```

Should I `git push -f` with this in the commit message?

**Comment by mvaled** [comment]
Well, I made another push.  Let's hope travis gets it.

**Comment by MiquelRForgeFlow** [comment]
Green! I can't believe! 😄

**Comment by pedrobaeza** [comment]
OK, thank you very much for the effort! Merging.

**Comment by MiquelRForgeFlow** [comment]
Shouldn't a new migration analysis be run to update the analysis files? 🤔

**Comment by pedrobaeza** [comment]
Not in theory, as the stability rule from Odoo forbids to change the DB layout once the version is published. The other time was different, as the analysis was done before the v10 release, and they said that the freeze was done, but it was not really frozen at all. Even that, on a critical bug, I remember a change in DB layout after the release, but on version 7 or 8, so it's very improbable that there are changes right now, but if you want to try and you have all prepared for the analysis, you can do it to be sure.

**Pull request merged**
