### PR TITLE
[ADD] pre migration script

### PR DESCRIPTION
**Pull request by archetipo**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by hbrunn** [comment]
please also update the [documentation](https://github.com/OCA/OpenUpgrade/blob/10.0/odoo/openupgrade/doc/source/modules90-100.rst)

**Comment by archetipo** [comment]
thanks @hbrunn  done

**Comment by hbrunn** [comment]
I just noticed you also should rename the xmlids or `ir.rule` and `ir.model.access`. What I also forgot was to ask you to create an `openupgrade_analysis_work.txt` file which is a copy of the original analysis file, but with comments and what the migrations does. That's helpful for fellow developers. Check existing files for examples

**Comment by archetipo** [comment]
ok, thanks @hbrunn

**Comment by hbrunn** [comment]
thanks

**Pull request merged**
