### PR TITLE
hr_timesheet_sheet_week_start_day merged into hr_timesheet_sheet

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
See https://github.com/OCA/hr-timesheet/pull/136.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
something is wrong in openupgradelib

**Comment by pedrobaeza** [comment]
Well, latest changes on merge records have affected stock migration scripts. Can you check it?

**Comment by MiquelRForgeFlow** [comment]
Solved in https://github.com/OCA/openupgradelib/pull/121.

**Comment by MiquelRForgeFlow** [comment]
Another bug again :S

**Comment by MiquelRForgeFlow** [comment]
Solved in https://github.com/OCA/openupgradelib/pull/122.

**Pull request merged**
