### PR TITLE
[ADD] base_setup: Analysis file + migration script

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Failing while #795 is not merged.

**Comment by pedrobaeza** [comment]
I include 6c4dd0a5807fe1e340f14231ecfd906da0faba19 meanwhile it's merged.

**Comment by pedrobaeza** [comment]
@hbrunn, shouldn't coverage only be for migration scripts?

**Comment by hbrunn** [comment]
@pedrobaeza we miss https://github.com/OCA/OpenUpgrade/blob/9.0/.coveragerc - shouldn't this have been cherry picked from 9?

**Comment by pedrobaeza** [comment]
Well, I don't know how that was treated for the initial 10.0 branch, but we can cherry-pick it in any moment. Preparing the PR...

**Comment by hbrunn** [comment]
an extra commit here doesn't hurt imho

**Comment by pedrobaeza** [comment]
OK, you're right using the optimistic merging...

**Review by hbrunn — APPROVED** [review]

**Pull request merged**
