### PR TITLE
[UPG] rename mrp_jit -> procurement_jit

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1: finally some simple stuff to review :-)

**Comment by pedrobaeza** [comment]
Don't you need to rename the module also in base module? As far as I know, with this, you are only renaming it for analysis purpose, but not really rename it in a migration.

**Comment by hbrunn** [comment]
@pedrobaeza not since https://github.com/OpenUpgrade/OpenUpgrade/commit/a58e37604f418dc40d73961f55438f4798515b93
:+1:

**Comment by pedrobaeza** [comment]
Ok, thanks for the clarification.

:+1:

**Pull request merged**
