### PR TITLE
[16.0][OU-ADD] base_vat: Nothing to do

### PR DESCRIPTION
**Pull request by remytms**
There is two views that where removed. But they are not needed anymore and I presume they will be deleted by the upgrade mechanism.

It depends on `account` which has no migration script yet.

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration base_vat

<dependency>Depends on : 

- account : #4070</dependency>

**Comment by pedrobaeza** [comment]
Please change tag to  `[OU-ADD]`.

**Review by alexis-via — APPROVED** [review]

**Pull request merged**
