### PR TITLE
Project - merge only after product has migration script merged

### PR DESCRIPTION
**Pull request by gfcapalbo**
Description of the issue/feature this PR addresses:
nothing to do in project , but  merge only After product has a migration script

Current behavior before PR:
project is not set as migrated
Desired behavior after PR is merged:
project set as  

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by lfreeke** [comment]
product is merged

**Comment by pedrobaeza** [comment]
But why don't you update also documentation?

**Comment by pedrobaeza** [comment]
Please rename also as good practice removed fields for storing them in case of being need by any other module.

**Comment by gfcapalbo** [comment]
added documentation

**Comment by hbrunn** [comment]
actually, there's something to do as @pedrobaeza pointed out: https://github.com/OCA/OpenUpgrade/pull/848#pullrequestreview-40835045
I'll close this PR and we'll continue on #848

**Pull request closed without merging**
