### PR TITLE
[16.0] [OU-FIX] base: convert translatable text columns to jsonb

### PR DESCRIPTION
**Pull request by marielejeune**
Previously we just converted varchar columns, but there exist some html fields that are translatable. Html fields are text columns in DB.

### CODE REVIEW

**Comment by marielejeune** [comment]
Hi @hbrunn, here is a minor fix for migrating HTML translatable fields. Could you have a look please?

**Review by hbrunn — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@marielejeune when you say HTML translatable fields, do you mean those with `translate=html_translate`? If so, AFAIK this requires extra work. Seeing code, it seems just `Text` fields, which are not HTML (or at least, they are not translated by fragments).

**Comment by marielejeune** [comment]
> @marielejeune when you say HTML translatable fields, do you mean those with `translate=html_translate`? If so, AFAIK this requires extra work. Seeing code, it seems just `Text` fields, which are not HTML (or at least, they are not translated by fragments).

No I was just speaking of fields.Html fields, with translate=True attribute, as body_html in mail.template for example.
https://github.com/odoo/odoo/blob/1430644908d7d9a3119a1315389f5bf11888356a/addons/mail/models/mail_template.py#L59

**Comment by pedrobaeza** [comment]
OK, let's go then.

**Pull request merged**
