### PR TITLE
[14.0][FIX] account: Only fill account.move>payment_id when account.payment>move_id is set

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Oversight of https://github.com/OCA/OpenUpgrade/pull/3570.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We should remove the matching by name or payment_ref as well, isn't it?

**Comment by MiquelRForgeFlow** [comment]
Why? Do you have any issue with those queries?

**Comment by pedrobaeza** [comment]
They can match things that are not correct, even for draft payments.

**Comment by MiquelRForgeFlow** [comment]
Ok, wait, let me do some testings.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
