### PR TITLE
[9.0][FIX] account: Create new sequence instead of renaming

### PR DESCRIPTION
**Pull request by pedrobaeza**
When converting old fiscal years sequences to new range style, there can be the case where the same sequence is used in several intervals, so renaming will lead to an error on the second renaming.

Thus, we create a new sequence instead of renaming.

@Tecnativa

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
cannot you do the following?

first, check whether if exists new_seq_name. if exists, then create new one. if not exists, do the rename.

**Comment by pedrobaeza** [comment]
That can't be, as for the second occurrence, we will lose the firstly renamed and we won't know which is the following number.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
I didn't go deep with this, but I believe in you.

**Comment by pedrobaeza** [comment]
Tested this weekend in a migration.

**Pull request merged**
