### PR TITLE
[12.0][FIX] Include this tax to be able to migrate the 303 Spanish tax report

### PR DESCRIPTION
**Pull request by flachica**
**Description of the issue/feature this PR addresses:**

If I is installed [l10n_es_aeat_mod303](https://github.com/OCA/l10n-spain/tree/12.0/l10n_es_aeat_mod303) the process be will stopped

**Current behavior before PR:**

The update process stop with error

Desired behavior after PR is merged:

The update process continue

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This mustn't be done this way, but synchronizing whole repo with latest upstream.

**Comment by flachica** [comment]
Where is the documentation to make this update? Is that done automatically by someone? Would it have been better to put an issue? Maybe with a little more information I can collaborate better next time. If not, next time you can do not do any PR. This repository is heavy and I would like not to waste time or resources if later I am not able to allow my work to be used by the community. Cc @pedrobaeza

**Comment by pedrobaeza** [comment]
It's just to do `git pull odoo 12.0` over this repo and propose the PR with that.

**Comment by pedrobaeza** [comment]
Similar PRs: #2407 and #2409

**Comment by MiquelRForgeFlow** [comment]
Done in https://github.com/OCA/OpenUpgrade/pull/2425.

**Pull request closed without merging**
